### ISSUE TITLE
Identify Roles and Permissions to Use in Wagtail

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1120]
To ensure only approved and public-ready content is posted on the website, we need to identify roles for content managers and permissions to allow managers to effectively curate the content that appears on the site.

**Comment by AmyKort** [comment]
@gsmaragdis

**Comment by patphongs** [comment]
Had a meeting with @gsmaragdis. From our discussion, it appears that there are no additional wagtail groups needed. Currently there are 2, which is editor (no publish rights) and moderator (publish rights). Everyone will be able to upload images and documents.  

Also met with @jameshupp to discuss and he also agreed that this issue is now more of a formal workflow and content governance documentation for the FEC's content team. He will be working with the content team to draft this up. This documentation is extra helpful to keep current content owners aware of the formal processes and procedures as well as getting new content owners up to speed.

**Comment by AmyKort** [comment]
@patphongs Thanks for the great notes! With the meetings you had last week with Press and Public Records, are we ready to take next steps?

**Comment by patphongs** [comment]
@AmyKort I think at the very least we could start creating the permission groups. Then we can pull the trigger on actually implementing the permission groups once everyone is happy with the proposed permissions that are set.

**Comment by AmyKort** [comment]
Great! Since we've completed our documentation of the permissions requirements of our content managers, we can close this issue.

**Comment by patphongs** [comment]
Reopening this issue to implement new Wagtail roles and permissions.

**Comment by patphongs** [comment]
In order to identify roles and permissions, we need to develop a list of page owners. Closing in favor of this ticket: #4155
