### ISSUE TITLE
Build audit search page

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#1304]
Build detailed datatable page for the audit listings

- [ ] Build datable page, Front-end
     - [ ] URLs.py
     - [ ] page to link from
     - [x] make API run locally

:art: [Designs & notes](https://github.com/18F/openFEC-web-app/issues/2261#issuecomment-330275144) for table and filters

Original web-app issue: https://github.com/18F/openFEC-web-app/issues/2324

@xtine

**Comment by johnnyporkchops** [comment]
Linked to PR : https://github.com/18F/fec-cms/pull/1381

**Comment by jenniferthibault** [comment]
Question— I believe this is the issue that implaments the audit search interface (or the nearest I can find to it).

Since that work has not been merged/implemented, can we re-open this issue while the work is in progress and underway?

If this isn't the right issue, then I haven't been able to find it, so please point me the right way! I wasn't able to find any in progress audit issues, and a little worried we might not be tracking it visibly.

**Comment by AmyKort** [comment]
Our next step will be to complete testing with the audit team to make sure the search is returning expected results.

**Comment by AmyKort** [comment]
It looks like we're going to have a series of smaller tickets that come out of the testing phase. Can we close this issue in favor of those?
