### ISSUE TITLE
Implement content for downloadable data accordions in Adv. data tabs

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1400]
After setting up the new Adv data page and accordion styles in https://github.com/18f/fec-cms/issues/1309, add the accordions to the tabs and fill them with real content and links.

## Designs from https://github.com/18F/openFEC-web-app/issues/2318

🖥  [Invision prototype](https://gsa.invisionapp.com/share/K5DYFESA8#/258343763_Advanced-Data_Raising)

Click into each accordion to see the different content and layouts 

**Basic design templates to implement:**
![screen shot 2017-10-26 at 8 17 26 pm](https://user-images.githubusercontent.com/11636908/32082605-c0a47fba-ba8a-11e7-98df-87e6d86d86b3.png)
![screen shot 2017-10-26 at 8 17 42 pm](https://user-images.githubusercontent.com/11636908/32082606-c0b2e1b8-ba8a-11e7-92ca-f07ed2ef77d4.png)

**Using:**

- Intro content from https://github.com/18F/openFEC-web-app/issues/2321
- Prepared template changes from https://github.com/18f/fec-cms/issues/1309
- This  📝 [Google Doc](https://docs.google.com/a/gsa.gov/document/d/1UldBI9T_Bhz8j-CPoCr7LViBOEYLZNtbZnH8BgMd7mk/edit?usp=sharing) of content for title, year, and description content in accordions
- Issue for creating metadata pages to link to: (coming)

**Completion criteria:**

- [ ] Link years to files downloads in each accordion
- [ ] Connect links to metadata wagtail pages in each accordion from https://github.com/18F/fec-cms/issues/1399
- [ ] Add description content in each accordion

**Comment by llienfec** [comment]
II went through the data catalog S3 location spreadsheet to define links by year.  This blocker is mostly resolved, links by year are included in the spreadsheet.  I also highlighted the URL patterns and when those patterns don't work.  

Two small issues remain:

1. The link for Committee Report Summary was actually the link for Committee Summary.  Looked through the S3 bucket and am not sure which file is the right one for Committee Report Summary.  Maybe @jwchumley can point us in the right direction while @PaulClark2 is out?  On classic, the file name is CampaignandCommitteeSummaryAction.  If this takes too long to resolve, we could leave this out and add it in later.

2.  Two download types, electioneering communications and leadership pacs & sponsors, have 2007-2008 on the design mock ups, but I can't find those data files in the S3 bucket.  Since many other download types only go back to 2009-2010, we could start with that two year period here as well if we can't find/don't have files for 2007-2008.

Still in progress - QCing that the data that would be downloaded matches classic.  Method: use the data catalog on classic to perform the search, see how many results come up.  Then, download the new file, compare the number of results in excel (use line number, minus 1 line for the header row).  The number of results should be the same for both searches.  The QCing process has been started, but not finished.

Let me know if you have any questions!  Big thanks to @jenniferthibault for showing me how to browse the S3 bucket!

**Comment by llienfec** [comment]
Continued quality checking the data to make sure that the new downloads match what is available on the classic site. 

In all but one instance, the results match exactly.  For ECs, there's a slight difference in output for 2018.  This may be that the new bulk download's output (showing 4 lines of results) is in a different format from the one on classic (showing 1 result).  

Details: The 1 result is on both outputs.  2 of the results may be descriptor lines for the result above.  A result labeled for the 2016 election is also showing up.  I don't have time to dive deeper today.  Will try to look later this week, but may need to wait for Paul to help explain.

**Comment by jenniferthibault** [comment]
Thank you so much for double checking this data @llienfec and unblocking this issue and the PR! 

Connecting the spreadsheet to this issue:
- 📄 [Data catalog S3 links](https://docs.google.com/spreadsheets/d/1TRUX0fbC0_S_Hwe9rvxfx5EZAN93IfW-bY2zuqUXMUU/edit#gid=0)


@johnnyporkchops looks like this can move #1603 mostly forward, but we need to check with @PaulClark2 on Lauren's questions above to find the right files or see if these are all we have on the following categories:
- Candidate summary
- Electioneering communications
- Leadership PACs and sponsors

Lauren has put comments in the  📝 [Google Doc](https://docs.google.com/a/gsa.gov/document/d/1UldBI9T_Bhz8j-CPoCr7LViBOEYLZNtbZnH8BgMd7mk/edit?usp=sharing) of accordion content + in the spreadsheet linked just above. Between the two, if questions come up as you go along please ask!

**Comment by johnnyporkchops** [comment]
Thanks @jenniferthibault and @llienfec for pulling this together!

**Comment by AmyKort** [comment]
where are we with this issue?

**Comment by llienfec** [comment]
@johnnyporkchops This work is finished and will be in the next release, right?
