### ISSUE TITLE
Improve findability of more keyword options feature for statutes

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1436]
The "more keyword options" link appears on the search results page of the statutory search ( https://www.fec.gov/data/legal/search/statutes/?search= ), but not the main search page for statutes ( https://www.fec.gov/data/legal/statutes/ ). So that users understand that Boolean search functionality is available for statutes (either through the main keyword search box or the more keyword options box), we should provide the "more keyword options" link on the main search page for statutes as well.

**Comment by jenniferthibault** [comment]
Thanks for spotting this @AmyKort , it was not an intentional design choice to leave that feature out here. 

Here's a quick mockup of the change we're seeking to add:
![screen shot 2017-11-08 at 11 52 59 am](https://user-images.githubusercontent.com/11636908/32561946-7cc5899c-c47b-11e7-9b9b-d87a68641133.png)
