### ISSUE TITLE
Improve findability of more keyword options function for regulations

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1437]
The "more keyword options" link appears on the search results page of the regulations search ( https://www.fec.gov/data/legal/search/regulations/?search=&search_type=regulations), but not the main search page for regulations ( https://www.fec.gov/regulations ). So that users understand that Boolean search functionality is available for regulations (either through the main keyword search box or the more keyword options box), we should provide the "more keyword options" link on the main search page for regulations.

**Comment by jenniferthibault** [comment]
Like https://github.com/18F/fec-cms/issues/1436, this was move of an oversight than an intentional design choice, BUT editing the eRegs interface is more complex than editing the rest of the site.

Here's a quick mockup of the change we're seeking to add:
![screen shot 2017-11-08 at 11 59 44 am](https://user-images.githubusercontent.com/11636908/32562363-74241d5c-c47c-11e7-9ded-4f705f58f472.png)

**Comment by AmyKort** [comment]
If we have a chance to take up this issue, would it make sense to tackle https://github.com/18F/fec-eregs/issues/365 ? Or does this not streamline the work?
