### ISSUE TITLE
Add new GitHub issue template to CMS and API repositories that covers feature and bug options

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#1499]
Inspired by the PR template @jenniferthibault added (https://github.com/18F/fec-cms/pull/1453) 

I collaborated w/ @PaulClark2 on this, thanks!

So that we can have better information and completion criteria for features and bugs, we should add a issue template to our fec-cms and openFEC GitHub repositories. 

[GitHub instructions for creating issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) 

Suggestion for template:

-------

**If this is a feature or task, use "Feature" sections below. If it's a bug, use "Bug sections" below.** 

**Please include relevant labels (ie "Bug").** 

-------

### 1) Expected Outcome
_Plain language explanation of desired change_

### 2)  Value to Project

_Explain why this change is important_

### 3) Completion Criteria (required)
_Explain what steps are needed_

- [ ] Example

### 4) Screenshots, if helpful

-------

### 1) Steps to Reproduce
_Where did you click, what browser, etc_

### 2) Completion Criteria (required)

- [ ] Example

**Comment by jenniferthibault** [comment]
Great @lbeaufort!

One very minor request— for everything on the site our practice is to use sentence case capitalization (where the first letter of only the first word in the sentence is capitalized, unless it's a proper noun)  to keep things more readable and approachable. We've tried to keep that practice going through the repos, though I'm not sure how closely we're tracking. Could we switch the titles to sentence case here instead of title case (where the first letter of every word is capitalized)?

i.e. use this formatting

> 1) Expected outcome
> 2) Value to project
> 3) Completion criteria (required)

instead of this formatting
> 1) Expected Outcome
> 2) Value to Project
> 3) Completion Criteria (required)

**Comment by jenniferthibault** [comment]
Oops, I hit enter too soon— one suggestion on the tontent of the template:

Instead of, or in addition to `Value to project`, let's keep the focus on the user need the issue or feature would address. How this issue impacts people using the site it critical to understanding why it matters in a user-centered approach. "Value to project" feels stakeholder driven.

Using a user story to fill in the field might look something like this:

### User need this addresses:
"_As a __(type of user)___ , I want _____(a goal or objective)_________ , so that _____(the benefit or value they get from being able to accomplish their goal)________"

"As a journalist, I want to be able to reliably access data on the FEC website, so that I can meet my work deadlines and write timely stories."

If it's valuable to users, it will be valuable to the project. Sometimes, the user will be an internal user.
