### ISSUE TITLE
Committee filing filters not working on Internet Explorer

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1521]
When trying to narrow down this committee filings by Form Type (i.e. PAC and Party financial statements Form 3X) or Years (i.e. 2015-2016), users are  unable to select either, or any option for that matter, after clicking on the arrow for the menu options. This is only happening in IE.

IE version 11 (test windows 10 as well)

* URL: https://www.fec.gov/data/filings/?data_type=processed&amp;committee_id=C00001313

**Comment by johnnyporkchops** [comment]
I think this but has something to do with IE11/Edge support for `querySelectorAll` and `matches()`. We seem to have polyfills or fixes for this built into our codebase that is transpiled to the cached js files, but for some reason they are still throwing errors. I will continue to dig into to JS directories to figure this out. 

This error goes away when emulating IE 10 via the developer console (function > F12 > emulaton
In the meantime, this could be fixed by emulating IE10 instead of Edge in the IE compatibility meta-tag on /meta-tags.jinja:
` <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10"> `
Hopefully future releases of IE Edge and IE, will fix this. (though IE is notorious for fixing one bug and creating another when it comes to browser versions.)

Does anyone think emulating IE10, just on /data templates is problematic? It is not ideal, but may be a viable interim solution until wither IE or fixes thsi problem or we can find and fix it in our code.

Anyone who has any input or ideas on how to fix the code so it works without setting the X-UA meta tag, please chime in.

**Comment by johnnyporkchops** [comment]
Thanks @xtine .I think it does already use jQuery. Question: Is jQuery code transpiled into vanilla JS via Babel or something along those lines?

**Comment by xtine** [comment]
What I mean, is that the jquery selector method `$('.selector')` is equivalent to `document.querySelectorAll('.selector')`. Except, jQuery has backwards compatible support for legacy and outlier browsers.

Babel is only needed to compile ES6 code to ES5 (standard JavaScript). The only place that uses ES6 is the legal section that utilizes React. If you look at the Webpack configuration, we are just combining and minifying JavaScript files.

**Comment by johnnyporkchops** [comment]
Clicking the dropdown in IE debug mode triggers the `querySelectorAll` error. That error persists even when the dropdown works properly in IE10 emulation mode. I was unable to determine how, if at all,  that error might actually cause the dropdown problem in IE 11/Edge.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by patphongs** [comment]
Since some staff has tested the new fix already and has not reported any issues in internet explorer with it. I think this is good to close. Resolving PR: https://github.com/fecgov/fec-cms/pull/1901
