### ISSUE TITLE
Occupation field returning no results for individual contributor search before 2002

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1522]
@fec-issue-bot commented on [Tue Sep 19 2017](https://github.com/18F/FEC/issues/4545)

## What were you trying to do and how can we improve it?
Received a phone about the occupation field not working for Individual Contributions from 2002 back to 1980.  Ran a for the 2000 Election Cycle using CEO and got zero results.  Went to Classic and ran the same search and got 6 results. 

- [ ] confirm data is there but not being found by search
- [ ] Decide on correct approach (always search both employer and occupation for occupation?)

## General feedback?
Please fix

## Tell us about yourself
Public Records Staff on behalf of a caller.

## Details
* URL: https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2000&amp;min_date=01%2F01%2F1999&amp;max_date=12%2F31%2F2000&amp;contributor_occupation=ceo
* User Agent: Amazon CloudFront

---

@jbucelato commented on [Tue Sep 19 2017](https://github.com/18F/FEC/issues/4545#issuecomment-330666522)

Please note, if you put anything in the occupation field, teacher, professor, etc., it yields no results.

Might be a performance issue
Might be a data issue - looks like occupations are blank for that time period: https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&two_year_transaction_period=2000&min_date=01%2F01%2F1999&max_date=12%2F31%2F2000&sort=-contribution_receipt_date&per_page=100&contributor_occupation=-null&is_individual=true

**Comment by jwchumley** [comment]
Looks like several things going on here. This may be missing data but it also is likely caused by the fact that in older data employer and occupation were concatenated into a single employer column. THe occupation column is empty.  In the legacy individual contributor search we search that column for both employer and occupation. 

As for missing, I haven't been able to find these six transactions either through the interface or directly from the API using name and image number to try to find them
![image](https://user-images.githubusercontent.com/12615919/36542728-aeb167f0-17af-11e8-8035-1e0cbdd8135b.png)

**Comment by jwchumley** [comment]
Will address this in help screens. THe data prior to April of 2003 were stored with employer and occupation concatenated on one field so we'll explain to use the employer search for both employer and occupation prior to 2003
