### ISSUE TITLE
Research Common Data Usage Issues: Usability 2/3

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1660]
**What we're after:** FEC.gov has been experiencing problems regarding its data, including usability of particular data sets. These problems. negatively impact user confidence in our data and inevitably with the FEC's overall customer experience. While performance issues are known and have been logged, one issue in particular has also outlined other needs that prompt additional research, including data usability. 
We'll use this research as a baseline for developing tests as well, based on our better understanding of how people use the site and the problems they might encounter.
 
**Research tasks:**
 - [ ] Speak with internal FEC staff about problems expressed by users
 - [ ] Review user feedback issues for common problems
 - [ ]  Conduct data user interviews to identify pain points
 - [ ] Identify and organize themes
 - [ ] Discuss/mock-up solutions

This is the second in a series of research tasks from #1505

**Comment by jenniferthibault** [comment]
Minor note on research practice: When possible, we should also (or primarily) interview users whenever we are interviewing FEC staff (who are internal stakeholders) so that we make sure we hear peoples' experience directly. 

FEC staff have been great at representing common external user questions/pitfalls through the course of this project, but it's good quality assurance to validate it with users themselves as well. We often don't get the motivations/rationale behind users' choices or questions when we rely on internal staff's perspectives, or they can only guess/conjecture as to user motivations.

The feedback issues submitted to the repository are one part of that, but if we can conduct direct interviews, I'd always advocate for that!

**Comment by JonellaCulmer** [comment]
Closing, no longer relevant.
