### ISSUE TITLE
Contributions with $0 in the aggregate field are missing from individual search

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1668]
User has an issue where contributions are not showing up on the website.  He conducted a little research and it appears that when the "aggregate" field for an individual is $0, it won't show up in the receipts search.  

**Examples:**
- Dunn, Gary gave $225 to C00101105 on the 2017 M11 report, received 11/16/17.  The aggregate is $0 and it doesn't show up on the individual search.           
- C00071365's 2017 M11 has a lot of these.

I'm not sure if it was an active choice to not show these contributions.  It may be difficult to link the contributions to their refunds, which is important info too.  However, there's also good case that these contributions should show up because they're on the reports, if we have a case where a contribution is refunded due to its illegality or an event in the news (straw donor scheme, etc.), the public would still want to see that.  Also, committees can and do report the aggregate field's information incorrectly.

**Comment by lbeaufort** [comment]
Thanks, @llienfec! It looks like an API issue. I don't believe that's by design.
API query:
https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&committee_id=C00101105&two_year_transaction_period=2018&min_date=11%2F16%2F2017&max_date=11%2F16%2F2017&sort=-contribution_receipt_date&per_page=30&is_individual=true
