### ISSUE TITLE
Adjust submenu designs based on testing results

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1799]
We want to make sure users can quickly and easily find the information they're looking for. To improve users' experience on the site, we tested two options for enhancements to the submenus at the FEC's February conference. Our next step is to adjust our submenu designs based on the results of those testing sessions.

Completion criteria:
- [x] review prior research, including what research contributed to current design, as well as AZ conference
- [x] adjust designs as necessary
- [x] review preliminary mock-ups in design sync with the larger design team including PMs, if possible, make any additional adjustments as necessary
- [ ] move designs to followup issue

**Comment by JonellaCulmer** [comment]
Documenting previous menu issues that lead to our current state:

Consider adding nav items for raising and spending breakdowns
https://github.com/18F/openFEC-web-app/issues/1686

Finalize site navigation menus
https://github.com/18F/fec-style/issues/655#issuecomment-290218725

Users struggle to find individual contributions via the main navigation menu
https://github.com/18F/openFEC-web-app/issues/2061.

**Comment by JonellaCulmer** [comment]
Following on design sync this afternoon, we have come away with a menu design to prototype and test in upcoming sprints. There are some last discussions that need to take place, include a conversation with the content team on the language used in the menus to improve on the navigation to the landing pages. 

From usability testing, we were able to determine that the use of the menu links is still highly desirable as we could not get a conclusive determination that the no menu option was the better option. As long as links within the menu are available, our users will use them to get to the content they are most interested in. Therefore, we are focused on restructuring the menu in order to improve navigation to the landing pages. 

Below are the mock-ups for the Campaign finance data, Help for candidates and committee, and Legal resources tabs menus. 

### Campaign finance data
<img width="1128" alt="screen shot 2018-03-14 at 4 38 23 pm" src="https://user-images.githubusercontent.com/31663028/37430349-47cfee40-27a8-11e8-9433-8810af4d553b.png">

### Help for candidates and committees
<img width="1128" alt="screen shot 2018-03-14 at 4 43 04 pm" src="https://user-images.githubusercontent.com/31663028/37430354-4dbdab4e-27a8-11e8-8edf-4c470f7670ab.png">

### Legal resources
<img width="1129" alt="screen shot 2018-03-14 at 4 43 18 pm" src="https://user-images.githubusercontent.com/31663028/37430365-532768cc-27a8-11e8-8ead-5c96dd9f2e63.png">

Next steps: 
- [ ] Move to new issue for content to think through the language for each of these new menu options. Something that incorporates a verb or call-to-action to prompt users to navigate to the landing pages

**Comment by JonellaCulmer** [comment]
These designs have been moved to a content issue, here: https://github.com/fecgov/fec-cms/issues/1862
