### ISSUE TITLE
Adjust election summary display designs

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1800]
We want to make sure users can quickly and easily understand the money raised and spent in a particular race. To improve users' experience on the site, we tested a new election summary display at the FEC's February conference. Our next step is to adjust our designs based on the results of those testing sessions.

Completion criteria:
- [x] adjust designs as necessary
- [x] review preliminary mock-ups in design sync with the larger design team including PMs, if possible, make any additional adjustments as necessary
- [x] move designs to testing issue

**Comment by JonellaCulmer** [comment]
Following a productive discussion during 3-9-18 design sync, the team has decided to move forward with the following mock-up for the election summary pages. 

The below designs are updated following the research findings that were gleaned from the usability testing conducted at the Scottsdale conference. Those updates include:
- improving the visibility of the Dates and deadlines cards, on both the data and about pages, which lead users to the overall dates and deadlines links for all elections. The color for the active cards was changed from gray to blue. The blue is used consistently across all CFD pages. 
- improve the visibility of the reporting deadlines buttons at the bottom of each data section. Incorporating an icon to introduce the section adds a bit more visual interest to grab user's attention. 

### **About this election page**
![aboutthiselection_031218](https://user-images.githubusercontent.com/31663028/37303366-9f1da91c-2604-11e8-99e1-afeac462dc01.jpg)

### **Election data and reporting deadlines page**
![electiondatapage_031218](https://user-images.githubusercontent.com/31663028/37303374-aa27be38-2604-11e8-9790-7286b7249b75.png)

## **Next steps:**
- [ ] Content team review of the language used to describe the data that composes the `Candidate financial totals` table on the data page. 

Needs to be updated because as it's currently written it applies more to the Processed v. Raw data, but this might confuse those who are looking at just this totals table. It must also be considered that data tables also now include "Coverage ending" date. 

Currently, that language reads: "Candidate financial totals come from processed data that has been categorized by the FEC. It may not include the most recently submitted electronic filings. Raw data may show more recent filings."
@AmyKort @llienfec @rhoughfec @dorothyyeager

**Comment by AmyKort** [comment]
How about: "This table only shows candidates who have registered and filed a financial report. Information in this table may not include the most recently submitted filings."

@llienfec @rhoughfec @dorothyyeager

**Comment by JonellaCulmer** [comment]
Thanks, @AmyKort! If there are no objections, this can go into the prototype that @patphongs is working on for testing during sprint 5.3.

**Comment by patphongs** [comment]
@JonellaCulmer @AmyKort I just finished up coding out the updates to the election profile page for user testing. Hopefully we'll get some sign-ups for next week. https://fec-feature-cms.app.cloud.gov/data/elections/house/AZ/01/2018/

Just for clarity, this branch has been deployed to feature space: `feature/election-page-redesign-updated`

**Comment by JonellaCulmer** [comment]
Moving this to a testing issue: https://github.com/fecgov/fec-cms/issues/1869
