### ISSUE TITLE
Add help text to indiv and all receipts occupation search field

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1878]
Why we want this:
Occupations in data from before 2003 were concatenated into the employer column so searches by occupation don't work in the older data.

What we want to do. Take this fabulous bit of text crafted by our very own Amy Kort:
"Use the employer field to search by occupation in reports filed before 2003"
and add it as context help here (just one option for displaying information): 

![image](https://user-images.githubusercontent.com/12615919/37790105-f4887448-2ddb-11e8-8ed2-2a036862266b.png)
- [x] research options
- [ ] add to both the "Individual contributor" search and the "All receipts" search

**Comment by JonellaCulmer** [comment]
**Design review:**
This filtering issue is a unique situation. In order for users to understand that they need to use a different filter to complete their search of individual contributors by occupation, we need to make it easy for them to make the switch. 

The initial proposal for this design solution was to use a tooltip to provide this information. However, using a tooltip may add additional undue burden for our users. Knowing you need to switch to the employer filter to continue your search is required information. Our tooltip pattern provides helpful information and additional context to our users, but it's not information that may determine search results. It is not required information. Therefore it would better serve our users by making this information prominent. We'll be able to  so that this required information can be utilized and not have to be sought out in order to complete an accurate search of individual contributors or receipts. 

**Design recommendation:** 
My recommendation would be to use example type text to explain when to use the occupation and employer fields along with the language previously approved: _"Use the employer field to search by occupation in reports filed before 2003"_ 

This will make the information in the filter panel more prominent, better unite these two very similar filters, and explain the relationship between the two. In this design, the two filters are switched with occupation listed first, and the accompanying text above it. By switching the order, we create a better flow. This will allow users to see the first filter, and if their search involves a time period prior to 2003, they can easily move down the list to the employer field and continue with their search. 

<img width="363" alt="screen shot 2018-05-02 at 3 32 18 pm" src="https://user-images.githubusercontent.com/31663028/39546113-4474c410-4e21-11e8-952b-04b665a9af9a.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/1976
