### ISSUE TITLE
Write new language for "no data" messages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1892]
**What we're after:** Data messages that explain why data may be missing from a particular table need to be revisited. For elections that have long passed, we need to elaborate further, or modify the language used. At present, we give two reasons why data is not present. Either a filing deadline has not passed, or a deadline has passed but the FEC is still processing it. Neither of those circumstances apply to data from a 2015-2016 election. Deadlines have passed and we're likely done processing it, if it existed.

In this issue we need to review the language to account for this additional circumstance as well as determine whether or not multiple versions of this No data message needs to exist. 

**Screenshot:** 
<img width="916" alt="screen shot 2018-03-30 at 3 23 43 pm" src="https://user-images.githubusercontent.com/31663028/38151107-e34e75b0-342f-11e8-9cde-e51355bca4b7.png">

While we're at it, there is also a bug in the mail to. The no data found message at https://www.fec.gov/data/committee/C00515700/?tab=raising asks users to email us if they have questions, but the email link opens up an empty mailto.

**Completion criteria:**
- [x] fix email link to nowhere
- [x] Meet with data team to better understand universe of possible reasons for data not to show
- [x] draft language
- [x] SME review
- [x] Move to design issue, if appropriate

Research: https://github.com/fecgov/fec-cms/issues/1869

**Comment by JonellaCulmer** [comment]
Related issue: https://github.com/fecgov/fec-cms/issues/1922

**Comment by llienfec** [comment]
### Research
I conducted a little bit of research on "no data" messages.  Found the following 2 helpful articles.  
https://www.nngroup.com/articles/search-no-results-serp/
http://www.uxbooth.com/articles/design-no-results-found-pages-that-get-results/

We're tackling a few different things with this message:

1. Sometimes "no data" is right.  User didn't make a mistake - there's no data to find.  
   * Past cycles - there's no data.  For example, ECs are not as common anymore, so a return of no results would actually be the correct answer and there is nothing else to find. 
   * A filer may not have sent anything in (similar to all the questions we've been getting because registered candidates don't show up in lists when their activity is $0).
   * Similar to above, a filer may not have anything due yet.
   * We haven't finished processing the data and need to help people find the raw filings (#1922)
1. The search could have been conducted incorrectly/in the wrong place
1. There's a problem on our end.

The likely errors can be a little different depending on if the user is:

- Searching the current cycle or for real-time info
- Researching past cycles for historical info

### Language draft
Here's a really simple proposed draft that sticks closely to the original - but does a pretty good job of addressing issues above.  It was getting really long and complex when I broke the message into "If you're searching the current cycle/If you're researching a past cycle..." but I can give it another try in the re-writes if that's the direction we want to go.

> We don’t have [data type] information for [time period].

>This can be because:
> - No one filed this type of activity during the time period.
> - The filing deadline hasn’t happened yet.
> - We’re still processing the data. 

> If we’re still processing the data, try looking for [raw versions of committee filings](https://www.fec.gov/data/filings/?data_type=efiling).  Raw files are only available for electronic filers.

> Think this result is a mistake? Send us more information in the feedback box or [contact us](https://www.fec.gov/contact-us/).

^ Draft is ready for massaging by Content Team @AmyKort

**Comment by AmyKort** [comment]
I like it. Do you think we should put the raw data prompt first, since that's the one that is actionable for folks?

**Comment by llienfec** [comment]
Sure.  Also added the "Have questions" to the last line to try that out.  Edited message would look like this:

> We don’t have [data type] information for [time period].

> This can be because:
> - We’re still processing the data.  Try looking for [raw versions of committee filings](https://www.fec.gov/data/filings/?data_type=efiling). Raw files are only available for electronic filers.
> - No one filed this type of activity during the time period.
> - The filing deadline hasn’t happened yet.

> Think this result is a mistake or have questions? Send us more information in the feedback box or [contact us](https://www.fec.gov/contact-us/).

**Comment by AmyKort** [comment]
Looks great!

**Comment by AmyKort** [comment]
@PaulClark2 and @jwchumley Look okay?

**Comment by llienfec** [comment]
Moving to ready b/c it's ready for final content review by PMs.

**Comment by PaulClark2** [comment]
@AmyKort looks good to me. I think I'd change `happened` to 'occurred` or `passed`

**Comment by AmyKort** [comment]
Yay! I'll close this out and make an implementation ticket.
