### ISSUE TITLE
Presidential candidate raising breakdown not consistent with adv. data table

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1949]
**What we're after:** Presidential candidate Raising overview bar chart does not reflect all candidates currently raising funds for 2020. The data is filtered by two-year period, with the latest showing as 2017-2018. There should at least be some overlap with the information presented on the Presidential candidates advanced data table. 

<img width="1342" alt="screen shot 2018-04-25 at 11 45 58 am" src="https://user-images.githubusercontent.com/31663028/39257019-6e4f3c32-487e-11e8-86b7-437fc17fc595.png">

The data included on the Presidential candidates advanced data table is from 2017-2020, which includes 2017-2018. Additionally, the presidential candidate listed on the Raising breakdown is not on the list of Presidential candidates for 2017-2020.

<img width="1476" alt="screen shot 2018-04-25 at 11 46 27 am" src="https://user-images.githubusercontent.com/31663028/39257037-77f49552-487e-11e8-80e8-44d2653ddbfd.png">

Relevant issue: #1950 and #2007 

Completion:
- [ ] Show 2020 in pulldown
- [ ] don't break anything else

**Comment by jwchumley** [comment]
What Paul said.

**Comment by JonellaCulmer** [comment]
Okay, thanks. So is this work essentially the same or similar to work done in #1945, `Add missing cycles to raising/spending breakdowns`?

**Comment by lbeaufort** [comment]
@JonellaCulmer - the change would be pretty different from my PR because if you want the cycle options to dynamically change depending on the office sought, that's a JavaScript change and the dropdowns are currently hard-coded. The [initial issue](https://github.com/fecgov/fec-cms/issues/1550) says "Include all 2 year periods even for presidential and Senate candidates" but I agree that it would be easier if it were dynamic.

**Comment by jwchumley** [comment]
@AmyKort I think tandem but whoever does the work may change that once they start digging into it.

**Comment by lbeaufort** [comment]
Combining with https://github.com/fecgov/openFEC/issues/3214
