### ISSUE TITLE
Consider language and design to explain redistricting and how it affects candidates and their data

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1959]
**What we're after:** Recent redistricting in Pennsylvania has prompted us to update our maps and explain how some candidate information is affected following the districting. In this issue, we want to draft language and design a solution that may allow our users to better understand how our data is impacted by the redistricting. Both the language and design are dependent on where this helpful information will live and so it must also be determined where this information makes the most sense.

Some language has already been drafted for our statistical release that we can use as a starting point:

> "On February 19, 2018, Pennsylvania's Supreme Court released a new congressional map for the state. As a result, some candidates subsequently amended their registration forms with the Commission to reflect their new district numbers. The presentation of candidates and their affiliated district numbers reflect their most recent candidate registration forms as of March 1, 2018, the day this table was generated."

**Comment by llienfec** [comment]
## Candidates & districts research
This research served a couple of purposes:
- Make sure that candidates are showing up in the correct districts post-redistricting and restructuring our maps, etc., to account for the new district boundaries
- Help inform where we may want to add language about redistricting on the district webpages

### Method
Used the ballot list, a 3rd party source, and the new map in staging to see which candidates are showing up for each.  This helped me figure out who should be where. Full research here:
🔒 https://docs.google.com/spreadsheets/d/1xskNmNlGkNq_WZpbfnEKVoKRwrbEg1x0VqIfu-Mskg4/edit?usp=sharing 🔒 

### Findings
- It looks like 1 candidate updated the Form 2, but is still showing up in the pre-redistricting district. This needs more research and a possible fix.
- 3 candidates aren't showing in the right district.  They appear to have multiple IDs or didn't update the Form 2 so that they show up in the right district.
- 137 candidates show up in the correct districts.

**Comment by llienfec** [comment]
Had a great pairing session with @JonellaCulmer regarding language.  Here's what we came up with.

### Needs/considerations:
- Keep language kind of close to the statistical release (above)
- Tell how we put candidates into districts (answer: by using info from their registration forms)
- Leave breadcrumbs for users/researchers making past comparisons that candidates may be in different districts than they were in the past.
- Write so that the language is correct in the future, when we're out of this cycle. (taking out "most recent," etc.)

### Proposed language:
> On February 19, 2018, Pennsylvania's Supreme Court released a new congressional map for Pennsylvania. Some candidates subsequently amended their registration forms to reflect new district numbers. Candidates are listed using information from their registration forms and may be running in different districts than in the past.

### Language placement:
@JonellaCulmer came up with 2 great places to include language regarding redistricting - on the PA map page and on the election profile pages for PA.  As of now, we can use the same language on both pages.  That may change after we get edits back.

### Next steps
- [ ] Happy to make edits.  Need :eyes: from other Content folks and approval to move forward (@AmyKort @rhoughfec )
- [ ] After we get final language, @JonellaCulmer will create mockups.

**Comment by AmyKort** [comment]
Your proposed language looks great to me (and your reasoning makes a lot of sense). Since @PaulClark2 was involved in drafting the language for our press release, maybe he can take a look too.
Thanks!

**Comment by PaulClark2** [comment]
@llienfec @AmyKort I think the proposed language looks good. I don't have any edits.

**Comment by llienfec** [comment]
@JonellaCulmer We have our approvals and can move forward to the mockup phase!

### Approved language
> On February 19, 2018, Pennsylvania's Supreme Court released a new congressional map for Pennsylvania. Some candidates subsequently amended their registration forms to reflect new district numbers. Candidates are listed using information from their registration forms and may be running in different districts than in the past.

**Comment by JonellaCulmer** [comment]
Below are the design solutions we plan to move forward on for this issue. 

We plan to include a text box with the approved language (see previous comments) in the form of an accordion to truncate the information on the election search page. Additionally, we need to include that same text on the election profiles pages as an informational message. Calling this information out here because it is more relevant to a user's discovery of why a particular candidate may not be listed.

Additionally, we'd like to move map text from the results language to below the maps image: "District maps on this page are approximate."  This text will remain regardless of the state that is selected, or if none are selected at all. 

### Designs:
**Election search page:** 
<img width="934" alt="screen shot 2018-05-18 at 3 32 13 pm" src="https://user-images.githubusercontent.com/31663028/40254325-f3100d0e-5ab0-11e8-9d48-90a2a9370871.png">

**Pennsylvania election profile pages:**
<img width="1003" alt="screen shot 2018-05-18 at 3 36 06 pm" src="https://user-images.githubusercontent.com/31663028/40254404-4aafc5a4-5ab1-11e8-9558-df03ac5f1867.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/1997
