### ISSUE TITLE
Add Edit HTML button to Wagtail 2.0

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1971]
Upgrading to Wagtail 2.0 left us with an entirely new rich text editor framework. Because of this, we need to create a new custom edit HTML button for the editor.

**Comment by johnnyporkchops** [comment]
We could possibly use https://github.com/isotoma/wagtailtinymce instead of draftail or Hallo.js. I was able to get this to work on Wagtail < 2.0, but had some problems configuring it for 2.0.1.  However, it was suggested to use this, rather than continuing use of hallo.js for 2.0 in the Wagtail Slack, support channel so it may be a viable alternative. I will continue to research.

**Comment by apburnes** [comment]
To do:

- [ ] Add  draftail customization JS to webpack transpiler
- [ ] Let Wagtail template properly inject transpiled js
- [ ] Register wagtail rich text editor hook for html editor
- [ ] Create module component to display editor as html
- [ ] Create submit action to save edited html to wagtail rich text editor

**Comment by apburnes** [comment]
This issue is being broken into two PR's.

Part I: Setup Webpack compilation and tests for React components used to customize Draftail #2190
Part II: A future PR specifically for the edit HTML component

**Comment by JonellaCulmer** [comment]
@apburnes Is this issue safe to close, or leave it open?

**Comment by apburnes** [comment]
Open. This is waiting on #2190 and a future PR

**Comment by apburnes** [comment]
Closing since Part I #2190 merged and Part II #2234 in progress.
