### ISSUE TITLE
Organize homepage banners in Wagtail

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2004]
- [x] organize homepage banners in wagtail so easier to find and publish when needed
- [x] explore archive functionality

**Comment by dorothyyeager** [comment]
The banners are organized in a separate section ("Home page banners") now in Wagtail's production site and won't clutter up the "home view" of Wagtail. They also will work when they are live or unpublished.

The next step for this issue is to find a time to chat with @johnnyporkchops and figure out if archiving older banners is desirable/doable. For now, banners not in use at the moment (or in regular rotation) have been unpublished and are saved as drafts in the new section.

**Comment by dorothyyeager** [comment]
Tested out using the date/time expiry section to archive but it did nothing. Our current method of unpublishing banners and saving them as drafts seems to work for archiving at this point.

Closing the issue as work is complete. We can open a new one if we want to set a policy about when to delete a banner altogether from Wagtail.
