### ISSUE TITLE
operations_log endpoint

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2008]
- fix aggregations (moved to https://github.com/fecgov/openFEC/issues/3217)
- coverage date box issues (moved to https://github.com/fecgov/openFEC/issues/3217)
- [x] operations log - need an endpoint

difficulty 3

**Comment by jwchumley** [comment]
We had a meeting with Priya and Helen and the DB team to determine if this should be a new endpoint or additional columns on existing endpoints. The new endpoint won. That gives us more flexibility in how we use it.

Here are the operations_log columns that I think we need in the endpoint:
sub_id,  
cand_cmte_id            CANDIDATE_COMMITTEE_ID, 
Beg_image_num           BEGINNING_IMAGE_NUMBER,
END_IMAGE_NUM           ENDING_IMAGE_NUMBER,
FORM_TP                 FORM_TYPE 
RPT_YR                  REPORT_YEAR
AMNDT_IND               AMENDMEN_INDICATOR, 
RPT_TP                  REPORT_TYPE
PASS_1_ENTRY_DT         SUMMARY_DATA_COMPLETE_DATE
PASS_1_VERIFIED_DT      VARIFICATION_DATE_SUMMARY_DATA
PASS_3_ENTRY_DONE_DT    TRANSACTION_DATA_COMPLETE_DATE
RECEIPT_DT              RECEIPT_DATE
BEGINNING_COVERAGE_DT   COVERAGE_START_DATE
ENDING_COVERAGE_DT      COVERAGE_END_DATE

I think the entire table should be replicated to the PG staging schema so if we want to add columns in the future we can do it easily.

I think in the where clause we only want to include status_num=1 because all other rows should not be on the website.

@PaulClark2 will certainly have input when he gets back.

**Comment by pkfec** [comment]
@jwchumley  the staging.operations_log table already exist in Postgres DB. I think we should create an endpoint with all the columns that exist on the opearatios_log table.And add filters like you mentioned above along with the  status_num.

**Comment by pkfec** [comment]
@jwchumley  Since this endpoint is not returning any financial info, thinking to put this new endpoint under /filers-resource/ in API documentation. Any thoughts?
<img width="1071" alt="screen shot 2018-06-04 at 11 36 26 am" src="https://user-images.githubusercontent.com/11650355/40927116-ef06e154-67eb-11e8-9f6e-23bdc631c755.png">

**Comment by AmyKort** [comment]
I believe this is a good description of what we're looking for in the "coverage date" issue:
While the “campaign financial totals” section may show that the most recent summary totals include activity through 3/31/2018, the “Individual contributions” section may not contain financial activity through that same period. Only after reports have been Pass 3 coded will that section match the data in the “campaign financial totals” section, sometimes a delay and discrepancy of several weeks. I think the inclusion of a data range field and explanatory text may be useful

**Comment by pkfec** [comment]
@AmyKort are we seeing this discrepancies in both Candidate and Committee profile pages?

**Comment by PaulClark2** [comment]
@pkfec is putting the operations log under /filers-resource/ completed? The operations log provides metadata for filings. To me, it seems to make more sense to group the operations log under /filings/. I can be convinced it should be with  /filers-resource/, especially if it's already there.

**Comment by pkfec** [comment]
@PaulClark2 My initial thought was, since this endpoint do not have any financial info, i put this under  /filer-resources/ section. During the demo meeting, @jwchumley asked me to move this to /filings/ section since its more relevant to committee filings etc. 

Right now,  this endpoint is now under /filings/ section, i put a PR and its being reviewed by devs. I wan ted @jwchumley to review this PR, cause we keep changing the searchable elements every time we do a code reivew :) .  

cc @jwchumley

**Comment by PaulClark2** [comment]
@pkfec thanks

**Comment by pkfec** [comment]
@AmyKort @PaulClark2 I would like to discuss about the first two tasks. They look like screen changes than API. I am happy to help on any API changes, but if its front-end design, i would assign this to either @patphongs or @johnnyporkchops 

Can we discuss this after stand-up today?

**Comment by jwchumley** [comment]
RAD has approved the use of the ops log in the API. That is no longer an issue.

**Comment by JonellaCulmer** [comment]
@pkfec Can this issue be closed now that the PR has been merged?

@AmyKort @jwchumley Do you think this warrants a testing ticket?

**Comment by pkfec** [comment]
Its okay to close this issue. However its upto PM's if they want to test extensively in higher env's.

**Comment by JonellaCulmer** [comment]
PR has been merged, so closing this issue.

Testing ticket here: https://github.com/fecgov/openFEC/issues/3282
