### ISSUE TITLE
Review & Prioritize Requested changes to Election pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2018]
- [ ] review & prioritize requested changes from Press/Public Records
- [ ] communicate changes to Dev group to implement

**Comment by AmyKort** [comment]
1.	Italic descriptions (Candidate Financial Totals, IEs, and ECs) should be listed under the header, not underneath the data
2.	Instead of listing the PCC in the “About This Election” section, add a column in Candidate Financial totals
3.	Take the State Election Offices from “About This Election” and place it on the left-hand side on the Election Data page. This step combined with 2 would element the “About This Election” section and thus one more click.  If the left-hand side doesn’t work, you place the State Election Offices on the state entry page underneath the map of the state.
4.	The “Individual Contributions” header is a bit misleading.  Perhaps Individual Contributions by Candidate
5.	Instead of having links to the dates, put the dates on the page.
6.	Incumbent totals for Receipts and Disbursements do not match once you click on their name. (I checked about 30, same results)
7.	When you click on the amount in IEs, you don’t the transactions that relate to the candidate that you are looking at.
8.	For some Senate incumbents, when you select any of the options under Individual Contributions, no results are returned
9.	In “About This Election”, for example Alaska At-Large, some candidates don’t have PCCs. Need some sort of standard language for that.

@JonellaCulmer  These are the comments from Public Records. Can you take a look?

**Comment by JonellaCulmer** [comment]
@AmyKort Will do. Thank you!

**Comment by AmyKort** [comment]
And this:
1.	I think it would be useful if the “Election” drop-down menu include future elections or at least an option for the 2019-2020 election cycle.

2.	I think there is value in adding a Debt column to the page that lists the names of the candidates.  Receipts, Disbursements, Cash on Hand, and Debt are the four main financial activity buckets that the public seems to be interested in.

3.	The new left-hand menu options (Candidate financial totals, Individual contributions, Independent expenditures, Communication costs, Electioneering communication) are great additions. I worry that that menu is a little washed out and will go unnoticed by website visitors. I wonder if there is a way to make it stand out more.  Perhaps a different color font?

4.	I like that there are glossary links for Independent Expenditures and Electioneering Communications. Can we also add one for Communication Costs?

5.	For future consideration, it would be wonderful if we could identify candidates who lost or withdrew from the primary election and those who are involved in the general election. Likewise, it would be especially helpful to indicate special election candidates although I know that that will be particularly challenging given the manner in which the agency permits candidates and committees to register and report activity.

6.	In the “About This Election” field, has there any thought be given to adding primary election dates?

7.	The “Individual Contributions” section provides useful information and data; however, I think we need to make an effort to ensure that web visitors are clearly informed on the time period that the data captures. For example, while the “Campaign Financial Totals” section may show that the most recent summary totals include activity through 3/31/18, the “Individual Contributions” section may not contain financial activity through that same period.  Only after reports have been Pass 3 coded will that section match the data in the “Campaign Financial Totals” section, sometimes a delay and discrepancy of several weeks. I think the inclusion of a data range field and explanatory text may be useful.

8.	The “Independent Expenditures” section, in theory, is useful. I understand that there is only so much that we can do in terms of providing accurate IE totals, but I worry that we are not presenting 24- and 48-hour report activity that have been submitted after a quarterly or monthly filing. I wonder if we could include a link to the IE search page in this section and some explanatory language.

9.	As an FYI…the Electronic Filing office is in the process of developing an email notification portal for users to sign up to receive an email alert when committees file reports with the Commission. This might be a feature that we may want to consider integrating with or at least link to from the Election Profile pages. 

10.	I think it would be helpful if there was a notation in the Source Reports field to state that there may be new filings that include financial summary information beyond the coverage dates that are presented in this field. This happens in the first two dates after a committee files a new report with the agency.

**Comment by JonellaCulmer** [comment]
@lbeaufort I'm in the process of prioritizing the work on this list for stuff we can do now/later/etc, and in looking at #6 in Amy's first comment, I was wondering if you knew if your recent work on totals might fix this as well?

**Comment by JonellaCulmer** [comment]
I've started a list to prioritize the work requested by Press/Public Records. 

https://docs.google.com/document/d/1deFYtnN1RL_fPQIt83-wFQHDpPuuXWaPQ59CrxLvTTY/edit#
