### ISSUE TITLE
Make orphan page to help respondents use pay.gov

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2031]
The ADR office offers respondents the ability to pay fines through pay.gov. To help ease the process, the office would like to be able to provide a link to a webpage explaining this service. The page will be an orphan, but it would be great if it could have a shorter, less complicated URL.

Updated to include creating OGC's page for pay.gov.

- [x] draft pages in Wagtail
- [x] provide ADR for review
- [x] ADR approves
- [x] provide to OGC for review
- [ ] OGC approves

**Comment by llienfec** [comment]
Hey @AmyKort, here's a proposed draft of the page.  I used the resource template because it has access to the contact icons.  This means it has the left-hand menu, which is why I added an "online option" section -- so that the menu would have more than one thing.  

For the page's link, we can make a redirect so that they can use something easy like www.fec.gov/payADRfine for their letters.

Let me know what you think. Happy to make edits!

![image](https://user-images.githubusercontent.com/22914750/40746202-c30d1f68-6427-11e8-8f08-22031b162c43.png)

**Comment by AmyKort** [comment]
Well that's kind of gorgeous. Are you ready to share it with ADR?

**Comment by llienfec** [comment]
Yep, it's ready to go.  I'll email you the link.

**Comment by llienfec** [comment]
Noticed that the title "online option" followed by "online option" is awkward.  Changed the second one to "online" since we know the office hasn't reviewed yet.  We can see if ADRO has a language change or they may not think the language is awkward.

### Updated screenshot:

![image](https://user-images.githubusercontent.com/22914750/40757622-68576d3c-6457-11e8-8108-6b77b949d6f6.png)

**Comment by dorothyyeager** [comment]
Looks good @llienfec. Thank you for taking care of it!

**Comment by AmyKort** [comment]
Two small changes and I think we're good to go:

1)	Change simple link to /payADR or /ADRpayment
2)	Change header to Paying Alternative Dispute Resolution Civil Penalties

**Comment by llienfec** [comment]
I changed the header to "civil penalties."  It's sentence case to match the rest of the site.  This also changes the longer page URL.

**Comment by llienfec** [comment]
I created the OGC page that's ready to review.  @AmyKort I'll email you the link shortly.  I worked with Dorothy on the redirects.  I am missing some Wagtail privileges, and as soon as John or Pat gives me access, I'll create the redirects to shorter links.

**Comment by llienfec** [comment]
Here are the shortened OGC and ADR addresses:

**Comment by llienfec** [comment]
Here are shortened addresses for ADR and OGC:
www.fec.gov/adrpayment
www.fec.gov/ogcpayment

All that's left on this issue is for Rhiannon to get OGC's edits and/or approval.  After that, we can close out.
