### ISSUE TITLE
Identify and fix broken links in FEC Timeline

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2039]
A number of the links to court cases and annual or anniversary reports are broken in the FEC timeline. In addition, there are some broken links to press releases and some links to feature on the old website that don't exist on the new website. Step 1 is to identify the broken links and the resources they were intended to go to. 

Completion criteria:
- [x] Identify broken links
- [ ] Fix broken links

**Comment by AmyKort** [comment]
I've created a document that identifies the broken links, and I'm working with SMEs to ensure the suggested fixes take users to the intended results.

**Comment by dorothyyeager** [comment]
Updated issue to add completion criteria. Amy's identified links and passed along her document. I'm working on updating the timeline now.

**Comment by dorothyyeager** [comment]
Broken links have been updated. In some cases, the only link to use was one to the classic site, so we will have to decide what to use once that site is retired.

Some suggestions were made to add photos. Since we are linking to the classic site for those places now, screencapping those pages might be a future solution to the question of what to link when the classic site is retired, assuming that the timeline is not overhauled or retired as well.

Since the links are fixed, closing this issue.
