### ISSUE TITLE
Design- Add image number to filings on committee profile pages

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2049]
**What we want:** A document image number is a key piece of data for our users. Acknowledging this and the fact that key documents, such as reports and statements of organization can be found on committee profile page, we need to add image numbers to documents on those pages as well. 

We are also in the process of adding image numbers to documents on candidate profile pages as well (#2154).

**Completion criteria:**
- [x] Mock-up filing tables with image numbers for committee profile pages, considering the placement of image numbers on the candidate profile pages

**Comment by lbeaufort** [comment]
Related to 2055?

**Comment by JonellaCulmer** [comment]
Similar to the placement of the image number column on the candidate profile page filings tab, we should plan to place the image number column in the same place. 

Regardless of the table (Regularly filed reports, 24 and 48-hour reports, Statements of organization, and Other documents) each table should place the Image number column between the Date filed and Pages columns. Please see the below image for reference. 

Please note: The mock-up does not include all current columns due to space limitations in the mock-up. The important part is the pink bar between the Date filed and Pages columns. That is where the new column should be displayed. 

<img width="934" alt="screen shot 2018-10-26 at 2 55 32 pm" src="https://user-images.githubusercontent.com/31663028/47587052-bc430800-d92f-11e8-9a75-acedbdb83ba7.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/2476
