### ISSUE TITLE
Broken open meeting link

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2082]
@fec-issues-bot commented on [Tue Jun 12 2018](https://github.com/fecgov/FEC/issues/6158)

## What were you trying to do and how can we improve it?
 The link to the meeting captions at https://www.fec.gov/updates/may-24-2018-open-meeting/ is broken (link: https://www.fec.gov/documents/568/Captions_20180524.txt).   

## General feedback?
 Too many broken links on site. 

## Details
* URL: https://www.fec.gov/updates/may-24-2018-open-meeting/ 
* User Agent: Amazon CloudFront

**Comment by dorothyyeager** [comment]
This is fixed. The problem was that the document was uploaded but the link was formatted to point to our internal server (so it returned a forbidden error). Just in case, I did upload the document again w/ a slightly different name.

In plain language, the link pointed to https://www.fec.gov/documents/568/Captions_20180524.txt but it needed to use this format:
https://www.fec.gov/resources/cms-content/documents/Captions20180524.txt

It's live and fixed now, so closing the issue.
