### ISSUE TITLE
Update or consider removing Quick Answers section of transition altogether

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2149]
Users need the most recent compliance guidance, and we need a strategy for taking care of Quick Answers on transition.  Goals: get information off of transition & one piece of content in one place.

#### Current state:
Much of Quick answers links to different pages in Updates or new H4CC.

**To do**
- [ ] Research what is in Quick Answers.  What links to new site, what is missing?   Does missing stuff need to move?  Where would it go?
- [ ] Content team decides whether to retire Quick Answers or specific sections of Quick Answers
- [ ] If stuff moves, create guide for internal users to help transition off transition.

#### Implementing
- will create another ticket for implementing whatever we decide above
- if we remove Quick Answers and need to take down its hard coded header, we can work with Pat and have this done at the same time she works on #2145.

**Comment by llienfec** [comment]
@dorothyyeager and I spent some time this morning scoping this issue and looking for which sections on the new site answer the most number of questions in the [Quick Answers](https://transition.fec.gov/ans/answers.shtml) section on transition.  This should help content team make decisions about how to proceed with this section.


Quick   answers section | Suggested redirect section | Notes
-- | -- | --
General questions | https://www.fec.gov/introduction-campaign-finance/
Disclosure questions | https://www.fec.gov/introduction-campaign-finance/ | Not finished yet?  Maybe add   Records Room hours to Contact page?
Compliance questions | https://www.fec.gov/legal-resources/
Filing questions | https://www.fec.gov/help-candidates-and-committees/ | **includes Senate paper filing, redirect sooner rather than later**
Candidate | https://www.fec.gov/help-candidates-and-committees/guides/?tab=candidates-and-their-authorized-committees | **includes Senate paper filing, redirect sooner rather than later**
PAC | https://www.fec.gov/help-candidates-and-committees/ | Sending to main page b/c PACs are split into SSF and NCs on the new site
Party | https://www.fec.gov/help-candidates-and-committees/guides/?tab=political-party-committees
Public funding | Already goes ot new public funding section | If redirected, the old page(s) is ready to come down

**Comment by dorothyyeager** [comment]
We redirected two of these (filing and candidate) in sprint 7.1 in anticipation of the new Senate filing/point of entry law. Better to redirect to pages we intend to update immediately.

**Comment by llienfec** [comment]
We made efiling-related redirects for the candidate and filing sections.  We have suggestions for redirects in each of the other categories.  We're going to do an inventory of 1) general 2) disclosure 3) compliance sections to make sure that all of that content is covered on the new site.  We also plan to make a reference guide for people who use those sections.  Tackled here in an upcoming sprint: https://github.com/fecgov/fec-cms/issues/2402

After that further research, we'll make implementation tickets.

With this research task done, we're closing this ticket.  Awesome work @dorothyyeager
