### ISSUE TITLE
Improve language for advanced data pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2293]
**What we're after:** We have a better understanding of the kinds of users who visit our advanced data pages, a primary stop for many interested in digging into specific data points. Because of this we conclude that calling that entrance into those data sets as Advanced is not an accurate representation of those who use it. And so part of this issue will be to work out an alternative name.

The other part of this ticket is to modify the language "Raising/Spending breakdown" which is a button that leads from the line charts to breakdown charts so users can see top raisers and spenders for a given election. It was discussed in the last design sync that this language might be the best way to describe what users will find on this page. 

(This ticket will be updated with research on the foundation of the existing language, if possible.)

**Completion criteria:**
- [x] Research what make a good label, esp with data
- [x] Come up with list of alternate names
- [x] Shop to content team and narrow list down to our picks
- [x] Report out

**Design:**
<img width="811" alt="screen shot 2018-08-17 at 6 00 38 pm" src="https://user-images.githubusercontent.com/31663028/44290614-8a366b00-a247-11e8-906b-59d21039e485.png">

**Comment by llienfec** [comment]
Hey @JonellaCulmer Would you mind adding a screenshot of what's behind the "raising breakdown" button?  I want to make sure that I get the language options right.  Thanks so much!

**Comment by JonellaCulmer** [comment]
Sure thing, @llienfec, here you go!
![raisingbreakdown](https://user-images.githubusercontent.com/31663028/44362855-5306ca80-a490-11e8-9526-e9592ba91008.png)

**Comment by llienfec** [comment]
I worked with @dorothyyeager and @rhoughfec to come up with new language to replace `advanced data`, which appears to be intimidating to users. Decisions were centered on the fact that it's not advanced or different data, it's just simply our data.

### New title:
`Browse data`
We took our cue from the CFD page (below).  We want to encourage people to interact with our data.  "Explore data" was also considered, and browse was our winner b/c it seemed easier and more casual.
- [ ] update on [CFD landing page](https://www.fec.gov/data/)
- [ ] update on tabbed [data pages](https://www.fec.gov/data/advanced/?tab=raising)

![image](https://user-images.githubusercontent.com/22914750/44606228-59f84a80-a7ba-11e8-8803-145a4ccee660.png)

### New button name:
`More raising charts` OR `raising infographics`
This was the harder re-name.  Here, we want people to know that you'll find different info, but on the same topic.  We'd suggest going with `more [topic] charts` because it's more straightforward and is less intimidating.  Though we love infographics!

**Comment by llienfec** [comment]
We have our two recommendations: `Browse data` and `More [topic] charts` so we're closing this issue and passing it to front end for implementation.

**Comment by JonellaCulmer** [comment]
@llienfec Should we also consider changing that card section header to "Browse full data sets"? Or something similar.

**Comment by llienfec** [comment]
@JonellaCulmer - Yep.  We were thinking simply "Browse data"

**Comment by JonellaCulmer** [comment]
In both places, got it! Thanks
