### ISSUE TITLE
Implement advanced data language changes

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2306]
**What we're after:** As part of our effort not to unintentionally exclude any of our users from exploring our data, we need to modify the section name from "Advanced data" to "Browse data"

Content team has language suggestions for the section of the website formerly known as `advanced data` at #2293.

**Completion criteria:**
- [x] Update advanced data page(s) title to "Browse data"
- [x] Update advanced data bread crumbs to "Browse data"
- [x] Update card section title on CFD landing page from "Browse full advanced data sets" to "Browse data"
- [ ] Remove this issue as a blocker from https://github.com/fecgov/fec-cms/issues/2538 and put #2538 in the "New Issues" pipeline

**Comment by llienfec** [comment]
Language suggestion for URL if we can make the change:
`/data/browse-data`

**Comment by lbeaufort** [comment]
@AmyKort @llienfec - I believe the URL change and redirect will add a lot more time to this issue because of the `?` in the URL. Would it be ok to split the redirect work out into a separate ticket so it doesn't block the language changes?

cc: @johnnyporkchops correct me if I'm wrong about the effort level, thanks!

**Comment by AmyKort** [comment]
Sounds good to me @lbeaufort . Thanks!

**Comment by lbeaufort** [comment]
URL/redirect moved to https://github.com/fecgov/fec-cms/issues/2538
