### ISSUE TITLE
Research: Take stock of where reporting dates live

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2328]
**User story:** As a treasurer, I want to find accurate and relevant reporting dates information, so that I can meet all my reporting obligations. 

**What we're after:** As part of our work to make data improvements to our compliance dates site wide, we need to first take stock of all the instances where compliance/reporting dates are implemented currently and where we can see a benefit of their inclusion. 

This issue would require the content team to take that first step and compile this list before we can move forward with goal-setting or identifying needs. 

**Completion criteria:**
- [x] Identify areas where compliance dates are currently employed
- [x] Identify some preliminary locations where compliance dates may be needed

**Comment by dorothyyeager** [comment]
Have started a spreadsheet for this at https://docs.google.com/spreadsheets/d/10VE8MByrDcj6wvkZ50TuVpJcp3a7XuV-9ya6HeXy3so/edit?usp=sharing.

**Comment by dorothyyeager** [comment]
Had a key Info Division staff person who regularly works on these dates look over the spreadsheet and have incorporated their comments. The spreadsheet has one section meeting the first box, labeled "Pages with due dates included" and one section meeting the second box, labeled "Pages with compliance info but no due dates." 

Closing the issue since we've done the research, but am available to answer any follow-up questions on it!
