### ISSUE TITLE
Create Admin Term/DSP page

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2482]
We need to put Administrative Terminations (ATs) and Debt Settlement Plans (DSPs) from the 2016 election cycle to present on the website so that committees, the public, and researchers can find information about these decisions.  This project supports work from RAD, CAT, and Admin Law.

**Pre-work:**
- OGC will compile redacted documents.
- RAD will create the suggested chart in Word or Excel.
- Both groups will approve any explanatory or intro language on the page.

**To do:**
- [x] RAD/OGC complete preparation of documents to be published.
- [x] Decide on a template for the page.
- [x] Decide where to host the the page. 
- [x] Groom implementation ticket based on initial work here.

**Future work**
Implementation ticket: #3213

**Comment by llienfec** [comment]
For the charts, we suggest using the E&J format:
- Use the resource template
- Section headings should be `Administrative Terminations` and `Debt Settlement Plans`
- When coding the charts, use the table class `simple-table`, be sure to use percents for column widths

**Comment by bmathesonFEC** [comment]
Picking up where Lauren left off with this ticket. I modified the completion criteria to make this an "decisions" ticket while RAD/OGC finalize the documents. Created an implementation ticket to execute these decisions once materials are ready.

**Comment by bmathesonFEC** [comment]
**Re: page type:**

**Suggestion 1**: Use the E&J pages as a template. (These are  kind of our template for "legal resource archives.") https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-2010-2019-ejs/#2019

**Suggestion 2**: Use the Webinar materials resource page:
https://fec-prod-proxy.app.cloud.gov/help-candidates-and-committees/trainings/webinar-materials/

**Comment by bmathesonFEC** [comment]
### Re: page location ###

Suggestion:** Page should live at [Legal resources > Policy & other guidance](https://transition.fec.gov/law/policy.shtml#legalconsideration) as one of the subcategories of the page:

- Requests for Comment
- Proposals Under Consideration
- Policy Statements
- Requests for Legal Consideration by Commission
- Interpretive Rules
- Rules of Agency Organization Procedure, or Practice
- **_Administrative Termination and Debt Settlement Documents_**
- Other Guidance

Below, in the _Administrative Termination and Debt Settlement Documents_ section of the page, provide the following:
- link to the new page which will have the table of documents 
- link to the policy statement PDF: https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2019-10_07292019.pdf

**Comment by bmathesonFEC** [comment]
### Re: page type

Decided on a resource page with two categories on the left for each of the two lists, AT and DSP, within each list there will be specific committee maters using a Document List to display the docs for download. Considering the documents listed

![image](https://user-images.githubusercontent.com/33758291/66328297-637b3e00-e8fa-11e9-9681-8e022d7709da.png)

**Comment by bmathesonFEC** [comment]
### Re: page location:

Summarizing suggestions for locations:
- [Policy and other guidance](https://transition.fec.gov/law/policy.shtml#legalconsideration)
- [Documents on Enforcement & Compliance Practices](https://transition.fec.gov/law/procedural_materials.shtml
)
- Data section.

This content is an unnatural fit for pages on the current site because each document references a specific committee, but we're not going to list these documents on the committee's page -- for now --  in the same way we don't link to a closed MUR from the committee page.  Alternatively, _Policy and Other Guidance_ **and** _Documents on Enforcement Compliance Practices_ are both home to policy documents NOT the documents produced by those policies.

A possible content analogy is the ["Program for Requesting Consideration of Legal Questions by the Commission"](https://transition.fec.gov/law/policy.shtml#legalconsideration) on the Policy and Other Guidance page. This subheading of the Policy and Other Guidance page includes a link to ["Browse Previous Requests"](https://transition.fec.gov/law/legalconsideration.shtml) That page links to a separate transition page with a table showing each request that has been made under the policy.

@AmyKort @dorothyyeager @JonellaCulmer  I propose that we move forward with an approach that puts this content on the Policy and Other Guidance page for now based on my perception that this content is most similar to the Legal Consideration section. Two positives about this approach:
- we have a 10.6 ticket (#3220) queued up to take the Policy and Other Guidance page and convert it to a resource page before taking it off of transition. I can add a note to that ticket that we should reassess whether AT/DSP should be housed on that new resources page at that time.
- this is a completely new page so we don't have a materials that reference this page, nor do we have a chain of redirects to put into place if we decide to move it somewhere else on the site.

I don't want to kick the can down the road if you think this content absolutely doesn't fit on Policy and Other Guidance. Let me know what you think.

**Comment by dorothyyeager** [comment]
I'm between the policy page, for the reasons @bmathesonFEC mentions, and the data page, because this new page relates to a filing by a candidate.

Another idea that just occurred to me - could this page work as a child page of the H4CC page on terminating a committee? That page explains the administrative termination process. (A content analogy could be the coordinated party expenditure pages, where we have one page that explains the law and one page that has the limits for the year.)

https://www.fec.gov/help-candidates-and-committees/terminating-a-committee/

**Comment by bmathesonFEC** [comment]
@dorothyyeager I'm not a fan of putting this under H4CC because there are only a small subset of ATs and DSPs that get referred to the Commission. Most are completed uneventfully when they fall within thresholds specified in RAD Procedures. I think it would be misleading to visitors of the site if they reviewed one of these memorandums.

Re: data page. I agree that it would be ideal to go a committee's page and see their AT or DSP memo to find out why they're terminated, but I think that's a huge lift relative to the expected traffic to see these documents and our competing priorities.

@AmyKort I'm looking over the [Documents for Enforcement and Compliance Practices](https://transition.fec.gov/law/procedural_materials.shtml) page and it starts out:

> Following oversight hearings on November 3, 2011 before the Subcommittee on Elections of the House of Representatives Committee on House Administration, the Commission released a number of documents relating to the enforcement and compliance processes.The Commission has worked to further transparency and is pleased to advance this agency goal by making these internal documents available to the public. The documents, which can be found at the links below, fall into three categories:

Since AT / DSP referral docs aren't part of the 2011 oversight subcommittee release, I suggest that we don't put AT/DSP on that page, unless we want to reword the intro altogether. 

I'm still team POG (I'm going to use this for Policy and Other Guidance from now on).

**Comment by AmyKort** [comment]
How about we make it a subhead under "Other Guidance," rather than it's own heading on the Policy page?

**Comment by dorothyyeager** [comment]
That's good to know, @bmathesonFEC so I agree, H4CC or Data is not a good fit.

**Comment by AmyKort** [comment]
. . .  because (and I know I am splitting hairs) it is not a policy statement or an interpretive rule. But it is a form of other guidance.

**Comment by bmathesonFEC** [comment]
**Final location on the site:**
[Policy Statements, Interpretive Rules and Other Guidance](https://transition.fec.gov/law/policy.shtml)

- Requests for Comment
- Proposals Under Consideration
- Policy Statements
   -Requests for Legal Consideration by Commission
- Interpretive Rules
- Rules of Agency Organization Procedure, or Practice
- Other Guidance
   -**Administrative Termination and Debt Settlement Documents**

I'll make a note in the 10.6 Policy and Other Guidance that we should re-assess this as an appropriate home for this content.
