### ISSUE TITLE
Begin work on the E&J chronological index tables

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2568]
**User story**
As an internal stakeholder or outside legal consultant, I need to see the explanation and justification for Commission regulations to do proper legal analysis of them.

**Background:** In previous issues, we worked on the citation index. The other main index for the E&Js is the chronological listing of them. (Currently these pages are linked at https://transition.fec.gov/law/cfr/ej_toc.shtml.) This process will work much like the citation index. We'll need to create the tables in word, update the links, turn into HTML blocks and then populate a page that is set up in Wagtail.

**Completion criteria:**
- [x] Create word versions of the chronological index tables

**Future work:**
- [ ] Update the links in those tables - Dorothy
- [ ] Use our table to html conversion process to make the html blocks - Brad
- [ ] Set up the page(s) for the chronological index - Brad or Dorothy
- [ ] Insert the new html blocks in a resource page that has been set up for this. -Brad

**Comment by bmathesonFEC** [comment]
@dorothyyeager I made the word versions of the tables. I'll be able to convert them back to HTML blocks once we update the links. Do you care if I update the ticket to assign that to me instead of "Info Div. Specialist"? I'm not sure who that is, but the Word->HTML is just the reverse process of the HTML->Word that I did this morning, nbd.

**Comment by patphongs** [comment]
Future work has been defined and new ticket for 8.2 has been created. Closing in favor #2617
