### ISSUE TITLE
Design studio for raising data visually

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2636]
**User story:**
As a design and development team, we need to have a design studio to talk about approaches to displaying raising data in a way that is meaningful for our users.

**Completion criteria:**
- [x] Need to schedule a design studio
- [x] Goal is to determine what makes sense to display raising data in a visual format
- [x] We should discuss technical impacts of design decisions made during this meeting

**Comment by AmyKort** [comment]
Meeting is scheduled for Thursday.

**Comment by JonellaCulmer** [comment]
From this discussion, we have opted to improve upon an existing data visualization and improve navigation to it from our homepage. Additionally, we plan to continue with an earlier idea to add the election search to the homepage. This is our MVP.

Some work on moving the election search to the homepage has been completed here: https://github.com/fecgov/fec-cms/issues/2541, but this needs to be updated based on yesterday's discussion. 

Additionally, some data work needs to be completed in order to make those improvements to the existing data visualization (Who's raising/spending the most bar charts), including: providing full cycle totals, and filter to include only active candidates. Work on updating the charts interactions are happening here: https://github.com/fecgov/fec-cms/issues/2616

The charts are found here: https://www.fec.gov/data/raising-bythenumbers/ and here: https://www.fec.gov/data/spending-bythenumbers/

Materials from yesterday's discussion:
[Election data research presentation](https://docs.google.com/presentation/d/1qWmSxN0JvkdvaOy2RGr2bpvtq_lNseNEzqnvGZWx0Sk/edit#slide=id.g4f5c58b6fa_0_1266)
[Design studio notes](https://docs.google.com/document/d/18F_H--7oY3fAlfqNxWRvsbGyh8SNY_OtPg21gBPxMYw/edit#)
