### ISSUE TITLE
Update EQS, SERS, and SAOS links to HTTPS

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2661]
For security compliance, the below listed URLs will be updated to using strictly https in the near future.

1. http://eqs.fec.gov/eqs/searcheqs
2. http://sers.fec.gov/fosers/
3. http://saos.fec.gov/saos/searchao

**Completion criteria:**
- [ ] Coordinate with the PM for that application to see when the implementation will be going live so that we can push out our changes the same time
- [x] Confirm with content team about content linking to the above applications
- [ ] Confirm with legal application team to set up a redirect from http to https. Without this, a lot of content page links will break.
- [x] Make banner code changes to point to https

**Comment by dorothyyeager** [comment]
I spoke with @patphongs yesterday and related that there are a TON of content pages that link to SERS since it's where things like rulemaking federal register notices are linked. In particular, the E&J pages contain a ton of links to sers pages - enough that I think we should hold off on future E&J work until this work is complete. (cc'ing @AmyKort @bmathesonFEC on that.)

There are a lot of older pages that will contain links to SAOS, such as pre-2017 Record articles, press releases, etc. 

While not used a lot by the Information Division, I believe there are a lot of agenda documents and press releases that contain links to EQS.

Finally the intranet site used by FEC staff to do legal research (InfoWeb) contains a bazillion links to both SERS and SAOS, and a few for EQS. 

All that considered, I definitely think we'll need that redirect from http: to https:. The volume of pages affected is simply too great to not have it.

**Comment by patphongs** [comment]
Moving this to 8.2 until we get a firm timeline as to when this change will happen
