### ISSUE TITLE
Table names in statistical releases are not appearing correctly

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2746]
When using custom table in the statistical release, the word "custom_table" appears instead of the name of the table.

For example, when viewing https://www.fec.gov/updates/statistical-summary-24-month-campaign-activity-2017-2018-cycle/, you see this instead of a header that says the actual name of the table:

![image](https://user-images.githubusercontent.com/24437369/54452748-44357d00-472c-11e9-8c34-d0823578a677.png)

**Comment by johnnyporkchops** [comment]
It looks like the template for the custom-table block got moved to the bottom of `block.py`, so there is currently no template associated with it. Instead Wagtail just renders its default table-block and streamfield template. Which is why the title above the table block does not render as a headline style.

I think this also means that all statistical press releases that were previously created, would have had this incorrect rendering until we fix this.  

Also, since this template was put under the `example-forms` block at the bottom of `blocks.py`,  example forms blocks would not show the image and some or all of the content one would put into that in the Wagtail editor.

- [ ] We need to move the `custom-table meta section` from the end of `blocks.py` to the custom-table block section and also make sure anything that the content team has created using that block since, looks OK to them.


- [ ] Also, we might want to change the `overflow-x:scroll` on custom-table in  `_table-styles.scss` to `overflow-x:auto` and test it in smaller screens. Overflow-x:scroll was leaving an empty scrollbar on the bottom regardless of width, I think.
