### ISSUE TITLE
Add MUR 2186 to MUR search

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2757]
We need to add MUR 2186 to the MUR search on the [classic](https://classic.fec.gov/MUR/) website and [main](https://www.fec.gov/data/legal/search/enforcement/) websites.

Ask @patphongs for the MUR file when ready for this ticket.

**Comment by pkfec** [comment]
Archived MUR's 2186 and 1412 are loaded on to classic(classic.fec.gov) site. Gashaw deployed the latest MUR.war file on to classic production servers. 

I am working on loading these two MUR on to main website(www.fec.gov). Trying to load the archived mur's to `dev` space . After the murs are successfully loaded, i will create a  new archived murs snapshot
and load it into` stage` and  `prod` spaces

**Comment by pkfec** [comment]
Attempted to load  archived murs 2186 and 1412 on `dev` space. The task that loads the murs failed  due to subject(s) not defined(unavailable) on these two murs.  After talking to @PaulClark2, i have updated the load script to handle archived murs without subject(s) by setting the subject text to `unavailable` and reloaded the murs in `dev` space successfully.  

On production,  load script changes were deployed as `hotfix` on 03/28. archived murs were loaded to `prod` space successfully.

ToDo# i need to load these two murs on `stage` space.

**Comment by pkfec** [comment]
Finished loading the two archived murs on `stage` space. Hence closing this issue.
