### ISSUE TITLE
Wagtail: Custom page template unable to toggle between red and blue breadcrumb style

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2762]
**What we're after:** Unified color scheme of blue navigation breadcrumbs bar for all legal resource and campaign finance data pages.

**Background**
In working on the E&Js, we discovered that pages created with the custom page template within legal resources are displaying the red breadcrumbs bar normally used in H4CC. We need them to have the blue breadcrumbs bar. The same problem is occurring with Wagtail pages using custom page template in the Data section.

**Example:** 
![image](https://user-images.githubusercontent.com/24437369/54841573-f11c7680-4ca5-11e9-9a7f-d776f17d533f.png)

As a workaround, we've inserted an html block style tag on these particular pages, but we need to make sure future pages using the custom template are able to go blue if we need them to. 

**To do:**
- [x] First, try to identify what's causing the wrong color to show. If we cannot identify, move to the next item. --->
- [x] Add the toggle between red and blue breadcrumb style to the promote tab of the custom page template that the resource page template currently has. Here's a screencap from a resource page:

![image](https://user-images.githubusercontent.com/24437369/54841739-65571a00-4ca6-11e9-8d33-27ebf4ed34ae.png)

- [x] Make a ticket to remove the workaround html block hack from these pages after the fix is deployed.
/legal-resources/regulations/explanations-and-justifications/chronological-index-e-j-s/
/legal-resources/regulations/information-for-public-hearing-june-27-28-2018/
/legal-resources/regulations/pending-rulemaking-matters-comment/
/legal-resources/regulations/sers-supplemental-information/
/campaign-finance-data/candidate-summary-file-description/
/campaign-finance-data/committee-summary-file-description/
/campaign-finance-data/committee-master-file-description/
/campaign-finance-data/communication-costs-file-description/
/campaign-finance-data/contributions-committees-candidates-file-description/
/campaign-finance-data/house-and-senate-map-help/
/campaign-finance-data/independent-expenditures-file-description/
/campaign-finance-data/party-code-descriptions/
/campaign-finance-data/presidential-campaign-finance-summaries/
/campaign-finance-data/presidential-map-help/

**Comment by dorothyyeager** [comment]
Just a note - this is affecting pages being created in the Data section for #2770 and #2771 as well as some custom pages created in that section in past PIs to explain various data sets.

For #2770 and #2771 , we'll use the html workaround for now, but we'll need to add them to the list in this issue once published. @kathycarothers

**Comment by johnnyporkchops** [comment]
**Currently:**
All `ResourcePages` default to blue unless otherwise specified as red in the promote tab.
`CusromPage, CollectionPage, RecordPage etc` default to red and have no option to specify a color.

**With this PR:**
I think it might be better to control the color of the breadcrumbs by parent-page type than by using the checkbox--although we can leave it on the resource page since it is already in use. This is how I set it up so far for this PR
1) All pages with  `legal-resources` or `campaign-finance-data` as a parent will be blue
2) All other pages **NOT** in  `legal-resources` or `campaign-finance-data` are red --unless it is a resource page that is specified as blue.

**@dorothyyeager ,  @kathycarothers Questions:**
- Are pages with parent of `introduction-campaign-finance` supposed to be blue? They are currently all blue because they are all resource pages.
- Do you want ti be able to use other page types here-- I can add that to the list in number 1 above so that all page types here would also be blue.
- How does one navigate the the `introduction-campaign-finance` section, I could not find my way there from the homepage without knowing the URL, I know you have mentioned this before, but cannot remember what you said.

**Comment by dorothyyeager** [comment]
For @johnnyporkchops Here are the answers to your questions:

1) introduction-campaign-finance is supposed to be blue. 
2) Yes, please go ahead and add introduction-campaign-finance to your PR. We'd want the option to create a custom page in this section, so it would need to be blue.
3) To access introduction-campaign-finance from the home page, you'd click one of these three links (which are just below the "compare candidates" map):
![image](https://user-images.githubusercontent.com/24437369/55878606-c5850180-5b6a-11e9-8842-2d9a5bed2feb.png)

Thank you for working on this!

**Comment by dorothyyeager** [comment]
@johnnyporkchops and I agreed on an even better fix beyond the toggle that will conditional statement to breadcrumbs.html that forces breadcrumb style based on parent-page type. Detail is at https://github.com/fecgov/fec-cms/pull/2818.

I've put in a follow-up issue to tackle after 8.4 is deployed on 4/23 that will clean up the Wagtail pages and remove a hack that won't be needed any more. That is at #2826 .
