### ISSUE TITLE
Handle over rate limit message for downloads

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2842]
https://github.com/fecgov/openFEC/issues/3651

API message for over rate limit is code 429. Test with more than one request with this key: 
`curl -I "https://api.open.fec.gov/v1/candidate/P80001571/totals/?api_key=8Bhfz2eaOM0KVmfulpzCUgLnTeYn60oJQDZp4tzy"`

```
HTTP/1.1 429 Too Many Requests
Server: openresty
Date: Wed, 17 Apr 2019 15:04:14 GMT
Content-Type: application/json
Connection: keep-alive
X-RateLimit-Limit: 1
X-RateLimit-Remaining: 0
Access-Control-Allow-Origin: *
X-Cache: MISS
Strict-Transport-Security: max-age=31536000; preload
```

**Comment by lbeaufort** [comment]
@patphongs here's what I have so far: https://github.com/fecgov/fec-cms/pull/2852

The issue I'm having is that I can get the 429 message to show up once, but not subsequent times:

![Screen Shot 2019-04-22 at 3.45.04 PM.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/36aad0b4-fe6e-45fb-b445-5939835f437c)

**Comment by patphongs** [comment]
Sorry I didn't get to this, will need to move over to 9.1

**Comment by patphongs** [comment]
@lbeaufort Upon further investigation of this ticket, there's probably no way to be able to differentiate between errors happening through the download AJAX calls. See below my detailed explanation below.

When a download request is made, there are 2 different request methods being used: `OPTIONS` and `POST`. OPTIONS is sent first, this is a preflight request that is sent first to the API domain in order to determine if the actual request is ok to send. So if a success is received, the `POST` request will follow immediately afterwards. It will continue to call these two methods until `Status: complete` response is received. See images below that illustrate this.

<img width="544" alt="Screen Shot 2019-05-30 at 10 32 06 AM" src="https://user-images.githubusercontent.com/12799132/58640168-7d5ea180-82c6-11e9-8838-7b59bbf05021.png">
<img width="547" alt="Screen Shot 2019-05-30 at 10 07 03 AM" src="https://user-images.githubusercontent.com/12799132/58640175-82235580-82c6-11e9-98fb-0556a3a126eb.png">
<img width="248" alt="Screen Shot 2019-05-30 at 10 32 42 AM" src="https://user-images.githubusercontent.com/12799132/58640211-96ffe900-82c6-11e9-8bac-196c3c7959b4.png">
<img width="535" alt="Screen Shot 2019-05-30 at 10 32 27 AM" src="https://user-images.githubusercontent.com/12799132/58640161-7768c080-82c6-11e9-8801-30678b97b88c.png">

The problem happens when the 429 error occurs. Initially, you may get this to occur in a POST method on initial error, but this is unfortunately not consistent. Each follow-up request that occurs will happen in an OPTIONS request method. When the error happens immediately in this type of call, there's no follow-up POST method that happens, it immediately dies there. The OPTIONS method does not have a response, so we can only hook into what is provided in the xhr, which now we are using `statusText: error`, there is no specific status code of 429 or 504 to hook into. Which does not allow us flexibility when trying to differentiate between error messages.

<img width="1502" alt="Screen Shot 2019-05-30 at 11 01 12 AM" src="https://user-images.githubusercontent.com/12799132/58641949-438f9a00-82ca-11e9-8fe2-14c33f636ee6.png">
<img width="560" alt="Screen Shot 2019-05-30 at 10 04 28 AM" src="https://user-images.githubusercontent.com/12799132/58638252-59995c80-82c2-11e9-8fa0-a067579b82ce.png">

## General solution
I propose to make an all encompassing error message to indicate the reasons why an error may have occurred, including messaging about over rate limit. This will let the user know that over rate limit is now something to look out for as well as other server errors. 

@dorothyyeager @AmyKort Can you help take a look at what I've drafted below for the solution? Basically you can get an error that happens because of a random server error or an over rate limit for downloads. 

"Sorry, you have either exceeded your maximum downloads for the hour or encountered a server error. Please try again later."

**Comment by dorothyyeager** [comment]
That seems clear to me! I think it works @patphongs
