### ISSUE TITLE
[HIGH] CRLF injection -- need a fix by May 24, 2019

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#2862]
**CRLF injection**
Vulnerable module: urllib3
Introduced through: wagtail@2.2.1, slacker@0.8.6 and others 

**Detailed paths**
* Introduced through: project@0.0.0 › wagtail@2.2.1 › requests@2.20.1 › urllib3@1.24.2
* Introduced through: project@0.0.0 › slacker@0.8.6 › requests@2.20.1 › urllib3@1.24.2
* Introduced through: project@0.0.0 › requests-mock@1.3.0 › requests@2.20.1 › urllib3@1.24.2
* Introduced through: project@0.0.0 › github3.py@0.9.6 › requests@2.20.1 › urllib3@1.24.2
* Introduced through: project@0.0.0 › cg-django-uaa@1.3.0 › requests@2.20.1 › urllib3@1.24.2
* Introduced through: project@0.0.0 › cachecontrol@0.11.5 › requests@2.20.1 › urllib3@1.24.2
* Introduced through: project@0.0.0 › requests@2.20.1 › urllib3@1.24.2

**Overview**
urllib3 is an HTTP library with thread-safe connection pooling, file post, and more.

Affected versions of this package are vulnerable to CRLF injection. Attacker who has the control of the requesting address parameter could manipulate an HTTP header and attack an internal service.

**Remediation**
A fix was pushed into the master branch but not yet published.

**Comment by rfultz** [comment]
The branch is closed but there's still discussion going on at [urllib3 #1553](https://github.com/urllib3/urllib3/issues/1553) and [requests #5065](https://github.com/kennethreitz/requests/issues/5065). Will continue to monitor the conversation.

**Comment by pkfec** [comment]
**Reopening this issue :**

we tried updating the `requests` python to `v1.21.0` which downloads  the dependency package`urllib3 v1.24.3`. But that dosent seems fix the issue here.

There are other packages that needs to be upgraded as well :

1. Introduced through: project@0.0.0 › wagtail@2.2.1 › requests@2.21.0 › urllib3@1.24.3
2. Introduced through: project@0.0.0 › slacker@0.8.6 › requests@2.21.0 › urllib3@1.24.3
3. Introduced through: project@0.0.0 › requests-mock@1.3.0 › requests@2.21.0 › urllib3@1.24.3
4. Introduced through: project@0.0.0 › github3.py@0.9.6 › requests@2.21.0 › urllib3@1.24.3
5. Introduced through: project@0.0.0 › cg-django-uaa@1.3.0 › requests@2.21.0 › urllib3@1.24.3
6. Introduced through: project@0.0.0 › cachecontrol@0.11.5 › requests@2.21.0 › urllib3@1.24.3
7. **Introduced through: project@0.0.0 › requests@2.21.0 › urllib3@1.24.3** (This is already taken care of) 

 More info on snyk here:
  https://app.snyk.io/org/fecgov/project/ff0dca01-794e-4c1c-bf1f-0c0f8932fadd

**Comment by rfultz** [comment]
@pkfec this looks like it's been resolved on its own. ?

**Comment by pkfec** [comment]
Yes @rfultz. Closing this issue.
