### ISSUE TITLE
Create a template to be used for content team issues

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2887]
**What we're after**
Streamlining our issue-making!

@rfultz made some awesome templates for features and for bugs at https://github.com/fecgov/fec-cms/issues/new/choose

Wondering if we can get one for content issues, which have their own rhythm and wording.

Some examples to look at in order to get a sense of our workflow. Generally we have a ticket for drafting, a ticket for circulation and a ticket for publishing and related tasks to publishing. 

- All the ones tagged "presidential guidance"
- Various ones on reporting examples: https://github.com/fecgov/fec-cms/issues?q=is%3Aissue+reporting+examples+is%3Aclosed
- All the ones tagged "E&Js"
- For our redirect work flow, you could look at https://github.com/fecgov/fec-cms/issues/2776 and https://github.com/fecgov/fec-cms/issues/2800

Happy to pair on this or answer questions.

**Comment by patphongs** [comment]
Thanks @dorothyyeager! You've given me a lot of awesome ideas! I'd like to see if we can streamline this as something that we can use across the team. Would you say that content generally has Task issues? Because I could see task issues that we all make frequently when grooming. To me, a task is something actionable that includes criteria that need to happen to complete an issue. What do you think about this kind of templating below?

### Summary
**What we're after:**
_Briefly describe the goal or user story for this issue. Be sure to add any dependencies down below if there are any._

### Related issues

_List any relevant related issue(s)_
- #[issue_number]
- #[issue_number]

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [ ] First item to complete
- [ ] Second item to complete
- [ ] etc

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by dorothyyeager** [comment]
This works for me and we totally use a task structure.  I could see us varying it slightly for things like a redirect ticket, but overall this is our usual pattern. The only thing I would add is under completion criteria -  add one - [ ]  that says "Follow up tasks (add to redirect list, open front end ticket for implementation, etc.) We're trying to get better about tracking those. Thank you @patphongs !! I like where we're going!

**Comment by rfultz** [comment]
Since these templates will be available for _anyone_ who submits a ticket, should we indicate if some things are for internal use only? (e.g. someone who doesn't work on the site has probably completed their contribution by pointing out the error/fix/feature without having to worry about internal processes)

I wonder if there's a way to offer different templates based on whether someone is part of the project (i.e., fecgov).

**Comment by patphongs** [comment]
> The only thing I would add is under completion criteria - add one - [ ] that says "Add follow up tasks"

@dorothyyeager Thanks! I've added your suggestion to my original comment above.

> Since these templates will be available for _anyone_ who submits a ticket, should we indicate if some things are for internal use only?

@rfultz I feel like we haven't received a lot of public comments within our individual repos (fec-cms, openfec, etc.). We generally get them from our [general FEC repo](https://github.com/fecgov/fec/issues), in which we get feedback. @AmyKort @dorothyyeager What do you think? Should we add some sort of indication about certain types of issue templates being for internal use only?

**Comment by dorothyyeager** [comment]
If the templates pop up in our general FEC repo, then I'd say yes we should add that. But if they are only used in our individual repos, almost never see non-FEC people opening them there, so not sure we really need it.
