### ISSUE TITLE
IE "filter this data" button not respecting committee ID or candidate ID

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2956]
Found while testing #2955 

### Expected Behavior
Candidate and Committe profile pages IE datatable "filter this data" button _should_ go to  the IE transactions associated with that candidate/committee.

### Actual Behavior
Cand/cmte profile pages IE datatable "filter this data" button doesn't filter by candidate/committee ID when clicking through the candidate/committee profile pages

### How to Reproduce

https://www.fec.gov/data/candidate/P80001571/?tab=other-spending
or
https://www.fec.gov/data/committee/C00571703/?tab=spending
This chart shows quarterly report data (see explanatory text at the bottom)

1. Look at the link for "Filter this data" - note how it has `committee_id=` or `candidate_id=`
2. Click the link
3. Datatable doesn't filter by passed through committee or candidate ID

**Comment by johnnyporkchops** [comment]
It looks like the Sizzle selector engine fails on parsing the long id that gets appended to `input id ="min_date...."` and `input id ="max_date...."`. 

Switching this from a `jQuery CSS selector` to vanilla `getElementByID()` seems to get us almost there, but there is still a console error that persists. 

I pushed this change to the original PRs branch: #2955.

I wonder when this bug was introduced. It doesn't look like it was with the new jQuery upgrade, but will research further to determine for sure.
