### ISSUE TITLE
Decide on / design new social media image 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2972]
We need to stop calling the website new on social media. We need a replacement for the current image. ![2F495847-BDAC-4D7F-93E8-E51A61D91377.jpeg](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/606c84ec-6958-456d-a4b7-dfc626379cb5)

- [x] Design new image that no longer says "the new". Consider whether we want different images for different pages.
- [x] Create new image (see https://github.com/18F/fec-style/issues/670 for how we did it before)
- [ ] Remove this issue as a blocker to this implementation issue https://github.com/fecgov/fec-cms/issues/1635

**Comment by JonellaCulmer** [comment]
Had a great conversation with Jim about what we can do for these images. We have a few things we're going to explore. One of them being whether or not we can automate these images, or if we can create images and add them to specific pages so that when a link is shared it overrides the generic image. Do you have any thoughts you can share on this, @johnnyporkchops? 

Additionally, we plan to update the generic image to, at the very least, remove "the new".

**Comment by JonellaCulmer** [comment]
It seems that the original images that were created, to be used on social media are based on the page template type. These seem to be working, if inconsistently. So there may be some front-end work to better understand how/when images are used. Seem to be working "now" for H4CC pages, but not for Legal. 

To keep things easy and introduce some new images to break up the monotony of the same image repeated over and over, we can just create new images based on pages we frequently share on twitter. These include: 
- AO - record page 
- Weekly digest - digest page
- Open meeting - meeting page
- Press release - press release page

Need to take some inventory to make sure we're accounting for all the uses of these specific pages types so we don't over-design or exclude anything.

**Comment by AmyKort** [comment]
@JonellaCulmer Thanks for all of your work on this! Are you thinking there will be a more generic option for other pages, like pages out of the legal resources section?

**Comment by JonellaCulmer** [comment]
@AmyKort To recap our chat, we will still have the generic image, updated, for those pages that we can't account for my a specific page type. At least not in this iteration.

**Comment by JonellaCulmer** [comment]
Moving this issue to the Innovation sprint, as we are waiting until that time (availability is next week) to take new photos for this.

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 ,  @jjonesFEC and I have come up with a new series of images that we'll use for social media. Since the images are dependent on the page template, we have designed them so that they can be used based on the page template, and not necessarily that specific page. The link to that page should take care of the rest. 

**Record page template**
Pages included: Advisory opinion

![Tweet_AO](https://user-images.githubusercontent.com/31663028/63110497-9be54800-bf59-11e9-862e-5edfd4c45cb8.png)

**Digest page template**
Pages included: Weekly digest

![Tweet_WD](https://user-images.githubusercontent.com/31663028/63110527-a869a080-bf59-11e9-818d-e2df1b5aed6e.png)

**Meeting page template**
Pages included: Open meeting, Public hearing, Executive session

![Tweet_OS](https://user-images.githubusercontent.com/31663028/63110537-aef81800-bf59-11e9-93f4-b328fd02be78.png)

**Press release page template**
Pages included: Press release

![Tweet_PR](https://user-images.githubusercontent.com/31663028/63110547-b3bccc00-bf59-11e9-9b6b-fd3ead8a82ae.png)

**Updated generic image**
Pages included: All other page templates not covered

![New Twitter Graphic 01](https://user-images.githubusercontent.com/31663028/63110564-b9b2ad00-bf59-11e9-993e-18e76a47ee28.jpg)

**Comment by JonellaCulmer** [comment]
The images above are in addition to the existing images already in use for other page templates that are specific to the H4CC, Legal resources and Data pages. 

![original-help-2-1](https://user-images.githubusercontent.com/31663028/63110723-131adc00-bf5a-11e9-9a12-41b2a5591051.png)
![original-legal-2-1](https://user-images.githubusercontent.com/31663028/63110724-131adc00-bf5a-11e9-808e-359186c505b9.png)
![original-data-2-1](https://user-images.githubusercontent.com/31663028/63110745-1d3cda80-bf5a-11e9-9c81-2d11dfb2d062.png)

**Comment by PaulClark2** [comment]
@JonellaCulmer looks good to me. I don't have any comments or suggestions.

**Comment by JonellaCulmer** [comment]
These images are good to go. Closing this ticket in favor of implementation ticket: https://github.com/fecgov/fec-cms/issues/1635
