### ISSUE TITLE
Design for new data summary language 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#2986]
**User Story**

The regulated community needs to understand that the data summaries take time to update. In some cases they are not updated right away. 

**Background**

In #2924 we worked out the language to post on the website to alert the regulated community that the data takes time to update. 

**Completion Criteria**

- [x] Identify and mock-up where to place language on the website. Here is one idea from @AmyKort 
![image](https://user-images.githubusercontent.com/32739251/59926847-2fdadd80-9409-11e9-81a8-83ea505b920e.png)

- [ ] Create a front-end ticket to make the change to the hard-coding to implement this wording:

> Newly filed summary data may not appear for up to 48 hours.

**Comment by dorothyyeager** [comment]
Include front-end deadline of 7/14 in the follow-up ticket.

**Comment by JonellaCulmer** [comment]
@kathycarothers @PaulClark2 To start, I want to make sure we have an inventory of all the places this language is needed. Is below correct?
- Data tables
- Visualizations
- Candidate profile pages
- Committee profile pages

**Comment by kathycarothers** [comment]
@JonellaCulmer @PaulClark2 That would be correct

**Comment by PaulClark2** [comment]
@JonellaCulmer you're list looks correct to me.

**Comment by JonellaCulmer** [comment]
@kathycarothers @PaulClark2 @AmyKort Below is a list of all the places I believe we need to include this new language. Please let me know if any of these places are incorrect or if I'm missing a page.

Data tables: [Presidential candidates](https://www.fec.gov/data/candidates/president/), [Senate candidates](https://www.fec.gov/data/candidates/senate/?is_active_candidate=true), [House of Representatives candidates](https://www.fec.gov/data/candidates/house/?is_active_candidate=true)

Visualizations: [Cumulative amount raised by committees](https://www.fec.gov/data/browse-data/?tab=raising), [Cumulative amount spent by committees](https://www.fec.gov/data/browse-data/?tab=spending), [Office/party totals raised and Top raising bar chart](https://www.fec.gov/data/raising-bythenumbers/), [Office/party totals spent and Top spending bar chart](https://www.fec.gov/data/spending-bythenumbers/)

Candidate profile pages: [Financial summary tab](https://www.fec.gov/data/candidate/P80001571/), [Raising tab](https://www.fec.gov/data/candidate/P80001571/?tab=raising), [Spending tab](https://www.fec.gov/data/candidate/P80001571/?tab=spending), [Spending by others to support or oppose](https://www.fec.gov/data/candidate/P80001571/?tab=other-spending)

Committee profile pages: [Financial summary tab](https://www.fec.gov/data/committee/C00580100/?cycle=2020), [Raising tab](https://www.fec.gov/data/committee/C00580100/?cycle=2020&tab=raising), [Spending tab](https://www.fec.gov/data/committee/C00580100/?cycle=2020&tab=spending)

**Comment by JonellaCulmer** [comment]
@kathycarothers @PaulClark2 @AmyKort Draft mock-ups are below. I considered something a little more involved with messages, but think that even though this information may not apply all the time, this implementation seems simpler. Some of this placement seems a bit heavy. I'm trying to balance the need for this language to be prominent with all the places that require it. If you feel we can scale back anywhere, I would appreciate your thoughts.

### Datatables
New language placed in a message on the bottom of the filter panel
![Desktop - filter panel](https://user-images.githubusercontent.com/31663028/60974845-d45d8a80-a2f8-11e9-8aad-985d902a6f30.jpg)

### Cumulative amount raised and spent line charts
New language placed at the bottom of the charts.
![Advanced-data_raising](https://user-images.githubusercontent.com/31663028/60975043-36b68b00-a2f9-11e9-997a-dde4e6b7b7ae.jpg)

### Office/party totals (raised and spent) and Top spending candidates (raised and spent)
New language added at the bottom of both charts on both the raising and spending chart pages.
![Raising Breakdown - Main Copy 9](https://user-images.githubusercontent.com/31663028/60977288-2dc7b880-a2fd-11e9-863a-0a8155e25e83.jpg)

### Candidate and committee profile page - financial summary
New language introduced at the bottom of each table.
![Committee - Financial summary](https://user-images.githubusercontent.com/31663028/60974277-cc511b00-a2f7-11e9-8ab8-4f58d09925c7.jpg)

### Candidate and committee page - raising tab
New language added at the bottom of the Total receipts table
![Committee - Raising](https://user-images.githubusercontent.com/31663028/60974371-fd315000-a2f7-11e9-88aa-a86f2d86e882.jpg)

### Candidate and committee page - spending tab
New language added at the bottom of the total disbursements table
![Candidate - Spending ](https://user-images.githubusercontent.com/31663028/60974478-2651e080-a2f8-11e9-9644-79b9c3226c0f.jpg)

### Candidate profile page - spending by others to support or oppose
New langauge added at the bottom of the IE table. This section was trickier since it combines the summary figures with individual transactions. Let me know if folks feel that this is a confusing placement.
![Candidate - Spending by others](https://user-images.githubusercontent.com/31663028/60974692-86e11d80-a2f8-11e9-9e7b-aa69c0482a54.jpg)

**Comment by kathycarothers** [comment]
@JonellaCulmer I like what you did with the placement of the language. I do agree with you on the last chart you provided for the IE table. The language at the bottom could be confusing, or people can get lost in the language. I don't think those two sentences should be combined. Maybe put it on a separate line or move it to the top?!?! I am not sure. hmmmmm
@AmyKort @PaulClark2

**Comment by PaulClark2** [comment]
@JonellaCulmer I'm not sure. I makes sense to me but I know what we are trying to say. I wonder if @kathycarothers' suggestion would help. It would certainly make it clearer to users that the two notes below the table are independent.

**Comment by JonellaCulmer** [comment]
Thanks @kathycarothers and @PaulClark2. Please see the updated mockup below to move the language up by the totals figures. It makes sense up here and is similar to the placement in other instances. 

![Candidate - Spending by others_take2](https://user-images.githubusercontent.com/31663028/60993224-ff0d0a80-a31b-11e9-991a-6ce3899a87be.jpg)

**Comment by kathycarothers** [comment]
@JonellaCulmer @PaulClark2 I think that will work. I like the change.

**Comment by PaulClark2** [comment]
@JonellaCulmer I agree with @kathycarothers . I like the change.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue https://github.com/fecgov/fec-cms/issues/3040
