### ISSUE TITLE
Identify pages and content for new 404 pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2993]
**What we're after:**
We continually try to seek out new ways to improve the user experience across .gov including improved navigation and findability. One way we can make it easier on our users who have trouble locating a specific page is to improve our 404 pages and provide helpful information that might either answer the question on a different page, or point them to other details that might help them achieve their goals. 

For example: If a user is looking for a PDF can we provide options to the correct PDF on a 404 page? If a user is looking for information on a newly registered candidate, what information can we provide on a 404 page that gives them some information they might find helpful? 

### Related issues
- https://github.com/fecgov/fec-cms/issues/2865

### Completion criteria
- [ ] Compile list of the different pages types and consider helpful content for those pages
  - Candidate profile pages
  - Committee profile pages
  - Election profile pages
  - CMS-templated pages
  - Hard-coded pages
- [ ] Document pages and content
- [ ] Open implementation issue

### Future work

We should consider improving our data messages if possible and being more specific. And implement the work for [improved calendar messaging for no results](https://github.com/fecgov/fec-cms/issues/2315).

**Comment by kathycarothers** [comment]
@JonellaCulmer let's set up a meeting to talk about these pages.

**Comment by JonellaCulmer** [comment]
@patphongs @johnnyporkchops 

@kathycarothers and I are hoping we can set up a time to talk to you about the possibilities for our 404 pages. We need to get a better understanding about how the 404 messages are generated and what we can do to automate responses either based on the URL, SEO tags, or something else we're not thinking of. 

Before @kathycarothers starts to document all the possible pages that we'd want to implement new more helpful 404 pages, we'd like to know what's within the realm of possibility. 

The point of this work is to help our users find other places on the site where they may get their answers and we're thinking this may involve the page URLs or SEO.

**Comment by patphongs** [comment]
**404 Errors** - Right now these are generic and will raise the same 404 no matter where you are on the site. Perhaps we can think about displaying a custom 404 page per bucket of content: Data, Help for candidates and committees, Legal resources, About. There are other things that don't go into those buckets such as Press, Getting started with campaign finance data, FOIA, Inspector general, updates, and calendar. 

**500 Error** - This most likely happens when we can't get a response from the API. It would be nice to explain this to be more user friendly. It's not always the case it's an API issue.

**No data type errors** - These errors occur in our data templates when you are on profile pages and don't have any data. These are customizable per data page type.

**Comment by kathycarothers** [comment]
@patphongs Thank you. This explanation is super helpful. @JonellaCulmer let's set-up a meeting for Tuesday if possible to discuss the next steps.

**Comment by JonellaCulmer** [comment]
Thanks @patphongs for that information. It's really helpful.

@kathycarothers Here's the start of a list of all the bucket and non-bucket pages. (May need to come up with something better than non-bucket). 

https://docs.google.com/spreadsheets/d/1Ej7Qh_LdWpKOUWlh7CgmYRy65tLlRkR-W2pzw23OsOQ/edit#gid=0

**Comment by JonellaCulmer** [comment]
@kathycarothers and I have gone through the potential pages that we can send users to for more information, if a particular page they're looking at 404s. Would love some feedback from @AmyKort and @dorothyyeager and @bmathesonFEC if you have time. See our working spreadsheet: https://docs.google.com/spreadsheets/d/1Ej7Qh_LdWpKOUWlh7CgmYRy65tLlRkR-W2pzw23OsOQ/edit#gid=0

Next steps: 
- [ ] Open a new issue to mock-up these new 404 pages

**Comment by dorothyyeager** [comment]
A few thoughts 

The Legal Resources landing page (https://www.fec.gov/legal-resources/) actually has a Record feed embedded in it so that seems like the best place to point people for everything legal. 

For Help for candidates and committees, what you have is good, and I'd add the contact your analyst form and something related to e-filing (like contact information)

If the updates feed isn't working, I'd use the calendar, the legal resources landing page, Press main page at https://www.fec.gov/press/, the meetings page at https://www.fec.gov/meetings/ and to sub for the tips, contact info for Info Div and RAD plus a link to H4CC landing page. (The Record is an Updates thing and doesn't have another place to point them, but all of the other stuff together would sub well for it.)

For the calendar, I'd point to https://www.fec.gov/meetings/, Dates and deadlines, Trainings, https://www.fec.gov/legal-resources/regulations/pending-rulemaking-matters-comment/ and https://www.fec.gov/updates/?update_type=fec-record&category=advisory-opinions.

**Comment by JonellaCulmer** [comment]
Now that we have a list of content needed, we're closing this in favor of design issue: https://github.com/fecgov/fec-cms/issues/3114
