### ISSUE TITLE
Design how to add "Connected organization" to the SSFs only committee profile pages

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3024]
Follow-up task for https://github.com/fecgov/openFEC/issues/3807

Per @PaulClark2, "Connected organization" should be included with the information on the "about this committee tab" of all SSFs. These committees have connected organizations: C00053553, C00002089, C00096156, C00029447, C00007922.

Add "Connected organization" to "About this Committee" page for SSFs only ([example](https://www.fec.gov/data/committee/C00053553/?tab=about-committee)) This is an example API call where you will see an `organization_type`: https://api.open.fec.gov/v1/committee/C00053553/history/?per_page=1&api_key=DEMO_KEY. This means where org_type is: 
C corporation
L labor organization
M membership organization
T trade association
V cooperative
W corporation without capital stock

SSF examples:

org_tp | min | max
-- | -- | --
W | [C00012153](https://www.fec.gov/data/committee/C00012153/?tab=about-committee) | [C00690149](https://www.fec.gov/data/committee/C00690149/?tab=about-committee)
C | [C00000042](https://www.fec.gov/data/committee/C00000042/?tab=about-committee) | [C00709956](https://www.fec.gov/data/committee/C00709956/?tab=about-committee)
L | [C00000000](https://www.fec.gov/data/committee/C00000000/?tab=about-committee) | [C00702043](https://www.fec.gov/data/committee/C00702043/?tab=about-committee)
V | [C00000422](https://www.fec.gov/data/committee/C00000422/?tab=about-committee) | [C00681338](https://www.fec.gov/data/committee/C00681338/?tab=about-committee)
M | [C00000117](https://www.fec.gov/data/committee/C00000117/?tab=about-committee) | [C99002727](https://www.fec.gov/data/committee/C99002727/?tab=about-committee)
T | [C00000026](https://www.fec.gov/data/committee/C00000026/?tab=about-committee) | [C00702092](https://www.fec.gov/data/committee/C00702092/?tab=about-committee)

**Completion criteria:**
- [x] Ensure that the PAC sponsor's name is part of the API call. Not just the full name of the PAC. If not create a new API ticket to add this. See https://github.com/fecgov/openFEC/issues/3807 and https://github.com/fecgov/openFEC/pull/3847. #3847 will be part of release 9.4.
- [x] Decide where this new "Connected organization" label will go. Should it go in the About this committee tab or somewhere else?
- [ ] Decide null states for SSFs who don't have this. This may be null in the beginning if the committee has not added this to their form. They are required to add this eventually.
- [ ] Create front-end implementation issue and business logic for this. ~API ticket for adding PAC sponsor name may block this ticket (see first item in this list).~

**Comment by JonellaCulmer** [comment]
Below is a mock-up of what the new About this committee section can look like for applicable committees with connected organizations. 

Instead of grouping the committee name next to the connected organization, I'd recommend we place it at the bottom of the list for a couple reasons. Listing both names at the top might introduce confusion as to which name is the committee name when read at a glance. 

Also, listing the connected organization name second in this list, may create confusion, since the committee name is followed by the address. I'd rather not confuse users at to which one belongs to that address. The organization's address may be different. 

As for when the connected organization is not provided by the filing committee, I'd recommend at this time that we leave it blank. More often than not when we do not have the data, as in it was not provided, that we leave those spaces blank. This is most obvious on our datatables. 

Other verbiage we use to describe why data is missing include: 
_null_: too technical
_unknown_: that's more like we can't determine it
_not applicable_: which, in this case, it is, or 
_no data available in table_: which is more like something doesn't exist rather than we don't have it

I welcome any and all feedback. cc: @dorothyyeager @AmyKort 

<img width="979" alt="Screen Shot 2019-07-26 at 9 42 29 AM" src="https://user-images.githubusercontent.com/31663028/61959280-104b4d80-af91-11e9-8abc-4100dca0f458.png">

**Comment by dorothyyeager** [comment]
No special feedback from me! This looks great and your reasons for placing it where you did seem very sound to me. Thanks @JonellaCulmer !

This is more of a question for @PaulClark2: For "Committee type" - why don't we say SSF or separate segregated fund for these types of PACs?

**Comment by AmyKort** [comment]
Thanks, @JonellaCulmer . This looks great to me. My only question is about leaving the connected organization line blank if we're missing that information. Your reasoning makes sense to me. But, @dorothyyeager got me thinking about how I can't really tell this is an SSF except for the fact that it has a connected org--and I guess the name? So if that's listed as an option, but blank, I'm not sure what that's telling me. I guess this is a question for @PaulClark2 and @jwchumley , because what would answer my question would be to label the committee as an SSF.

**Comment by lbeaufort** [comment]
We want to look at org_type, like the chart at the top of the issue: 
C corporation
L labor organization
M membership organization
T trade association
V cooperative
W corporation without capital stock

**Comment by lbeaufort** [comment]
@JonellaCulmer @AmyKort We can conditionally show/hide a field based on organization type, and that way only show the connected org field for SSFs.

**Comment by JonellaCulmer** [comment]
@lbeaufort @AmyKort Right. This additional field is only really valuable for those committees who have and are supposed to provide the name of their connected organization. I would not recommend listing for every committee type. Otherwise that would introduce other language such as "Not applicable" for a candidate committee, for example. That doesn't make sense.

**Comment by AmyKort** [comment]
Thanks for clarifying that. I guess my question was why we don't indicate in the mock-up that this is an SSF, except for the fact that there's a connected organization. But, maybe that question is outside the scope of this issue.

**Comment by lbeaufort** [comment]
@AmyKort good point! @JonellaCulmer and Amy, maybe it makes sense to show organization type on the committee profile page for SSF's, or indicate in some way that they're SSF's.

**Comment by JonellaCulmer** [comment]
@AmyKort Oh, got it. Thanks, Amy. Yes, everything else that's in the mock-up is what is currently in production, so that would be a new change. I can open a follow-up ticket to add that in, since we do provide that for other committee types such as candidate committees and parties.

**Comment by AmyKort** [comment]
That would be awesome @JonellaCulmer . Thank you. And, I agree with @dorothyyeager (as usual) that your work on this issue is great!

**Comment by JonellaCulmer** [comment]
Closing this issue in favor of these followup issues: 
- Update committee type to show specific PAC type https://github.com/fecgov/fec-cms/issues/3079
- Add connected organization to committee profile pages https://github.com/fecgov/fec-cms/issues/3078
