### ISSUE TITLE
Craft message for MUR search to indicate it only includes closed cases

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3049]
### Summary

**What we are after:**
Users of the MUR search date filters need to know that the search only returns closed cases. For example, searching 2019 dates opening now yields no results, but only because all 2019 cases are still open.

### Related issues

- #2969 

### Completion criteria

- [x] Draft message
- [x] Review by content team (and OGC enforcement?)
- [x] Once message crafted, put in front-end implementation ticket.

### Future work

- [ ] Front end implements the new message.

**Comment by AmyKort** [comment]
The search box on the main enforcement page (https://www.fec.gov/legal-resources/enforcement/) says "Search closed MURs." Should we label https://www.fec.gov/data/legal/search/enforcement/?case_no= "Closed Matters Under Review" instead of "Matters under review." That might be more effective than coming up with a message and finding a place to put it where folks will see it, but it also won't be in the way.

**Comment by dorothyyeager** [comment]
I think that's a good idea @AmyKort, especially for those people who land on that search page first.  Right now you'd look at that page and think it includes all the cases, so anything we can do to indicate it doesn't include the currently open ones would be helpful.

**Comment by AmyKort** [comment]
Thanks @dorothyyeager ! I think this is a pretty big problem, and changing the label for the table is the most high profile change I can think of. Since we'd be mirroring the language on the enforcement landing page, I don't think we'd need review.

We should also probably add "closed" to the message at the top that explains what's in there an links to EQS. "The MUR search feature includes all *closed* cases dating back to  . . . "

**Comment by dorothyyeager** [comment]
We're going to go with @AmyKort's suggestions above.

The message is crafted and the implementation ticket is at #3083 so closing this ticket.

**Comment by dorothyyeager** [comment]
Reopening to add the estimate then closing.
