### ISSUE TITLE
House/Senate reports datatable won't load

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3057]
### Summary

House/Senate reports datatable won't load in `dev` and `stage` but will load in `prod`

### Frequency

It's currently replicable but it looks like it's happened in the past: https://github.com/fecgov/fec-cms/issues/2206

### How to Reproduce

1. Go to https://fec-stage-proxy.app.cloud.gov/data/reports/house-senate/?data_type=processed
2. Page won't load
3. See console errors
4. API call loads (see network tab) https://api-stage.open.fec.gov/v1/reports/house-senate/?api_key=oXyFx4md0kTkxxq9JNfIRlrOPorXc60dqOVEs4GE&sort_hide_null=false&sort_nulls_last=true&data_type=processed&sort=-receipt_date&per_page=30&page=1

### Browser

_Which version of which browser are you using? Does this issue occur with other browsers or with other browser sizes?_

- [X] Chrome

### Device

_Tell us what you can about your device and its operating system._

- [X] Laptop/desktop (Mac)
- [ ] Tablet
- [ ] Phone

### Screenshots

![image](https://user-images.githubusercontent.com/31420082/61409932-457cdf00-a8b1-11e9-8d99-c79acfa3d372.png)

**Comment by patphongs** [comment]
The error is happening on because it is attempting to access `row.amendment_chain.length`. On stage, `amendment_chain` JSON key is returning NULL. It should have a value I think. According to prod, those values are populated. Compare the results between stage and prod below:

https://api-stage.open.fec.gov/v1/reports/house-senate/?api_key=NICAR16&sort_hide_null=false&sort_nulls_last=true&data_type=processed&sort=-receipt_date&per_page=30&page=1

https://api.open.fec.gov/v1/reports/house-senate/?api_key=NICAR16&sort_hide_null=false&sort_nulls_last=true&data_type=processed&sort=-receipt_date&per_page=30&page=1

**Comment by PaulClark2** [comment]
Discussed with @patphongs @fec-jli and @hcaofec . The production API call for House and Senate produces a different return than the same call to stage API.  Helen and Jun will investigate what's causing the difference on stage.

**Comment by patphongs** [comment]
Future work will also include catching null values in `amendment_chain` and displaying something for it rather than not loading the table at all. New ticket has been logged: https://github.com/fecgov/fec-cms/issues/3060

**Comment by fec-jli** [comment]
the cause has been identified in the following ticket.
[https://github.com/fecgov/openFEC/issues/3871](https://github.com/fecgov/openFEC/issues/3871)

**Comment by lbeaufort** [comment]
Issue has been addressed in ticket above
