### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#3073]
@fec-issues-bot commented on [Wed Jul 24 2019](https://github.com/fecgov/FEC/issues/9025)

## What were you trying to do and how can we improve it?
 I was trying to access https://www.fec.gov/resources/about-fec/commissioners/ravel/statements/141009_McCutcheon_Statement.pdf

The document is titled "Statement on Rulemaking in Response to McCutcheon v. FEC" 

## Tell us about yourself
 I'm an FEC employee trying to access the rulemaking record 

## Details
* URL: https://www.fec.gov/about/leadership-and-structure/ann-m-ravel/ 
* User Agent: Amazon CloudFront

**Comment by dorothyyeager** [comment]
I think this is what they are looking for: https://sers.fec.gov/fosers/showpdf.htm?docid=305263.

@AmyKort I can assign this to myself and fix the link if you want.

**Comment by AmyKort** [comment]
Thank you @dorothyyeager !

**Comment by dorothyyeager** [comment]
Since it was a rulemaking-related document, it was in the SERS database for that particular rulemaking. I've replaced the broken link on former [Commissioner Ravel's page](https://www.fec.gov/about/leadership-and-structure/ann-m-ravel/) (scroll down to second from bottom under "Rulemaking and Litigation") with the link to the document in SERS. Closing since the link is fixed.
