### ISSUE TITLE
Decide on the business rules for what org type information to show on PAC profile pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3079]
**What we're after:**
Following up on the work to add connected organization names, we want to now make it clear which PAC type a user is looking at when on a committee profile page. It is somewhat unclear what the committee type is when it says PAC - Nonqualified. We think we can do better. This would also make these pages consistent with other profile pages such as candidate committee profile pages and parties.

### Related issues
- https://github.com/fecgov/fec-cms/issues/3078
- https://github.com/fecgov/fec-cms/issues/3024

### Completion criteria
- [ ] see @PaulClark2 to determine business rules for committee_type/org_type requirements
- [ ] Consult with content team for desired business logic on the appropriate language/descriptor for each org type beyond what's in the database

### Example: 
<img width="725" alt="Screen Shot 2019-07-26 at 1 26 38 PM" src="https://user-images.githubusercontent.com/31663028/61969656-0df4ed80-afa9-11e9-8646-e474186d57a0.png">

**Comment by patphongs** [comment]
@PaulClark2 @JonellaCulmer I found out that we actually try and print out organization type in the website code, but the value is never added because the attribute name `organization` does not exist anymore in the API. We probably want to print out `organization_type_full`? There's no other criteria in this if condition though, it seems it was the intention to print out organization type if it existed. This ticket seems to stipulate that we only want to show organization_type if it's considered a PAC?

**Current code:**
```        
      {% if organization %}
          <tr>
            <td class="figure__label">Organization type:</td>
            <td class="figure__value">
                {{ organization }}
            </td>
          </tr>
        {% endif %}```

**New suggested code if requiring only for PACs:**
```        
      {% if organization_type in [list_of_org_types]  %}
          <tr>
            <td class="figure__label">Organization type:</td>
            <td class="figure__value">
                {{ organization_type_full }}
            </td>
          </tr>
        {% endif %}```
