### ISSUE TITLE
Draft methodology for Where contributions come from

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3123]
**What we're after:** As part of our work on the Where contributions come from chart, we need to explain our methodology for how we come to the numbers presented in the chart. 

**Completion criteria:**
- [x] Draft methodology
- [x] Finalize draft
- [ ] ~Create Wagtail page~
- [ ] ~Create pop-up on WCCF with methodology. (#2929)~

**Example methodology:**
METHODOLOGY OVERVIEW
This data includes Forms 3, 3P, and 3X.
**Money raised** includes each of the following:

Adjusted receipts for PACs, parties, congressional filers and presidential filers
Adjusted receipts are the total receipts minus the following:

Contribution refunds
Contributions from political party committees and other political committees
Loan repayments
Offsets to operating expenditures
Transfers from nonfederal accounts for allocated activities
The form-by-form breakdown for adjusted receipts is:

**Form 3:** line 16 - (line 11(b) + line 11(c) + line 14 + line 19(c) + line 20(d))
**Form 3P:** line 22 - (line 17(b) + line 17(c) + line 20(d) + line 27(c) + line 28(d))
**Form 3X:** line 19 - (line 11(b) + line 11(c) + line 15 + line 16 + line 18(a) + line 26 + line 28(d))

Applicable endpoints: https://github.com/fecgov/fec-cms/issues/2906#issuecomment-496673868

### Future work

- [ ] Create ticket to consider possible About the data methodology page in wagtail

**Comment by PaulClark2** [comment]
I used the methodology of the HOW MUCH MONEY HAS BEEN RAISED BETWEEN: chart as my model. The drafts below are also in a Google doc (FEC-18F-share > Data > Methodology pages > Methodology: Where individual contributions come from). I'm open to any and all suggestions. We might want to run this by Press and Public Records. They are going to get the phone calls about the chart.

**VERSION 1**

**METHODOLOGY OVERVIEW**
This data includes individual contributions from Forms 3 and 3P.

Individual contributions include the following: 

- Categorized individual contributions and 
- Inferred individual contributions.

Categorized individual contributions are transactions that have been assigned one of several transaction type codes associated with individual contributors. These codes are  “15,” “15E,” “15J,”  “11” and “11J.” These contributions are usually found on Form 3 Lines 11(a)(i) and 12 or Form 3P Lines 17(a)(i) and 18.

Inferred individual contributions are transactions that are not assigned a transaction type code and have a null memo code. These transactions are not assigned transaction type codes because the aggregate for the contributor is less than $200.00. These transactions are reported on Form 3 Lines 11(a)(i) and 12 or Form 3P Lines 17(a)(i) and 18

[link to transaction type page] https://www.fec.gov/campaign-finance-data/transaction-type-code-descriptions/

**VERSION 2**

**METHODOLOGY OVERVIEW**

This data includes individual contributions from Forms 3 and 3P.

Individual contributions include the following: 

- Categorized individual contributions and 
- Inferred individual contributions.

Categorized individual contributions are transactions that have been assigned one of several transaction type codes associated with individual contributors.

Inferred individual contributions are transactions that are not assigned a transaction type code and have a null memo code. These transactions are not assigned transaction type codes because the aggregate for the contributor is less than $200.00.
 
Transaction types of categorized individual contributions are “15,” “15E,” “15J,”  “11” and “11J..” These contributions are usually found on Form 3 Lines 11(a)(i) and 12 or Form 3P Lines 17(a)(i) and 18.. 

Inferred individual contributions are transactions found on Form 3 Lines 11(a)(i) and 12 or Form 3P Lines 17(a)(i) and 18 with no transaction type code and no memo code.

[link to transaction type page] https://www.fec.gov/campaign-finance-data/transaction-type-code-descriptions/

**Comment by pkfec** [comment]
@AmyKort @dorothyyeager @kathycarothers @bmathesonFEC  Please review the drafts.

**Comment by dorothyyeager** [comment]
I vote for version 4. Just some nitpicky things for me on that one. For describing forms on the website, we've not been saying "FEC Form X" but just "Form X" so I'd take out "FEC" for that line. I'd add this line from Version 2: "These contributions are usually found on Form 3 Lines 11(a)(i) and 12 or Form 3P Lines 17(a)(i) and 18." to the end of it. @PaulClark2 @pkfec

**Comment by PaulClark2** [comment]
With @dorothyyeager 's suggested edits

The state totals have been calculated by summing itemized individual contributions disclosed on Lines 11(a)(i) and 12 of Form 3 (for congressional candidates) and Lines 17(a)(i) and 18 of Form 3P (for presidential candidates) for each state or region.

Note that unitemized individual contributions are not included in these totals. For contributions that do not exceed $200 when added to the contributor’s previous contributions made during the election cycle (for candidate committees), the receiving committee must report only the lump sum amounts of all unitemized contributions to the FEC. No contributor information is required to be provided to the FEC in connection with unitemized contributions.

The transaction types of itemized individual contributions of congressional and presidential campaign committees are “15,” “15E,” “15J,” “11” and “11J.” These contributions are usually found on Form 3 Lines 11(a)(i) and 12 or Form 3P Lines 17(a)(i) and 18.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Added a bit more formatting from the first versions. I also moved up the last line so it wouldn't be 1. what the data includes 2. what it doesn't include 3. what the data includes.

**METHODOLOGY OVERVIEW**
The state totals have been calculated by summing itemized individual contributions disclosed on Lines 11(a)(i) and 12 of Form 3 (for congressional candidates) and Lines 17(a)(i) and 18 of Form 3P (for presidential candidates) for each state or region.

The transaction types of itemized individual contributions of congressional and presidential campaign committees are “15,” “15E,” “15J,” “11” and “11J.”

**Unitemized individual contributions are not included in these totals.** For contributions that do not exceed $200 when added to the contributor’s previous contributions made during the election cycle (for candidate committees), the receiving committee must report only the lump sum amounts of all unitemized contributions to the FEC. No contributor information is required to be provided to the FEC in connection with unitemized contributions.

**Comment by PaulClark2** [comment]
Thanks @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@PaulClark2 @rfultz Why does this need to be a wagtail page? Neither of our other features use wagtail pages for the methodology?

See Who's raising/spending the most methodology: https://www.fec.gov/data/raising-bythenumbers/

**Comment by rfultz** [comment]
@JonellaCulmer, I don't think it does. But @PaulClark2 was talking the other day about maybe having all of our Methodology details on one page and linking to that page from everywhere else in the site so this could be that

**Comment by PaulClark2** [comment]
@rfultz @JonellaCulmer It doesn't have to be a Wagtail page.  I'd like to eventually have an `about our data` section that is a Wagtail page that we could link to for data explanations, processing, methodology, etc.  I've only started thinking about this. So that we don't slow things down for WCCF, I think it's fine that we implement the description of the methodology like we did for `How much money has been raised`.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Okay, thank you. I added that to future work in the original comment.

**Comment by PaulClark2** [comment]
Thank you everyone. This is the version of the methodology we'll use. cc: @rfultz @JonellaCulmer 

**METHODOLOGY OVERVIEW**
The state totals have been calculated by summing itemized individual contributions disclosed on Lines 11(a)(i) and 12 of Form 3 (for congressional candidates) and Lines 17(a)(i) and 18 of Form 3P (for presidential candidates) for each state or region.

The transaction types of itemized individual contributions of congressional and presidential campaign committees are “15,” “15E,” “15J,” “11” and “11J.” These contributions are usually found on Form 3 Lines 11(a)(i) and 12 or Form 3P Lines 17(a)(i) and 18.

**Unitemized individual contributions are not included in these totals**. For contributions that do not exceed $200 when added to the contributor’s previous contributions made during the election cycle (for candidate committees), the receiving committee must report only the lump sum amounts of all unitemized contributions to the FEC. No contributor information is required to be provided to the FEC in connection with unitemized contributions.

**Comment by JonellaCulmer** [comment]
Closing in favor of work in progress (#2929)
