### ISSUE TITLE
Featured/pinned announcement on homepage not functioning

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3192]
**What we're after:** Back in the day we explored featuring articles/posts on the homepage announcements. We had it "working" to a degree, but it appears that functionality is not working now. So we need to explore why this feature is not functioning and what changes need to be made in order to utilize it. 

Previous PR: https://github.com/fecgov/fec-cms/pull/1035

**Completion criteria:**
- [ ] Wagtail users should be able to pin/save/feature a story/article in the news and announcements section of the homepage - 1 story at a time
- [ ] Should be able to use the homepage feed section in the wagtail promote tab to implement this. See screenshot below.

**Expected Behavior/Screenshot:**

<img width="771" alt="Screen Shot 2019-09-24 at 9 36 36 AM" src="https://user-images.githubusercontent.com/31663028/65520749-19d03380-deb6-11e9-9a3e-dd2f87b48d5a.png">

![Screen Shot 2019-12-02 at 11 08 11 AM](https://user-images.githubusercontent.com/12799132/69974893-285d4b80-14f4-11ea-891f-73d7fdacb7b3.png)

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , This feature seems to  works but:
1)The homepage_pin option is currently only enabled  for  `RecordPage` and `PressReleasePage` 
2) Was written (coded) to show features in order of precedence if more than one item is pinned for the same (or overlapping ) time period. Meaning, a press release pinned takes precedence over a record article pinned.
3) Also Weekly Digest section falls off when there is a pinned item because there is only room for four items.
The above conditions may be why we think it does not work. 

- I can enable it for `TipsForTreasurers` page locally as well --but it was commented out [here](https://github.com/fecgov/fec-cms/blob/9fb2eb4357361b68e148899738f592a7c09777a1/fec/home/models.py#L498-L514) due to migration errors quite some time ago and need to research if why that was and figure out if it might cause the same issue later (although it is not breaking migrations now)

- [ ] Pair with content team to decide how we actually want this to work.

**Comment by johnnyporkchops** [comment]
We confirmed that homepage_pin works on production for `record articles` and `press releases`.
After discussion with @dorothyyeager and @JonellaCulmer, we came up with some questions:
Do we wan't to enable pinning for  Tips for Treasurers?
Do we want to change the current behavior so Weekly Digests  don't fall off when and item is pinned?

**Comment by JonellaCulmer** [comment]
Based on @johnnyporkchops's information above and the resulting conversations, we're changing our plan for this work. 

Closing this ticket in favor of https://github.com/fecgov/fec-cms/issues/3464
