### ISSUE TITLE
Regular Expression Denial of Service in useragent

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3224]
### Summary

High severity vulnerability found in useragent
  Description: Regular Expression Denial of Service (ReDoS)
  Info: [https://snyk.io/vuln/SNYK-JS-USERAGENT-174737](https://snyk.io/vuln/SNYK-JS-USERAGENT-174737)
  Introduced through: karma@4.1.0
  From: karma@4.1.0 > useragent@2.3.0

Remediation: None yet

**Comment by lbeaufort** [comment]
@patphongs @jason-upchurch if package is only used by our automated tests, is it safe to say that this vulnerability doesn't impact us?

**Comment by jason-upchurch** [comment]
@patphongs @lbeaufort 
The maintainer's repo is here:
https://github.com/3rd-Eden/useragent/issues/147

**Comment by jason-upchurch** [comment]
@patphongs @lbeaufort The `karma` library repo is here: https://github.com/karma-runner/karma (this library makes use of `useragent`).
A fix does not appear to be available at this time, either through updating `karma` or `useragent`. I recommend keeping an eye on these two libraries/repos so that when a fix is available we can incorporate it.

**Comment by lbeaufort** [comment]
@jason-upchurch thanks, I agree we should keep an eye out. However, if I'm understanding the vulnerability, it requires user input as the attack vector, which we're not making available to the public. All the input to `karma` comes from our automated tests, so I don't think this vulnerability impacts us.

**Comment by patphongs** [comment]
@jason-upchurch @lbeaufort Did some additional research on this. Because we are using karma under devDependencies, we are not compiling it in the final JS that gets pushed out to production. If you look inside of the `./fec/dist/fec/static/js` files that the JS files get compiled to in production, you'll notice that searching for "karma" in the code will yield no results. Therefore, we're not pushing out dev dependencies to production. Do I have this correct @rfultz ?

**Comment by jason-upchurch** [comment]
Moving to sprint 10.4 per @PaulClark2, keeping assigned to me, and I will keep an eye on remediation.

**Comment by rfultz** [comment]
💯devDependencies are only used at compile-time and don't go to the production server. Only the code in /fec/dist goes to Prod.

I'm even less worried about this issue because Karma plays traffic cop during our JavaScript tests (`npm run test-single`) and isn't compiled into our code. It's called during `npm run build-production`, yes, but it only outputs to the screen.

**Comment by jason-upchurch** [comment]
Reached out to SISO to discuss options for path forward. Planning discussion for next week.

**Comment by jason-upchurch** [comment]
useragent is not used in production code. We will keep an eye on the package for updates nonetheless and update when available or investigate alternative packages if the need arises. Pushing out to Sprint 10.6 for now.

**Comment by patphongs** [comment]
only used for development, so we don't need this
