### ISSUE TITLE
Remove transition pages from site search index

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3279]
### Summary

**What we're after:**
_We were recently able to re-index with our search.gov global search tool. We'll want to figure out which pages on transition we want to come up on the site search. Right now the index is using this to find which pages to index for transition: https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/data/transition_pages.json._

### Completion criteria

- [x] Take a look at transition site and make a list of pages we want to add to the global site search as well as pages that could be deleted. (Content team) **[LIST IS HERE](https://docs.google.com/document/d/1vIC_QGpDDqZL7E0qI-tlRLqhHWROLoRkNGVlnr1sREc/edit?usp=sharing)**
- [ ] Add/Delete items from transition_pages.json, and scrape. (Front-end)
- [x] We need to run a manual delete of items we want removed from the index using this documentation: http://gsa.github.io/slate/#delete-a-document (Front-end)

**Comment by dorothyyeager** [comment]
I've started taking an inventory of the most visited pages on the transition site now as well as important pages on there that might not be the most visited but which don't have a place on fec.gov yet.

**Comment by dorothyyeager** [comment]
I've done my inventory and hope to talk to @AmyKort because there's still a lot of decisions to make about various transition pages and possible redirects to implement, so lots we could work on in future PIs.

But for this task, it turns out there's only one page to add, and a whole bunch we can delete because we have gotten those pages off transition and redirected people. See [this list](https://docs.google.com/document/d/1vIC_QGpDDqZL7E0qI-tlRLqhHWROLoRkNGVlnr1sREc/edit?usp=sharing) for the ones to delete and the page to add.

**Comment by dorothyyeager** [comment]
Removing my assignment as the list is made and the task is ready for the front end when they have capacity.

Moving this to 11.6 for when front end has capacity. (If this is something the content team can handle with coaching, we'd be happy to do it.)
