### ISSUE TITLE
Draft methodology for IE version/deduping

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3360]
**What we're after:**
We need to better explain the differences between the different versions regarding deduped IEs: current version, past version and unknown version. From our user testing it was clear that users were unsure what we meant by unknown version and how we arrived at those classifications for each version. We need to explain this in our methodology.

### Related issues
- Update IE deduping designs based on testing results https://github.com/fecgov/fec-cms/issues/3193
-  Implement changes to flyout and filter panels for Raw IEs https://github.com/fecgov/fec-cms/issues/3011
- Add most_recent filter to /schedules/schedule_e/ (Processed data) https://github.com/fecgov/openFEC/issues/4058

### Completion criteria
- [ ] Draft IE versioning methodology
- [ ] Discuss necessary content changes with content team
- [ ] Make any appropriate design changes based on review

### Designs
Upon selecting "Version methodology" a pop-up will open on screen with the methodology. 
![Methodology Copy](https://user-images.githubusercontent.com/31663028/69056853-ce7e6100-09de-11ea-9000-1735f68d3c24.png)

**Comment by PaulClark2** [comment]
Do we need to explain "version unknown?"  I think that's what happens when the API cannot determine the current version. Is that correct @JonellaCulmer   Do we need to explain how we determine the most recent filing in an amendment chain? It's the filing with the largest report id (also called file number)? 

@dorothyyeager can you take a look at the draft? Also, anyone else on the team that want to comment, please do.


DRAFT: 

Current version is the most recent filing in an amendment chain. For example, a report amendment might include the original (new) report, amendment #1 and amendment #2. Checking "current version" will display transactions disclosed on amendment #2.

**Comment by PaulClark2** [comment]
Do we want to describe each version: "current," "past" and "unknown?"

**Comment by dorothyyeager** [comment]
@PaulClark2 I think you might want to describe all of them, especially "unknown." 

Want to ask something before I comment on draft. By amendment chain, do we mean a report, an amendment, and then an amendment of the amendment? Or do we just mean the report plus all amendments to it?

**Comment by dorothyyeager** [comment]
Also, if one selects "version unknown" do they get the original plus amendments?

**Comment by dorothyyeager** [comment]
Here's my stab at it so far, but as you can see from my questions, I may not understand what people are able to select. @PaulClark2 

_A report amendment might include the original (new) report and several amendments. Checking “current version” will display transactions disclosed on the most-recently filed amendment. Checking “past version” will display transactions disclosed on the amendment(s) filed before the most recent one. “Version unknown” means that the API is unable to determine whether the report is an original or an amendment._

**Comment by JonellaCulmer** [comment]
Hi @PaulClark2. Yes, we need to explain how we determine that something is unknown.

**Comment by PaulClark2** [comment]
Second try. cc: @dorothyyeager @JonellaCulmer @hcaofec 

When you check "current version," the website will display transactions disclosed on current version and unknown version reports. 

Current version transactions are those transactions disclosed on the most-recently filed amendment. A report amendment might include the original (new) report and several amendments. Those marked current version were disclosed on most-recently filed amendment. 

Unknown version transactions are those transactions disclosed on reports the API could not determine the version. This happens when an amendment might not associated with previous versions of the report. 

Past version transactions are those transactions disclosed on reports that are not the most-recently filed amendment.

**Comment by dorothyyeager** [comment]
Tightened it up a little; see if this works... Also if users understand  "current" vs. "past" we could consider deleting that last sentence. @PaulClark2 @JonellaCulmer 

_When you check "current version," the website will display “current version” and “unknown version” transactions._

_Current version transactions are those transactions disclosed on the most-recently filed amendment. 
A report amendment might include the original (new) report and several amendments._

_Unknown version transactions are those transactions disclosed on reports where the API could not determine the version because an amendment might not have been associated with previous versions of the report._

_Past version transactions are those transactions disclosed on reports that are not the most-recently filed amendment._

**Comment by JonellaCulmer** [comment]
@PaulClark2 I think what you've written is great with @dorothyyeager's minor changes. I would, however, keep the second 'paragraph' together, as Paul had it originally. And not on a separate line.

**Comment by dorothyyeager** [comment]
Hmm, both our drafts are four paragraphs? My second paragraph looks like it's on two separate lines but that's just where word wrap landed.

**Comment by PaulClark2** [comment]
@patphongs I think this is the final version unless Dorothy and I have misunderstood Jonella's comment. 

When you check "current version," the website will display “current version” and “unknown version” transactions.

Current version transactions are those transactions disclosed on the most-recently filed amendment. A report amendment might include the original (new) report and several amendments.

Unknown version transactions are those transactions disclosed on reports where the API could not determine the version because an amendment might not have been associated with previous versions of the report.

Past version transactions are those transactions disclosed on reports that are not the most-recently filed amendment.

**Comment by patphongs** [comment]
Updated Current version PR #3438 with the latest methodology above. Closing this issue.
