### ISSUE TITLE
Server error on C00140590 committee profile page 

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#3426]
**What happened :** C00140590 committee profile page is throwing a server error.
- url : https://www.fec.gov/data/committee/C00140590/
- Note : C00140590is a party committee and should not have an associated candidate. 

**Where:**  Found in production. This server error in consistent across all environments

**Screen shot:**  : 

<img width="982" alt="Screen Shot 2019-12-23 at 6 54 39 PM" src="https://user-images.githubusercontent.com/11650355/71385437-b6899680-25b5-11ea-9f82-32b60361f17f.png">

**Reference PR**: https://github.com/fecgov/fec-cms/pull/3299

**Comment by jason-upchurch** [comment]
@pkfec @fec-jli this is the stack trace I encountered:

```
File "/Users/jupchurch/dev/cms/fec-cms/fec/data/templates/macros/cycle-select.jinja", line 53, in template
    {% for each in cycles | sort(reverse=True) %}
  File "/Users/jupchurch/.pyenv/versions/cms-dev/lib/python3.6/site-packages/jinja2/filters.py", line 278, in do_sort
    return sorted(value, key=key_func, reverse=reverse)
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by fec-jli** [comment]
The reason is cycles_has_activity return a 'None' value in ofec_committee_history_mv
wrong example query: select * from ofec_committee_history_mv where committee_id='C00140590'
cycles_has_activity=[1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020, NULL]

the correct query: select * from ofec_committee_history_mv where committee_id='C00105668'
cycles_has_activity=[1978, 1980, 1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020]

solution:
1)We will create an separated issue to fix ofec_committee_history_mv.
2)modify cms load_committee_history function in views.py
to clean cycles_has_activity, remove 'None' value in cycles_has_activity
`    committee['cycles_has_activity'] = list(filter(None, committee.get('cycles_has_activity')))
`

**Comment by fec-jli** [comment]
for some reasons, my local cms could not pass `npm run test-single`,
so I have to force push my branch. 
<img width="948" alt="Screen Shot 2019-12-23 at 10 56 25 PM" src="https://user-images.githubusercontent.com/24395751/71392829-9bc81980-25d7-11ea-90dd-58ef57e405a1.png">
