### ISSUE TITLE
Create presidential map data on browse data candidates section 

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3486]
### Summary

**What we're after:**
_We need to add presidential map data to the [browse data candidates section](https://www.fec.gov/data/browse-data/?tab=candidates)._

### Related issues

_List any relevant related issue(s)_
- https://github.com/fecgov/fec-cms/issues/3483

### Completion criteria

- [ ] Presidential map data should appear on the Browse data, Candidates tab in 4 accordions, according to the mock up #3483.
- [ ] Only display 2020 presidential candidate's data for this first iteration

**Comment by JonellaCulmer** [comment]
@patphongs Since we're not able to do the accordions at this time, we need to make sure the the "All states" file is available for all applicable years in both the Democratic and Republican candidates accordions. Right now there's just one for 4 election years. 

<img width="486" alt="Screen Shot 2020-01-27 at 12 06 20 PM" src="https://user-images.githubusercontent.com/31663028/73196505-b07b5e00-40fd-11ea-8f45-2dede10ca7d8.png">

**Comment by JonellaCulmer** [comment]
@patphongs The only section that really needs to be indented is the section with states listed out. Everything else should be left-aligned. We also need to specify now that the candidates listed (for now) include only 2020 candidates.

<img width="513" alt="Screen Shot 2020-01-27 at 12 20 01 PM" src="https://user-images.githubusercontent.com/31663028/73197668-b2deb780-40ff-11ea-89b3-a93a7b114889.png">

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, I have made the corrections that you suggested. I also got the chance to push up the WIP PR here: https://github.com/fecgov/fec-cms/pull/3487. Can you pull down the PR again and continue any design comments you might have in there. 

I also added the Report summaries form 3P that was requested inside the all candidates accordion. Can you check if there's a better place to put it in the accordion or if the placement is ok as is?
