### ISSUE TITLE
Add test coverage for presidential map

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3560]
- [x] Enable JS tests that were disabled by c6a5b902d78a8b41ad2e9cb6ae6c9e7167b036b7
- [x] Double-check code for readability
- [ ] Add test coverage
  - [ ] Decide what to test and how (unit tests? feature tests?)
  - [ ] Implement the tests
  - [ ] Address any failing tests

Note: As far as readability, the linter rules should be doing the heavy lifting. Doing a refactor could be a ticket of its own.

**Comment by patphongs** [comment]
JS tests are more complicated for these widget features because the JS is loaded directly on the widget itself. It is not an exported module like all the others. Therefore, we cannot easily import these scripts into the sinon chai testing suite we have set up. Documented a new task for PI 12 innovation: https://github.com/fecgov/fec-cms/issues/3624
