### ISSUE TITLE
Feedback box missing on contribution limit archive page and on E&J chronological pages

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3661]
### Summary

Feedback box missing on contribution limit archive page and on E&J chronological index pages .

### Frequency

_an ongoing issue,_

### How to Reproduce

Visit https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/archived-contribution-limits/. The usual feedback box does not appear in the bottom right. 

Same issue appears on each page linked in the bulleted list on https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-e-j-s/. 

All of these pages are resource pages that use years for the section names. See @johnnyporkchops [comment below](https://github.com/fecgov/fec-cms/issues/3661#issuecomment-609907610) 

### Device, browser, etc

_Tell us everything you can about:_

Mac, Chrome, 
Windows, Firefox, IE, Chrome

### Screenshots

This could be the problem (thanks @pkfec)

<img width="1276" alt="Screen Shot 2020-04-06 at 11 23 04 AM" src="https://user-images.githubusercontent.com/31420082/78575616-98a91000-77f9-11ea-9d70-d0cb71c6b146.png">

### Completion Criteria
 
- [ ] Feedback box appears at the bottom right of https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/archived-contribution-limits/.
- [ ] Feedback box appears at bottom right of E&J chronological pages (linked at https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-e-j-s/)

**Comment by johnnyporkchops** [comment]
This is happening because JS throws an error because the hash symbol cannot be followed by a number in the JS context. If you go into Wagtail and add an underscore, it fixes, but a dash or period (for example) do not. The issue with that solution  is that the title now has an underscore.

 I think we need to adjust the JS to accommodate this if possible rather than force editors to adjust their titles. If need to be fixed quickly for allowing RAD to post feedback from the page, we could temporarily add some character there. @dorothyyeager I seem to remember this issue coming up before, do you?

**Comment by dorothyyeager** [comment]
No, but the E&J pages could also have this issue since their anchor links have years in them too. Definitely would be good to adjust the JS. Thanks for checking this out @johnnyporkchops
