### ISSUE TITLE
Make modifications based on OGC’s testing comments on 4/17

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3671]
### Summary

**What we're after:**
_We will receive OGC user testing comments on 4/17. We need to compile the results from the testing and apply the necessary updates to the Guidance search feature before go live. Add the must have items to the [MoSCoW Must](https://docs.google.com/document/d/1O6TzwqOKDjlhMxevfjLinyDBvn1-8-uUmj0kwHXYw1g/edit#heading=h.b54eyfifolqw) 🔒 section._

### Completion criteria

- [ ] Ensure that all items listed in the [MoSCoW Must](https://docs.google.com/document/d/1O6TzwqOKDjlhMxevfjLinyDBvn1-8-uUmj0kwHXYw1g/edit#heading=h.b54eyfifolqw) 🔒  section are completed before go live

**Comment by dorothyyeager** [comment]
Some modifications in PRs connected to #3672 may help with their feedback.

**Comment by patphongs** [comment]
Emailed search.gov today to ask about these 2 search issues:

1. The title attribute for our HTML page here: https://www.fec.gov/updates/fec-statement-on-carey-fec/ is not using the title in the HTML as the actual title in the results. It seems to be picking up the social media title tags rather than the true HTML title tag. 

2. Strange search results returned for certain terms. For example, searching “speechnow” returns some terms with “or” as part of the highlighted keywords. I don’t see why this would be as it doesn’t match any of the key term inserted.

**Comment by patphongs** [comment]
Work has been merged. Other issues above has been remediated through best bets for now.
