### ISSUE TITLE
Add fine logic (JS) into the calculator

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3688]
**What we're after:**
Add fine logic (JS) into the calculator, pairing opportunity with back-end (if needed). 

Use [documented](https://github.com/fecgov/fec-cms/issues/3413) fine formulas, with modifications to accommodate the new calculator.

**Action items:**
- @djgarr will add edge cases to this ticket (small, large and weird example)
- Make sure to compare estimated fine amounts with the feature on transition to ensure accuracy

### Completion criteria
- [ ] Calculator logic is added and works/provides results (this will be QA tested)
- [ ] Can be tested through our automated tests

**Comment by johnnyporkchops** [comment]
Possible followup work:
In PR #3273, @rfultz  wrote: 
`@johnnyporkchops suggested being able to add the calculator as a Wagtail module. mi piace. Interesting…`
Just to address this comment, (probably for another iteration as mentioned) but this would be a block that could be made available to resource, custom, legal pages for convenience, but would not remove the ability to use the straight html option. Also, since it is just straight html, it could be made into a snippet. 
Screenshot of block implementation:
![admin_fin_block](https://user-images.githubusercontent.com/5572856/81764669-1074f500-94a0-11ea-9ef0-baba1586560e.gif)
