### ISSUE TITLE
Research: Improve homepage load time (currently ~1.9 seconds)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3711]
**User story** As a first-time visitor to fec.gov, I'm more likely to give up and leave if the homepage takes more than a second to load.

We should identify easy ways to improve the homepage load time. At 1.9 seconds, Pingdom gives us a `C grade` and has an interesting report. 

Not an exclusive list of things to check:
- [ ] Compare load with caching vs no caching (hypothesis: slower with caching)
- [ ] Look at both mobile and desktop
- [ ] Look at CDN
- [x] Look at webpack
- [ ] create separate ticket to address Webpack configuration and approach as mentioned in [this comment below](https://github.com/fecgov/fec-cms/issues/3711#issuecomment-692856595)

### Pingdom
https://my.pingdom.com/app/reports/rbc/5304992

<img width="961" alt="Screen Shot 2020-04-23 at 1 47 07 PM" src="https://user-images.githubusercontent.com/31420082/80131943-fd3dcc00-8568-11ea-9c89-e332de2a0430.png">

### Google speed test 
https://developers.google.com/speed/pagespeed/insights/?url=www.fec.gov
<img width="379" alt="Screen Shot 2020-04-24 at 10 49 16 AM" src="https://user-images.githubusercontent.com/31420082/80225618-4c433a00-8619-11ea-9233-4e5ff3f6924b.png">

<img width="725" alt="Screen Shot 2020-04-24 at 10 44 18 AM" src="https://user-images.githubusercontent.com/31420082/80225097-a1328080-8618-11ea-958a-fd5dfd413424.png">

**Action item**
- [ ] break ticket into independent smaller tickets and prioritize accordingly.

**Completion criteria:**
- [ ] Quick wins are identified and followup tickets are created to address those quick wins

**Comment by johnnyporkchops** [comment]
The two data visualizations(election search and raising/spending ) that we load below-the-fold on the homepage, may be effecting performance. They are loaded via Django templatetags.
We can consider using these debug tools to evaluate:
`Django debug toolbar`: https://django-debug-toolbar.readthedocs.io/en/latest/index.html
`Template-Timings toolbar`: https://github.com/orf/django-debug-toolbar-template-timings

**Comment by johnnyporkchops** [comment]
Since I was unable to use the Django `template-timing-toolbar` to test the performance of the visualizations on the homepage, a less scientific test was to remove them and push to feature and do a Pingdom test. This change does increase load time and raises the performance grade to a B, but the small difference shows that these visualizations are not a main issue in load-speed
<img width="1127" alt="Screen Shot 2020-08-26 at 12 01 30 PM" src="https://user-images.githubusercontent.com/5572856/91328185-93426700-e794-11ea-9336-81ece0f85e05.png">

**Comment by johnnyporkchops** [comment]
The size of our compiled Javascript creates a possible opportunity or performance improvement for the homepage and other pages based on the the Google insights results. (First screenshot below) and running Webpack analyzer locally, (second screenshot below).

 Based on research using Webpack Analyzer  and previous Innovation sprint research done by @rfultz, there is no one change to `webpack.config ` that would improve performance significantly, but more granular reconfiguring may help.

**Possible `webpack` changes**
Remove unnecessary calls to scripts based on  templates and/or find a more granular way to split compiled scripts into smaller pieces to only be loaded where needed. 
      - Once we can [upgrade to Webpack 5 ](https://github.com/fecgov/fec-cms/issues/2708, ) `commonschunks plugin` functionality is built in, but we would have to reconfigure the way we are identifying entrypoints. 


**For homepage:** 
Possibly create one entrypoint for homepage that only loads what we need there (including JS for the data visualizations) 
     - Does homepage need D3? This is big portion of the dataviz common loaded there now
     - Does homepage need `Juery.dataTables.js` ? , another big portion of dataviz-common loaded there.
     -  If homeapge needs `Juery.dataTables.js`  There are two calls to  `Juery.dataTables.js` (`datatables.net-responsive` and `datatables.net.js`. Are these essentially duplicates? 
    - we could sequence load JS, CSS, Fonts, other assets after initial page load, Then load the other assets like dataviz and init later 

****For other pages****: 
 - Look at redefining entrypoints -- possibly based on templates used in /data for example
-  Point to CDNs for vendor files. Or even consider CDNs for our files. This would mean that we can take advantage of cacheing because we would not have to load a new hashed-version file for unchanging assets.



### Google Insights https://django-debug-toolbar.readthedocs.io/en/latest/index.html:
<img width="815" alt="Screen Shot 2020-09-15 at 10 28 17 AM" src="https://user-images.githubusercontent.com/5572856/93227224-26dad800-f742-11ea-9075-41926986aa90.png">

Webpack analyzer running locally (Webpack plugin):
<img width="439" alt="Screen Shot 2020-08-27 at 2 04 06 PM" src="https://user-images.githubusercontent.com/5572856/93228950-13c90780-f744-11ea-9230-8d67c9cdf5e7.png">

**Comment by rfultz** [comment]
I've created tickets based on my findings and experiments ☝️

**Comment by rfultz** [comment]
Closing this as the other tickets have been created. For the record, there's a branch of code whose name starts with `feature/3711` where I've committed different experiments and samples
