### ISSUE TITLE
Error handling for MURs that are missing documents

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3772]
**What we're after:**
To catch missing MUR documents in the future, we need to incorporate better error handling and alerting when an error occurs.

**For more details:** 
This is related to https://github.com/fecgov/openFEC/issues/4361
and https://github.com/fecgov/openFEC/issues/4364

Question:
- Do all MURs have documents

**Completion criteria:**
- [x]  Front-end should show a warning message on a MUR when there are missing documents, but the page should still load.

**Comment by patphongs** [comment]
@JonellaCulmer @dorothyyeager I need some help as to what we should show when there are no MUR documents due to a failed document loading issue in the API. This is what I have so far, could you please help to refine it?

<img width="668" alt="Screen Shot 2020-06-03 at 5 30 30 PM" src="https://user-images.githubusercontent.com/12799132/83691568-68df7400-a5c0-11ea-8955-18a5a0d7f9fa.png">

**Comment by JonellaCulmer** [comment]
@patphongs We have draft language below which is not much different from what you have there. 

We're wondering though, what kind of error has occurred? We want to be specific - server error? Internal error? Yada yada. Also, are these just for new MURs or can this happen to older MURs and the documents "disappear" and need to be fixed?

**What we have so far:**
Sorry, there was a problem loading these documents. Please try again later. 

cc: @dorothyyeager
