### ISSUE TITLE
Consider revising hard-coded text about in-person meetings on meeting page template

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3841]
### Summary

**What we are after:**
_The Commission has resumed having meetings. Due to the COVID-19 pandemic, they are being held virtually. We've got language about attending meetings in person hard-coded into the template that we may want to consider taking out for now._

### Completion criteria

- [ ] Decide whether to remove this language and remove it if that is what is decided.
- [ ] Make sure content team saves the language for future use should in-person meetings resume.

**Comment by johnnyporkchops** [comment]
My two cents:  I think web users are expecting that if something stated abut "in-person" attendance does not make sense due to Covid-19 restrictions, they would look for extra guidance message about that, which we have at the top if the page. If we change it, it is just one more thing that we have to change back, once it resumes, and if it is last-minute, we'll likely be doing a hotfix

**Comment by JonellaCulmer** [comment]
My vote is for any option that allows us to be flexible and nimble when we need to make different kinds of events, be they virtual or in-person. We're living in a new age and should be able to accommodate different unforeseen circumstances as well as those we're aware of.

**Comment by dorothyyeager** [comment]
Taking the milestone off this ticket as the Commission is once again lacking a quorum so there are no open meetings for now. We can bring this back when the quorum is restored.

**Comment by dorothyyeager** [comment]
Or better, move it to a later milestone so we don't lose it. ;) @JonellaCulmer

**Comment by patphongs** [comment]
We have a few options we can take for this. Language also still needs to be decided. @AmyKort @dorothyyeager @JonellaCulmer what are your thoughts?

## Option 1
Don't change any of the default intro text of the meeting page and only add in the "additional information" field in Wagtail that all meetings are now virtual only. We would only update applicable public open meetings with this additional text. This is the easiest option since it requires no code changes.

![Screen Shot 2021-01-04 at 1 15 56 PM](https://user-images.githubusercontent.com/12799132/103565844-0b314400-4e8f-11eb-9473-9199e8a94fd6.png)

## Option 2
Globally update the default intro text on all meeting pages (includes open meetings and public hearings) to display a new intro text about all meetings now being virtual. This would be a change through all the templates, no matter if the meeting is happening in the future or if it happened in the past. This would require a code change and possible hotfix in the future once the restriction is lifted.

![Screen Shot 2021-01-04 at 1 26 14 PM](https://user-images.githubusercontent.com/12799132/103566805-ae368d80-4e90-11eb-83a0-23b6e0e2d2e5.png)

![Screen Shot 2021-01-04 at 1 26 40 PM](https://user-images.githubusercontent.com/12799132/103566815-b1317e00-4e90-11eb-8856-114853c7a384.png)

**Comment by dorothyyeager** [comment]
My two cents: I like option 1 both for the simplicity and because that's why we made that box - for just these kinds of weird situations. I also think it's weird to have the "virtual" language on the past hearing pages especially.

**Comment by JonellaCulmer** [comment]
@patphongs Does the additional information box have fixed copy or can we change it? It sounds like option 1 is best, especially if that text can be edited depending on any given situation. Whether we have a virtual meeting, in person, canceled meeting for whatever reason, etc.

**Comment by patphongs** [comment]
> @patphongs Does the additional information box have fixed copy or can we change it?

We can change it and customize it for each meeting page. It's a plain text field in Wagtail and will by default appear on the page bolded.

**Comment by dorothyyeager** [comment]
@JonellaCulmer Here's a screencap. The field will accept html codes too.

![image](https://user-images.githubusercontent.com/24437369/103571720-65370700-4e99-11eb-83e2-35aea96efe13.png)

**Comment by patphongs** [comment]
We have decided to take option 1 and add a message on a meeting-by-meeting basis. We will be using previous drafted language "Because of the COVID-19 pandemic, we will conduct the open meeting virtually."
