### ISSUE TITLE
Unable to select 2019-2020 two year period data for Julian Castro

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3881]
### Summary

When viewing the Julian Castro's candidate profile page, you are unable to select the `2019-2020` two year transaction period, as it is grayed out.

https://www.fec.gov/data/candidate/P00009092/

![Screen Shot 2020-07-07 at 2 16 15 PM](https://user-images.githubusercontent.com/12799132/86824699-7f179e80-c05c-11ea-9f72-6a3810036056.png)

**Comment by JonellaCulmer** [comment]
This may be a new problem post the front-end change. This was the behavior that I noted prior to the explanatory text being hard-coded on the page. I think we used to be able to see the 2019-2020 slice, it was just blank.

Julian Castro's (ID: P00009092) presidential campaign committee, Julian for the Future, converted to a PAC and renamed it, People First Future (ID: C00693044)
- Julian Castro's candidate profile page still contains data from his exploratory committee.
- Users can go back to a previous cycle to see old committee information, but it's for an exploratory committee only.

**Comment by lbeaufort** [comment]
The available 2-year periods are driven by the API's `fec_cycles_in_election` data. We moved business logic to the API to only show the 2-year periods where there is data. Because there isn't financial data in 2020 for a `P` or `A` committee affiliated with the candidate, 2020 isn't selectable. This is pretty complex to address without breaking other things.

Example: https://api.open.fec.gov/v1/candidate/P00009092/history?per_page=1&api_key=DEMO_KEY
cc: @fec-jli

**Comment by JonellaCulmer** [comment]
Based on @lbeaufort's comment above, we're going to close this (for now).
