### ISSUE TITLE
Migrate the Ongoing and major Litigation pages over to Wagtail / fec.gov

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3937]
### Summary

**What we're after:**
This page needs to be moved over to Wagtail and off transition in our effort to come off of transition, as does the major litigation page and related pages. **With the news that Windows 10 won't have Contribute, we need to prioritize the migration of these pages so that Information Division can maintain them.**_

Bonus: Google Search Console is warning us that Ongoing Litigation page found at https://transition.fec.gov/law/litigation/rtao.shtml has content wider than mobile screens (and larger issues). This ticket will address this issue.

### Related issues

- #3860 - Responsiveness issue
- #3938 - Moving the court case alpha pages (the ones with A cases, B cases, C cases, etc.) 
- #4070 - Move PDF files to S3

### Completion criteria - CANDIDATE FOR SCRAPING. 
Also, Info and litigation have a workflow we will need to consider. Zainab Smith in Info is the point person for updating the transition site.
- [x] Pair with information division
- [x] All pages now linked in ongoing litigation on https://www.fec.gov/legal-resources/court-cases/#ongoing-litigation are migrated to Wagtail
- [x] Index pages are either migrated or redirected as needed.
  - Pages to consider:
https://transition.fec.gov/law/litigationrecent.shtml - does it need to be migrated? Or redirected to https://www.fec.gov/legal-resources/court-cases/#ongoing-litigation?
https://transition.fec.gov/law/litigationmajor.shtml - should it be migrated? or redirected to https://www.fec.gov/legal-resources/court-cases/#selected-court-cases?
https://transition.fec.gov/law/litigation_related.shtml - Looks like a duplicate page we no longer need. Should it be redirected to main Court case landing page?

- [x] Links on Court case landing page are updated.
- [x] ~Info Division will be able to continue to update pages using Wagtail (note: The Info staff who updates knows HTML basics.)~

### Future work
Migrating the PDF files in #4070

**Comment by patphongs** [comment]
Redirects for the following have been added and will be deployed and those pages will be deleted soon:
- https://transition.fec.gov/law/litigationrecent.shtml can be deleted and redirected to https://www.fec.gov/legal-resources/court-cases/#ongoing-litigation
- https://transition.fec.gov/law/litigationmajor.shtml can be deleted and redirected to https://www.fec.gov/legal-resources/court-cases/#selected-court-cases

More work to be done:
- https://transition.fec.gov/law/litigation_related.shtml this page is a major component of the alpha court case index page (see third column in table): https://transition.fec.gov/law/litigation_CCA_Alpha.shtml. We'll want to put that content with the appropriate related court case so that we can eventually delete this related page.

**Comment by jason-upchurch** [comment]
@patphongs  I moved this to innovation sprint in preparation for the next iteration. Please let me know if I need to reprioritize it--thank you!

**Comment by patphongs** [comment]
We cannot update the links to the ongoing and major litigation section of the wagtail CMS page until the court case pages are scraped and migrated over. I will put this in blocked for now.

**Comment by patphongs** [comment]
This has been updated
