### ISSUE TITLE
Move the court case alpha list index page

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3938]
### Summary

**What we're after:**
In addition, these pages (there are many) and related PDF files need to be moved over to Wagtail and off transition in our effort to come off of transition. This needs prioritization because Windows 10 will not support Contribute, which is the current updating tool for these pages.

Related documents have also been moved to their respective court case summary sections. Therefore, we can also remove the related documents column for the alpha page

Bonus: Google Search Console is warning us that the court case alpha page found at https://transition.fec.gov/law/litigation_CCA_Alpha.shtml has content wider than mobile screens (and larger issues). So this migration will solve this problem.

### Related issues

#3860 - Mobile responsiveness issue 
#4070  - Moving the PDFs

### Completion criteria - CANDIDATE FOR SCRAPING.
Also, Info and litigation have a workflow we will need to consider. Zainab Smith in Info is the point person for updating the transition site.

- [x] Pages now linked at https://transition.fec.gov/law/litigation_CCA_Alpha.shtml are migrated to Wagtail (note that this involves many pages - see directory at law/litigation/ and all files with CCA in the name
- [x] Remove related documents column from the alpha landing page
- [x] Button link on Court case landing page is updated.
- [x] Info Division will be able to continue to update pages using Wagtail (note: The Info staff who updates knows HTML basics.)

### Future work
#4070 - Move the PDFs to S3

**Comment by dorothyyeager** [comment]
How does this fit in with plans to scrape the court cases?

**Comment by kathycarothers** [comment]
We need to talk about this one. Let me know when you have time. I can explain the background and we can go from there @dorothyyeager.

**Comment by kathycarothers** [comment]
@AmyKort and content team discussed scraping these a few years ago, but there were some blockers. Will want to tackle this in the smartest way because it is huge amount of content.

**Comment by jason-upchurch** [comment]
@patphongs I moved this to innovation sprint in preparation for the next iteration. Please let me know if I need to reprioritize it--thank you!

**Comment by patphongs** [comment]
@JonellaCulmer Since this page will be a long scrolling page, I've incorporated a "Back to alphabetical index menu" after each table so that a user can click on that to go back to the top where the alphabetical menu is. What do you think about that idea? It basically preserves similar functionality to the transition page where there is a "top of page" link after each table to return users back to the top. https://transition.fec.gov/law/litigation_CCA_Alpha.shtml

**Comment by JonellaCulmer** [comment]
@patphongs I think this is fine. This page is so unfortunately long, but we can't do anything about that yet. In the meantime, the links will help with navigation. Can the language say "Back to top"?

**Comment by patphongs** [comment]
> @patphongs I think this is fine. This page is so unfortunately long, but we can't do anything about that yet. In the meantime, the links will help with navigation. Can the anchor links say "Back to top"?

Thanks @JonellaCulmer, I was thinking about changing the functionality slightly where I would link them back to the alphabetical table towards the top, rather than to the very top of the page. Since I thought this would be more useful to allow them to navigate the page. This is why I was trying to be a little more semantic in my naming of the link: "Back to alphabetical index menu". But if you think it's better to keep the functionality to just bring them back to the top of the content, I can change the link text to "back to top".

**Comment by zsmith-fec** [comment]
May I add my two cents? 

I agree w/Jonella that "Back to top" might be more useful. "Back to alpha index" might not make sense if the user isn't starting from there. (Related question: will the alpha index be linked on each page as it is now (at the top)?)

Btw, there shouldn't be too many of these super long pages. I know they are clunky. These are cases that lasted many, many years.

**Comment by JonellaCulmer** [comment]
@patphongs Do you have a screenshot of what it will look like on the new page? 

"Back to top" or "Return to top" or just "Top/Up" are more commonly used and would be considered best practice. Also, if the alphabetical index (by that I'm assuming you mean all the letters to choose from), is near to the top it could mean the same thing. 

cc: @zsmith-fec

**Comment by patphongs** [comment]
@JonellaCulmer @zsmith-fec I just finished up the prototype of what the alpha index looks like: [Court case alphabetical index](https://fec-feature-cms.app.cloud.gov/legal-resources/court-cases/court-case-alphabetical-index/). I've updated it so that the link between each table says "Back to top" and it will go to the beginning of the content, right below the title (that's as high in the page I can get it). Take a look around and let me know what you think. 

Also @johnnyporkchops, I've replaced the links on the prototype [Court case alphabetical index](https://fec-feature-cms.app.cloud.gov/legal-resources/court-cases/court-case-alphabetical-index/) page using the hash to slug and url to slug generated files that you made and it's working well! I believe you only tested inserting the individual court case pages onto feature right now, so not all the links work, but I would like to test putting all of the alpha index pages onto feature. Then we can run a link checker on the alpha index page to make sure things are linking ok.

**Comment by zsmith-fec** [comment]
@patphongs The prototype is lovely! Things are coming together nicely. :)

A couple of thoughts: 
--after the scrape, we'll have to remove the reference to "related documents" at the top of the index as it will no longer be relevant. We'll have these docs on dedicated pages. 
--I'm also noticing some inconsistent formatting. I think some of it may be in the chart, which I can clean up now, if you'd like. But I also notice extra bullets. Not sure why this is happening. @JonellaCulmer would this be fixed in design?

**Comment by patphongs** [comment]
@zsmith-fec Thank you for checking the page! I'll look through the formatting font issues and will let you know when I'm done so you can do another check. Could you help to prune and clean up the text at the top of the tables? You can put your edited text directly in this github ticket and I can take those edits and make changes in the prototype.

**Comment by zsmith-fec** [comment]
FEC court cases are listed alphabetically by non-FEC litigant. Each case is linked to a summary, and in some instances, court opinions and documents pertaining to the case.

The PDF files on this web site may be viewed or printed using the Adobe® Acrobat® Reader available from Adobe, Inc.

****
Related items

Main litigation page

Ongoing litigation
Lists active litigation involving the FEC. Each case listed has a dedicated page including a case summary, as well as links to court opinions and related documents filed in the suit.

Selected campaign finance court cases
Identifies key court cases relating to the campaign finance law.

**Comment by patphongs** [comment]
[Cleaned up HTML](https://drive.google.com/file/d/1ycJYfSzb9eIgitkJOoQceVn7TelxmPwZ/view) 🔒 with updated links has been completed. We can put this HTML onto the new Wagtail Court case alpha index page after the scraping and inserts are done.

**Comment by patphongs** [comment]
New alphabetical index page is now live and this page has been updated to link to it: https://www.fec.gov/legal-resources/court-cases/#alphabetical-court-case-index
