### ISSUE TITLE
[November] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#4140]
Summary
What we're after:
We need to update the global search.gov index for new pages that were published in November

Related issues
#4046 

Completion criteria

- [ ] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [ ] Create ticket for December manual wagtail global search index

**Comment by patphongs** [comment]
Last indexed page count: 906 (indexed on 10/22/2020)
New indexed page count: 1384 (indexed on 12/01/2020)

Created new ticket to scrape and index the pages for November https://github.com/fecgov/fec-cms/issues/4223

**Note:** After the court case pages were inserted into Wagtail, there are two page IDs that are error when running the search CMS scraper: 11391 and 11445. In order to get the scraper to run smoothly, I had to locally delete these two IDs from my local database and run the scraper. We should see about either deleting these IDs altogether or making them not live so that the scraper will automatically ignore it. Bug issue logged here: https://github.com/fecgov/fec-cms/issues/4226

**Comment by patphongs** [comment]
Since this scrape was done on December 1st, I decided to just have another scrape in January instead for the follow up ticket: #4223
