### ISSUE TITLE
Modify resource template to accommodate court cases

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4191]
**What we're after:**
To improve the usability of the court case pages, we need to update the resource template. 

### Related issues
- https://github.com/fecgov/fec-cms/issues/4133 Design court case wagtail page template

### Action items / requirements for completion
- [ ] Adjust "hide title checkbox" to remove the line above the section title, not the entire title
- [ ] Field for italicizing court cases in the title is added (like we have for press releases and Record articles)--
![image](https://user-images.githubusercontent.com/24437369/99586399-af315f80-29b5-11eb-84bb-58e39d80a89d.png)

### Completion criteria
- [ ] Court case names can be italicized in page header
- [ ] Line above section headers is removed if there is no intro text to avoid double-line appearance

**Comment by patphongs** [comment]
@JonellaCulmer We're not using the Page number column anymore correct? The individual court case pages do not appear to cite the number of pages. And we also received agreement to remove page numbers from the individual audit page documents table, so we no longer need page numbers at all?

**Comment by patphongs** [comment]
@JonellaCulmer Also, I don't think the initial implementation will include the sort functionality. The different offices who use this documents table may want to order the documents in a specific way.

**Comment by JonellaCulmer** [comment]
@patphongs Yes, that all makes sense to me. We've more or less moved away from providing page numbers on Wagtail pages. We do, however, still provide them for filings on committee and candidate profile pages. 

The sort functionality would be beneficial for individual who want to view the data in a different way. Are we able to have a default view, that individual offices can dictate and if a user wants to sort we can afford them that option?

**Comment by johnnyporkchops** [comment]
Given issues with ResoourcePage template on the new Wagtail upgrade, this work may be blocked until that is resolved
https://github.com/fecgov/fec-cms/issues/4529

**Comment by johnnyporkchops** [comment]
There is a Wagtail wishlist item to control the column widths on the document tables on these pages.  We could create a new custom table block that gives user the ability to choose table-layout of fixes or auto which would accommodate that, and tables could be copied and pasted from the existing to new in Wagtail. See https://github.com/fecgov/fec-cms/issues/4258#issuecomment-998420749

This is a short term solution just to the width formatting, that does not address the broader issue of reformatting tables entirely ere https://github.com/fecgov/fec-cms/issues/4553
Since this issue is going to be a big lift and may not et implemented for quite some time, we can decide if its worth the effort  to make the basic change to the width-formatting  in the short term.
