### ISSUE TITLE
Investigate why some redirects from 13.7 aren't working

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4217]
### Summary

**What we are after:**
_Some of our redirects aren't working so we need to fix that._

### Related issues

#4124 

### Completion criteria

Fix the redirects for these files:
- [x] Add ~broader redirect for /eeo/(.*)  is needed to~ redirect for .shtml files in that directory (We have one for PDFs)
- [x] https://transition.fec.gov/pdf/firsttenyears.pdf is giving a forbidden error when redirecting to https://www.fec.gov/resources/cms-content/documents/firsttenyears.pdf
- [x] https://www.fec.gov/pdf/firsttenyears.pdf is giving a 404 error.

**Comment by patphongs** [comment]
@dorothyyeager @kathycarothers We can't make a broad redirect for the eeo `.shtml` pages because there's no pattern to be able to match a transition page to its Wagtail EEO counter part. But good news is that there isn't too many `.shtml` pages within eeo, below is the full list of pages that don't have transition redirects currently. Can you let me know where each of these should redirect? I can tack it onto my PR for this issue: https://github.com/fecgov/fec-proxy/pull/214

https://transition.fec.gov/eeo/AfricanHistoryMonth.shtml
https://transition.fec.gov/eeo/eeocounselors.htm
https://transition.fec.gov/eeo/EEOCounselors.shtml
https://transition.fec.gov/eeo/HispanicHeritageMonth.shtml
https://transition.fec.gov/eeo/LegalAuth.shtml
https://transition.fec.gov/eeo/MD-715Report.shtml
https://transition.fec.gov/eeo/NoFear.shtml

**Comment by dorothyyeager** [comment]
@patphongs All of those can just redirect to the main EEO page at https://www.fec.gov/about/equal-employment-opportunity/ except for No Fear which should redirect to https://www.fec.gov/about/no-fear-act/
