### ISSUE TITLE
[Security: Low] Buffer Overflow (Due: 6/2/2021)

### ISSUE THREAD

**Issue by hcaofec** [fecgov/fec-cms#4307]
Vulnerable module:  Pillow
Introduced through: pillow@7.1.0 and wagtail@2.7.4
Exploit maturity: No known exploit
Fixed in: 8.1.0

**Detailed paths and remediation**
Introduced through: project@0.0.0 › pillow@7.1.0
Remediation: Upgrade Pillow to version 8.1.0
Introduced through: project@0.0.0 › wagtail@2.7.4 › Pillow@7.1.0
Remediation: Pin Pillow to version 8.1.0

**Overview**
Pillow is a PIL (Python Imaging Library) fork.

Affected versions of this package are vulnerable to Buffer Overflow. There is a 4 byte read overflow in SGIRleDecode.c, where the code is not correctly checking the offsets and length tables.

More:  https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1055462

**Comment by patphongs** [comment]
This package does not cause a significant external security vulnerability since only approved and authenticated Wagtail users can upload resources to our system. We plan to patch this package when we upgrade our [Wagtail version to the latest 2.11 LTS](https://github.com/fecgov/fec-cms/issues/4384).

**Comment by patphongs** [comment]
Added dependency for [Wagtail upgrade](https://github.com/fecgov/fec-cms/issues/4384).

**Comment by patphongs** [comment]
No longer flagged
