### ISSUE TITLE
[Snyk: Low] Pillow Regular Expression Denial of Service (ReDoS) (6/2/21)

### ISSUE THREAD

**Issue by hcaofec** [fecgov/fec-cms#4444]
@hcaofec commented on [Wed Mar 03 2021](https://github.com/fecgov/openFEC/issues/4789)

Introduced through: pillow@7.1.0 and wagtail@2.7.4
Exploit maturity: NO KNOWN EXPLOIT

Detailed paths:
Introduced through: project@0.0.0 › pillow@7.1.0
Remediation: No remediation path available.
Introduced through: project@0.0.0 › wagtail@2.7.4 › Pillow@7.1.0
Remediation: No remediation path available.
Overview
Pillow is a PIL (Python Imaging Library) fork.

Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) via next_object_id.

More info:
https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1080654

**Comment by patphongs** [comment]
This package does not cause a significant external security vulnerability since only approved and authenticated Wagtail users can upload resources to our system. We plan to patch this package when we upgrade our [Wagtail version to the latest 2.11 LTS](https://github.com/fecgov/fec-cms/issues/4384).

**Comment by patphongs** [comment]
No longer flagged, closing
