### ISSUE TITLE
Change "contributor" to "source" for receipts datatable and browse data page

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#4513]
### Summary

**What we're after:**
Not all receipts are from contributors. We need a different term to more generically describe money coming in. We do **not** need to make this change to the individual contributions search page/data table. 

![image](https://user-images.githubusercontent.com/11817734/112511522-dd122080-8d68-11eb-94b5-7ec120bc9ce9.png)

![image](https://user-images.githubusercontent.com/11817734/112511636-fca94900-8d68-11eb-99c2-8f6f34697ee2.png)

![image](https://user-images.githubusercontent.com/11817734/112511765-1cd90800-8d69-11eb-9e8a-838e68d27e3b.png)

### Action items
- [x] Use language decided on in this [ticket](https://github.com/fecgov/fec-cms/issues/4527) **We'll sub "Source" for "Contributor"**
- [x] update `Search candidate and committee receipt data by contributor, amount and date.` on https://www.fec.gov/data/browse-data/?tab=raising
- [x] update `contributor` on the data table and its filters on https://www.fec.gov/data/receipts/

### Completion criteria
- [ ] The term "contributor" is updated in the all receipts datatable
- [ ] Individual contributions datatable remains unchanged

**Comment by JonellaCulmer** [comment]
Does this panel also need to change?
<img width="629" alt="Screen Shot 2021-03-25 at 6 06 52 PM" src="https://user-images.githubusercontent.com/31663028/112549917-f16c1280-8d94-11eb-9226-835a2ad6d49d.png">

**Comment by PaulClark2** [comment]
@JonellaCulmer yes it does. Thank you for catching that.

**Comment by dorothyyeager** [comment]
We need to update this page too: https://www.fec.gov/data/browse-data/?tab=raising

![image](https://user-images.githubusercontent.com/24437369/124939136-deddb800-dfd6-11eb-968b-f61d299f79ab.png)

**Comment by bmathesonFEC** [comment]
Hey @JonellaCulmer, @dorothyyeager, I agree that both of these references to "contributor" needs to be changed to be consistent with the change on the filters:

-------

For this section I think we can go in one of two ways:

First we could eliminate one of the headings and just use _Receipt information_ at the top to replace _Contributor information_ and _Contribution information._ That would leave two headings _Receipt information_ and _Recipient information_

Alternatively, we could keep two headings and rename both of these. This is my suggestion:
 1.  Contributor information -> Source information
2.  Contribution information -> Receipt information

![image](https://user-images.githubusercontent.com/33758291/129130069-d0ea071c-d6e1-4c44-9f16-712b53a2b4c4.png)

-------

For this section, I think we could just say "name." We don't have to be hyper specific here because we're not labeling a filter or a data field. If you think we should get more specific and say "source name" here.

![image](https://user-images.githubusercontent.com/24437369/124939136-deddb800-dfd6-11eb-968b-f61d299f79ab.png)

-------
