### ISSUE TITLE
Make the Pre-Election and additional reporting date charts sortable

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4581]
### Summary

Updating the Pre-Election and additional reporting date charts for more sortability.

On the current (or as of 2020 pre-election and 2021 special election) charts, the only way to filter the chart is to choose a state from a drop down menu. The goal was to see if there was a way to sort the table chronologically as well (Public Records produces a PDF demonstrating the alphabetical and chronological reporting dates (https://www.fec.gov/resources/cms-content/documents/2020pdates.pdf)). This applies to the Congressional pre-election report table, as well as the coordinated communication, electioneering communication, federal election activity, and independent expenditure reporting tables.

![image](https://user-images.githubusercontent.com/40633757/116611938-ef055700-a904-11eb-9ca6-1d0bddf4d2dd.png)

### Completion criteria

- [ ] Create sortability on both election date and state for election tables 
- [ ] Test extra carefully - it's very important not to scramble the data

**Comment by johnnyporkchops** [comment]
While it's possible to add sort to a basic table with JS, the existence of the hidden footnote rows makes adds a layer off complexity making this very complicated, if not impossible. Given the complications involved, I think it's worth evaluating the priority for implementing this before trying to move forward.

**Comment by johnnyporkchops** [comment]
Created two partially working prototypes for the the Congressional Pre-Reporting table but these are still not complete and only apply to that one table on a  FullWidth page. The issue author, @djgarr has said that this feature is a nice-to-have and nor a must-have so we agreed to shelve this work for now. 
The possible approaches, for future reference, are to 
 1)  Move export reporting-dates-tables.js as a module and include jQuery datatables node-module via a require variable. Then apply datatables to the table in the script and enable its sorting functionality. (this one also requires making the footnotes to be added on click instead of when the table loads so that there are no colspans that confuse Jq Datatables sorting functionality on-load)
 
        ```
        var $ = require('jquery');
        require('datatables.net');
        require('datatables.net-responsive');
        var moment = require('moment');

         ...

         $(this.dates_table).DataTable( { ....
   
         ```
   
 2. Use a native JS table sort function. Will likely this one also requires making the footnotes to be added on click instead of when the table loads so that there are no colspans that confuse Jq Datatables sorting functionality on-load)
