### ISSUE TITLE
Resource page templates not showing "Page title" information

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4797]
### Summary

Pages created on the resource template do not show all the information added to the "Page title" section of the "Promote" tab like custom and other pages. For example, on https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/

![image](https://user-images.githubusercontent.com/40633757/127181828-455e41d1-f8fb-462a-94e3-ffab2e7cc67d.png)

Although the information was entered in Wagail

![image](https://user-images.githubusercontent.com/40633757/127181920-8db90663-17d1-47ba-9488-094d12656ed0.png)

### Completion criteria

- [ ] Update page title information for resource pages to be consistent with other implementations

**Comment by rfultz** [comment]
@djgarr, do we want to look at `og:title` and `twitter:title`, too? (`og:title` is what Facebook, Slack, Google, etc use)

As a reminder, page titles appear in browser histories, bookmarks, and search engines but only the first 50-75 characters are displayed, basically anywhere.

### HTML Title Elements
Looks like the html templates use
`<title>{% block title %}{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }} | FEC {% endif %}{% endblock %}{% block title_suffix %}{% endblock %}</title>`

but the Jinja templates use
`<title>{% block title %}{% endblock %} | FEC </title>`

So the html templates' logic is:
- The title block content
- (space)
- the seo_title block if it exists otherwise the title field content
- " | FEC "
- the value of title_suffix (though I can't find where title_suffix is defined)

The Jinja templates':
- The title block followed by ` | FEC`

### Social Media Titles

`og:title` and `twitter:title` html logic is `{{ self.title }} - FEC.gov`
`og:title` and `twitter:title` jinja logic is `{{ title }} - FEC.gov`

**Comment by djgarr** [comment]
@rfultz Ideally, it should mirror the other page products, like custom pages, etc.
