### ISSUE TITLE
Design updates for committee profile pages to add filing frequency and "registration date"

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4826]
**What we're after:**
We would like to add additional clarity to committee profiles pages and display:
- Filing frequency
- "Registration date" (consider what we call this date in a few places across the site

This work should likely exclude form 5, 7, and 9 filers. Good pairing opportunity with content team.

**Related issues:**
- https://github.com/fecgov/openFEC/issues/4928 

### Completion criteria
- [ ] Mockups for committee profile pages is reviewed and approved by PMs

**Comment by JonellaCulmer** [comment]
@dorothyyeager @PaulClark2 @lbeaufort I wanted to get your thoughts on the "Registration date" label for this work. As far as the data is concerned I believe we're going with the first form 1 date, correct? If I'm wrong, please correct me. But saying that is much too long. I'd like to use as few characters as possible. 

Options: 
- Registration date
- First filing date
- Form 1 filing date
- Other alternatives?

**Comment by dorothyyeager** [comment]
My thoughts. From a legal standpoint, the instructions for Form 1 tell committees to put the "date the committee became a political committee." That date is determined differently for different types of committees. Many of the committees that have financial thresholds that determine whether they are a political committee actually file before they are required to. For that reason, I'd encourage you to call it "Registration date" or "First Form 1 filing date."

On your filing frequency question, I am not sure about the data, but quarterly filing PACs and party committees are generally referred to as "quarterly filers" even during the year when they file semi-annually. When I worked in Info Div, I did see that callers and workshop attendees could be confused by that labeling, so I agree with you that it might need some explanation.

**Comment by PaulClark2** [comment]
Thanks @dorothyyeager @JonellaCulmer . My preference is "registration date."  I'm confirming something about filing frequency. When I get the additional information I need, I'll post another comment.

**Comment by PaulClark2** [comment]
@JonellaCulmer PACs that file quarterly during election years automatically switch to a semi-annual reporting schedule during non-election years. The PACs are not required to notify the FEC they will file semi-annually. The PAC remains a quarterly filer. 

PACs that file monthly during election years can choose to switch to quarterly filers in the non-election year. They will follow the semi-annual reporting schedule. In this scenario PACs need to notify the FEC about the filing frequency change.

In the filing frequency data, there is no code for semi-annual filer. They are quarterly filers. We might need an information icon or something else to explain this to folks.

**Comment by JonellaCulmer** [comment]
@PaulClark2 @dorothyyeager Preliminary mockups using "registration date". I made both of these using the browser inspector. Based on length, this will likely wrap in a lot of cases.  

![Screen Shot 2021-08-19 at 2 33 07 PM](https://user-images.githubusercontent.com/31663028/130125222-8a573b61-5eae-4433-bb29-03de8c26986f.png)
![Screen Shot 2021-08-19 at 2 34 11 PM](https://user-images.githubusercontent.com/31663028/130125223-d14a5ff7-6300-4dc9-8ec5-c487eff3865c.png)

**Comment by dorothyyeager** [comment]
@JonellaCulmer I like that.

**Comment by PaulClark2** [comment]
Thanks, @JonellaCulmer. I like both of them. I like the date spelled out a little better, but I will defer to you since space is an issue. Looking at all the descriptors/labels we use below the committee name it looks like an administratively terminated nonqualified hybrid PAC registered in September would have the longest set of descriptors. 

Filing lable	|	Length
----	|	----
ADMINISTRATIVELY TERMINATED	|	27
ACTIVE - QUARTERLY FILER	|	24
ACTIVE - MONTHLY FILER	|	22
TERMINATED	|	10


Committee type lable	|	Length
----	|	----
PAC WITH NON-CONTRIBUTION ACCOUNT - NONQUALIFIED	|	48
CORPORATION W/O CAPITAL STOCK PAC - NONQUALIFIED	|	48
PAC WITH NON-CONTRIBUTION ACCOUNT - QUALIFIED	|	45
CORPORATION W/O CAPITAL STOCK PAC - QUALIFIED	|	45
MEMBERSHIP ORGANIZATION PAC - NONQUALIFIED	|	42
SUPER PAC (INDEPENDENT EXPENDITURE-ONLY) 	|	40
SINGLE CANDIDATE INDEPENDENT EXPENDITURE	|	40
MEMBERSHIP ORGANIZATION PAC - QUALIFIED	|	39
LABOR ORGANIZATION PAC - NONQUALIFIED	|	37
TRADE ASSOCIATION PAC - NONQUALIFIED	|	36
LABOR ORGANIZATION PAC - QUALIFIED	|	34
TRADE ASSOCIATION PAC - QUALIFIED	|	33
CORPORATION PAC - NONQUALIFIED	|	30
COOPERATIVE PAC - NONQUALIFIED	|	30
CORPORATION PAC - QUALIFIED	|	27
COOPERATIVE PAC - QUALIFIED	|	27
PAC - NONQUALIFIED	|	18
PAC - QUALIFIED	|	15


Form 1 lable	|	Length
----	|	----
REGISTRATION DATE: SEPTEMBER 22, 2022	|	37
REGISTRATION DATE: FEBRUARY 22, 2022	|	36
REGISTRATION DATE: NOVEMBER 22, 2022	|	36
REGISTRATION DATE: DECEMBER 22, 2022	|	36
REGISTRATION DATE: JANUARY 22, 2022	|	35
REGISTRATION DATE: OCTOBER 22, 2022	|	35
REGISTRATION DATE: AUGUST 22, 2022	|	34
REGISTRATION DATE: MARCH 22, 2022	|	33
REGISTRATION DATE: APRIL 22, 2022	|	33
REGISTRATION DATE: JUNE 22, 2022	|	32
REGISTRATION DATE: JULY 22, 2022	|	32
REGISTRATION DATE: MAY 22, 2022	|	31
REGISTRATION DATE: 12/31/2022	|	29

**Comment by dorothyyeager** [comment]
Thanks @PaulClark2, that's helpful to see it broken out like you did in those charts. Given how long the names of some committees can be, I guess having the date in number form works best, but I'm good either way.

**Comment by JonellaCulmer** [comment]
@PaulClark2 That's amazing, thank you! 

I found an administratively terminated nonqualified hybrid PAC and gave it the September 22, 2022 registration date. It JUST fits when the page is at full width. While we usually use the number form of dates, I think it spelled out in this one instance brings a little more gravity to it. For now I'll say let's go with it spelled out, unless front-end finds blockers with spelling it out. 

Longest:
![Screen Shot 2021-08-20 at 9 28 23 AM](https://user-images.githubusercontent.com/31663028/130240902-e3c8a79c-c3e9-43ec-8daf-ddb5510c6ee9.png)


Shortest:
![Screen Shot 2021-08-20 at 10 04 21 AM](https://user-images.githubusercontent.com/31663028/130245519-4e4fa569-ecd1-4c8e-a763-e6f6595e9298.png)

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/4827
