### ISSUE TITLE
Design new UI component for highlighting new features

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4877]
**What we're after:**
To help showcase new features, we should design a component that highlights those features. 

**Completion criteria:**
- [x] New component is drafted and reviewed by team/PMs
- [x] Followup implementation ticket to add to pattern library is created
- [x] Followup implementation ticket to identify places to add the feature is created

**Comment by JonellaCulmer** [comment]
Here are some preliminary options in different colors and how they might be displayed on the website. Would like front-end feedback on how the placement might work, specifically on datatable filter panels. I believe we are limited in our placement there. 

I'm leaning towards the versions with full-color shapes with white text and icons. 

![Screen Shot 2021-12-03 at 3 53 57 PM](https://user-images.githubusercontent.com/31663028/144671810-5fec7a22-0be7-4b74-9d1b-fcb107d80b2c.png)
![Screen Shot 2021-12-03 at 3 54 12 PM](https://user-images.githubusercontent.com/31663028/144671812-cc9d151b-3521-43d9-b2e9-d0cfeb952b38.png)
![Screen Shot 2021-12-03 at 3 54 20 PM](https://user-images.githubusercontent.com/31663028/144671813-6aa64f79-e5ca-405e-b881-f3a8cd9ae87e.png)
![Screen Shot 2021-12-03 at 3 54 33 PM](https://user-images.githubusercontent.com/31663028/144671815-c402dd75-07f0-4de6-8d51-05686e140cbb.png)
![Screen Shot 2021-12-03 at 3 54 46 PM](https://user-images.githubusercontent.com/31663028/144671816-8b696a56-5596-48c4-ab0b-559a3e593158.png)
![Screen Shot 2021-12-03 at 3 55 12 PM](https://user-images.githubusercontent.com/31663028/144671818-a784c309-27b0-4a25-8558-555bc2807765.png)

**Comment by patphongs** [comment]
@JonellaCulmer I like where you're going with this. A few things to consider with the design:

1. The dot indicator where the bell is indicates to me that there's something new that I haven't seen yet. What happens when I click on the indicator? Will it take me to a place that shows me what's new? 
2. Once a user clicks to see what's new though, would that dot go away? If it's personalized in that way, we may need to use some kind of cookie for that.
3. I'd like to make you aware of some of the technical complexities of this icon. In order to make these icons inline with the text, we'd attach a `t-inline-block` class to it. But the only problem is when the text wraps, like in a datatable label, we need to make it `t-inline` so that the icon doesn't jut out. That consequently makes the line heights larger due to the icon size. We'd have to play around with the positioning if we want it to act differently, but I'm not sure what that looks like yet. cc @johnnyporkchops @rfultz 

#### `t-inline`
![Screen Shot 2021-12-07 at 11 38 11 AM](https://user-images.githubusercontent.com/12799132/145069878-f7b54dbc-e13e-498d-94d1-7da08360376c.png)

#### `t-inline-block`
![Screen Shot 2021-12-07 at 11 35 42 AM](https://user-images.githubusercontent.com/12799132/145069880-97a635ec-29ee-4694-83ce-147c0652da5e.png)

**Comment by rfultz** [comment]
Yes to all of the CSS concerns!

Not a fan of the red options because of the alert/error/warning usage of red on the web. Incorrect form field, red. Can't submit order, red. Must agree to whatever, red. Service interruption, red.

I kinda like the idea of using only the bell for smaller devices and expanding to show the word on user taps, but then what if that triggers a line break, like if the bell fits nicely on the right side of the text but the text would make the icon too wide and then need to wrap. Never easy.

Customizing the 'new!' alerts per user would be super tricky and would _require_ cookies and/or GTM. How many times do we show an alert? For how long? If someone loads a page but immediately has to reload, would the 'new' alert go away? Would new visitors see every notice? Returning user after six months, would they see every new feature for the last half year? Would users who block or clear cookies & storage see everything new every visit or nothing new ever? But if we add something new to a template page (like a committee page), seeing an alert on every committee page for a sprint or two could get super annoying

**Comment by JonellaCulmer** [comment]
@patphongs @rfultz Thanks for your feedback. Based on your comments, I modified the layout a bit and removed the "new" circle indicator. 

This could now just link to the "what's new" page without explaining that new stuff has appeared. Alternatively, if we still want the indicator, we can just leave it up for a week and take it down, but we'd be constantly changing it every time we have a release. Doesn't seem workable at this point and removing seems the easiest course.
<img width="875" alt="Screen Shot 2021-12-08 at 9 54 19 AM" src="https://user-images.githubusercontent.com/31663028/145236574-44a22ad4-7c12-48c1-ba59-676cdefbdd98.png">

For the layout CSS challengs, I rearranged the placement. Do you think this will resolve some of the issues surrounding the inline
<img width="357" alt="Screen Shot 2021-12-08 at 9 54 26 AM" src="https://user-images.githubusercontent.com/31663028/145283662-c2856117-9d96-4f84-9e85-587c8e52ee98.png">

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , I am generally in agreement  with what's been said above. My vote is for orange, seems like red and green should be  reserved for error/success type messages. And for  some reason, green  makes me think it would  be clickable.

**Comment by JonellaCulmer** [comment]
Final designs:
![Screen Shot 2021-12-16 at 11 06 43 AM](https://user-images.githubusercontent.com/31663028/146407210-00d62a4a-66e8-497e-a139-884b00826db1.png)
![Screen Shot 2021-12-16 at 11 07 01 AM](https://user-images.githubusercontent.com/31663028/146407212-f11a2e2a-55e4-4064-a25e-0fde5a40f21c.png)
![Screen Shot 2021-12-16 at 11 08 07 AM](https://user-images.githubusercontent.com/31663028/146407214-6619b3ef-3d43-4ee9-b049-6fe63970faf2.png)
![Screen Shot 2021-12-16 at 11 08 22 AM](https://user-images.githubusercontent.com/31663028/146407215-9974b1b6-f2eb-4171-8ad5-452c023ff14d.png)
![Screen Shot 2021-12-16 at 11 08 45 AM](https://user-images.githubusercontent.com/31663028/146407216-b0b5557d-3fdf-4569-8279-ae55467f4c59.png)

**Comment by JonellaCulmer** [comment]
Closing in favor of the followup tasks:
- https://github.com/fecgov/fec-cms/issues/4996
