### ISSUE TITLE
Contributions across time: Identify packages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5031]
**What we're after:**
In order to begin implementation of the contributions across time visualization, we need to identify which packages will be required. 

**Considerations:**
- Do we need to model after widgets?

**Completion criteria:**
- [x] Necessary packages are identified and documented

**Comment by rfultz** [comment]
We could borrow some of the same functionality as Aggregate Totals but there are no real packages involved—it's just a small custom piece with a fetch and then animates native html elements' values are appearance. (i.e. there is no React, Vue, etc)

I'd like to have the values available in-page for SEO etc and then update them as needed but the effort could be higher than the value.

Thinking about semantic elements, they're all technically <figures> but are more about the data than the visual presentation. i.e. the data is the reason for the chart, as opposed to text describing a visual.

A quick option:
```
<figure>
  <h1>$549,388,810 <span> raised by House candidates</span></h1>
  <ul>
    <li><label>Dem. <meter value="281110383">$281,110,383</meter></label></li>
    <li><label>Rep. <meter value="267900102">$267,900,102</meter></label></li>
    <li><label>Other <meter value="378315">$378,315</meter></label></li>
  </ul>
</figure>
```
or
```
<figure>
  <h1>Individual contributions</h1>
  <ul>
    <li><label><time>2021-2022</time> <meter value="544949075">$544,949,075</meter></label></li>
    <li><label><time>2019-2020</time> <meter value="1956852873">$1,956,952,873</meter></label></li>
    <li><label><time>2017-2018</time> <meter value="1709530535">$1,709,530,535</meter></label></li>
  </ul>
</figure>
```

@JonellaCulmer for the contributions over time, should the max value for all three sections be the max of all nine values displayed? The comps uses three sets of three values, except Individual Contributions will basically always be the largest; will Transfers and Other be graphed to the same scale? What if it winds up being something like this every time?

**Individual Contributions**
█████████████████████████
██████████████████████████████
████████████████████████████
**Transfers**
❙❙❙
❙❙
❙
**Other**
❙
❙
❙

Would it be confusing like this?

**Individual Contributions**
██████████████████████████████ $1,000,000,000
███████████████ $500,000,000
**Transfers**
██████████████████████████████ $100
███████████████ $50
**Other**
██████████████████████████████ $1
███████████████ $0.50


We had to change the font for stacked numbers because people thought $200,000 was more than $1,111,111 because it was wider
ex:
200,000
1,111,111

**Comment by rfultz** [comment]
@patphongs @johnnyporkchops any concerns ☝🏼 ?

**Comment by JonellaCulmer** [comment]
@rfultz Great questions. I think I'd prefer to the former to the latter. Even if the values in the latter two sections are much smaller, it would be good to show that, rather than have $100 and $1,000,000 be the same size. 
Would love to know what @PaulClark2 and @bmathesonFEC since they like "most" charts.

**Comment by patphongs** [comment]
@rfultz No concerns here, this sounds like a good plan. I'm closing out this issue as we move towards implementation.
