### ISSUE TITLE
Special elections work: Reach out to Public Records about their workflow

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#5105]
### Summary

**What we're after:**
Special elections work: Reach out to Public Records about a list of special elections. 
Understand how data trickles down from public records
The purpose of this is to be able to see the special election date, special election type (ie: general, etc) , state, district

### Future development considerations
- We should be able query these endpoints to populate the special election list:
Example queries:
     - https://api.open.fec.gov/v1/elections/?api_key=DEMO_KEY&cycle=2020&election_full=true&office=house&state=FL&stateFull=Florida&district=20&per_page=100&sort_hide_null=true

     - https://api.open.fec.gov/v1/election-dates/?api_key=DEMO_KEY&sort=election_date&min_election_date=2022-1-11

### Related issues
- https://github.com/fecgov/fec-cms/issues/5104

### Completion criteria
- [x] Have a better understanding of the Public Records workflow for special elections.

**Comment by JonellaCulmer** [comment]
Notes from discussion here: https://docs.google.com/document/d/1E6EELNjQfZgyA1QpdD7PhNUKGt41g56icdJuVn063oY/edit# 

Next steps are to schedule a meeting with the contractor to discuss how the feature works on their end, possibly a workshop to learn what we need to do in order to display special election candidates.
