### ISSUE TITLE
Updating footnote coding in Wagtail

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5317]
### Summary

On page with large charts and footnotes, whenever information changes and the footnotes need to be updated, it requires working through hundreds of lines of codes to make updates to individual footnotes throughout the chart. 

![image](https://user-images.githubusercontent.com/40633757/176191875-c3f7083b-816a-4450-a830-719f4136500c.png)

### Completion criteria

- [x] Update code/wagtail to allow for easier (and less chance for error) updates to the footnotes in large tables

**Comment by johnnyporkchops** [comment]
@djgarr Are talking about adding or changing the number in `<sup></sup>` on individual rows?
One thing that  would help would be if we formatted the html like this, then you could do a search on the page and be able to see what you have to change more easily rather than the completely jumbled html you are working with now. 
I am not sure how having this in Wagtail fields would be much easier as you would still be searching through the same amount of items, but in Wagtail fields instead of html which might actually be harder to find.
<img width="1170" alt="Screen Shot 2023-03-06 at 9 01 14 PM" src="https://user-images.githubusercontent.com/5572856/223300420-2acd5174-4c79-4f8c-9cb0-0d9f296f033d.png">

**Comment by djgarr** [comment]
@johnnyporkchops it's not necessarily that. Changing the code presentation might help a little, but the main issue is that if we have to update one row's footnotes because of new information or a change in a date, and because we start ordering the footnotes in order based on state alphabetical order, changing one footnote number means having to update all the remaining footnotes below it on the chart. If there was any way to automate or update that process, it would be a huge help
