### ISSUE TITLE
Update spending page on inaugural committee profiles 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5352]
**What we're after:**
Inaugural committees don't make independent expenditures, so this table should be removed from those profile pages. Additionally, the disbursements that these committees make are exclusively refunds, so that table should be updated to reflect that.

Committee example: https://www.fec.gov/data/committee/C00540005/?tab=spending 

**Completion criteria:**
- [x] Independent expenditures table is removed. There is no replacement necessary.
- [x] Disbursements table name changed to "Refunds"

**Comment by dorothyyeager** [comment]
“Refunds” works

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jonella ***@***.***>
Sent: Thursday, July 28, 2022 11:18:47 AM
To: fecgov/fec-cms ***@***.***>
Cc: Dorothy Yeager ***@***.***>; Mention ***@***.***>
Subject: [fecgov/fec-cms] Update spending page on inaugural committee profiles (Issue #5352)


What we're after:
Inaugural committees don't make independent expenditures, so this table should be removed from those profile pages. Additionally, the disbursements that these committees make are exclusively refunds, so that table should be updated to reflect that.

Committee example: https://www.fec.gov/data/committee/C00540005/?tab=spending<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fec.gov%2Fdata%2Fcommittee%2FC00540005%2F%3Ftab%3Dspending&data=05%7C01%7Cdyeager%40fec.gov%7C8bd3469a880c4f413d3c08da70ac79de%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C637946183335192082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eqVhNWwliKvcH08ByW1xKu8H%2BMFwnMK0RLnFufs3e0U%3D&reserved=0>

Completion criteria:

  *    Independent expenditures table is removed. There is no replacement necessary.
  *    Disbursements table name changed to "Refunds" or "Donation refunds" @dorothyyeager<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdorothyyeager&data=05%7C01%7Cdyeager%40fec.gov%7C8bd3469a880c4f413d3c08da70ac79de%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C637946183335192082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Lw%2Bcml7McYoNMNM9hqlhktLb5MDDWCrINIpEW5m5uoo%3D&reserved=0> @kathycarothers<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkathycarothers&data=05%7C01%7Cdyeager%40fec.gov%7C8bd3469a880c4f413d3c08da70ac79de%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C637946183335192082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W0T8XcezMo3pf5MbwI7mHem67l7Do9oV66CIKp9KnE8%3D&reserved=0> @djgarr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdjgarr&data=05%7C01%7Cdyeager%40fec.gov%7C8bd3469a880c4f413d3c08da70ac79de%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C637946183335192082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KP1R3YjVSACbb6yn0ulsuaxwxL37pScnnzOCONXJrQo%3D&reserved=0> please let me know which you prefer.
