### ISSUE TITLE
Update COVID language on meeting pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5743]
**What we're after:**
The snippet is not appearing on meeting pages after June through the rest of the year.  Need to determine why this is happening so that we can reliably display the snippet across meeting pages. May need to edit the page ~and insert the snippet box onto the page~. 

June 22: https://www.fec.gov/updates/june-22-2023-open-meeting/ (snippet appears)
July 13: https://www.fec.gov/updates/july-13-2023-open-meeting/ (snippet does not appear)

**Updated Information:** Snippet was not inserted on meeting pages for 2nd half of 2023 when initially created. As noted in comments below, the format is being changed to move from using the snippet to using the additional information field. We need to populate this field for the June - December meeting pages.

**Completion criteria:**
- [x] The snippet is deleted and replaced with this message in the additional information field:
Visitors must also follow current COVID-19 safety protocols, which are updated each Monday on the Commission's <a href=https://www.fec.gov/contact/ target="_blank"><strong>Contact page</strong></a>.

**Comment by dorothyyeager** [comment]
From Commission Secretary email on May 17:

Open meeting pages used to include a box on COVID info for those who plan to participate in the meeting:
[FEC | May 4, 2023 open meeting](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fec.gov%2Fupdates%2Fmay-04-2023-open-meeting%2F&data=05%7C01%7CITDWeb%40fec.gov%7C4ff6d144ce99450ff85f08db570af224%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C638199476842864861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K23cUXFv0NtTuEdtr5ehuHOY2t76ALuROaNhaSQmHDs%3D&reserved=0)
*This information correlated with information we include on all open meeting sunshine notices.

Starting with tomorrow’s meeting, the meeting page will include a link to the contact page where participants can find that same participation info instead of a box (so less space is used before users see the agenda):
[FEC | May 18, 2023 open meeting](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fec.gov%2Fupdates%2Fmay-18-2023-open-meeting%2F&data=05%7C01%7CITDWeb%40fec.gov%7C4ff6d144ce99450ff85f08db570af224%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C638199476842864861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MVr%2FHVp5sEdkeGff78sm2Yi28MFnEprStm5R9%2FgmYFQ%3D&reserved=0)

Upcoming meeting pages (for now will still include the box):
[FEC | June 1, 2023 open meeting](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fec.gov%2Fupdates%2Fjune-01-2023-open-meeting%2F&data=05%7C01%7CITDWeb%40fec.gov%7C4ff6d144ce99450ff85f08db570af224%7Cee91fa706c9d45e0bb084a355de91010%7C0%7C0%7C638199476842864861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZLUmwuZPvjQc0MffnCoymrxJX94YFPtKkzOgXIemH6w%3D&reserved=0)

*Starting with the July 13, 2023 meetings, we’ll either need to include links or the box on the pre-agenda pages.  We’ll do that as time permits.

**Comment by dorothyyeager** [comment]
Reviewing a Slack conversation, it looks like it was desired that we change out the snippet for the format used for May 18.  We could update the June pages accordingly too.

**Comment by dorothyyeager** [comment]
All updated for 2023.
