### ISSUE TITLE
Research removal of "FEC |  "and " - FEC.gov" from global search results titles

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5945]
**What we're after:**
Following the site map work, we are now displaying  `- FEC.gov` at the end of many wagtail pages. We would like to remove this as it adds no value while on the FEC website and potentially creates confusion regarding the storage of our content. 

Slack discussion: https://fecgov.slack.com/archives/C3X3K6EVA/p1695909045823319

### Completion criteria
- [ ] Research has been documented
- [ ] Next steps for removal have been proposed
- [ ] Followup tickets created for next steps. 

### Research considerations
- [ ] Document where the `FEC |` prefix and `- FEC.gov` suffix are coming from
- [ ] Document who's reading what (e.g. Google, Bing, social media, search.gov, fec.gov search results)
- [ ] Determine a path to fix based on the aforementioned topics

**Comment by rfultz** [comment]
FTR, we're adding the ` - FEC.gov` suffix in two-ish places—two lines of two templates

![image](https://github.com/fecgov/fec-cms/assets/26720877/900fa2b7-9726-4ce1-8eff-606331363474)

**Comment by johnnyporkchops** [comment]
###  Where the prefix/suffix come from:
 
 The `"FEC |  ..."` prefix comes from the `title_tag` field in Wagtail editing template's promote tab ( it's called `seo_title` in the database). 
- According to the conditional statement in the base.html  template , from which all pages inherit, the title will use the title_tag(seo_title) value if present, for a prefix,  othewise  a suffix of  `"  | FEC"` is added..
 -  The title_tag(seo_title) value from the Wagtail template is used in the page's browser tag
 - It also shows up in the title on search-result listings
 -  However, the following pages that use `get_content_secrtion(self)` in models.py do not show value from the title_tag(seo_title) in search-result listings. Instead, they get a suffix of "- FEC.gov" from meta tags in `partials/mets-tags.html`
     - ResourcePage, CustomPage, RecordPage, CollectionPage, DocumentFeedPage
### How to remove the prefix/suffix from search.gov, site-search results:
This branch has a filter added to the search.html template to remove both pattens (`FEC | ` and  ` - FEC.gov`) from the titles of site-search results.
 
   - **Branch:**  `feature/5945-rm-prefix-suffix-from-insite-search-results`
   - **Note:** Because of match-highlighting, searches performed with FEC or FEC.gov as a seerch term cannot temove these patterns
