### ISSUE TITLE
Wagtail Wish List: Make it so anchor links go to the thing we linked and not the space below it.

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5999]
### Summary

When you create an anchor link in Wagtail, it works but when the link is clicked, it takes the user to the line below.

It should take the user to the text we selected to make the anchor link.

### Frequency

Ongoing issue

### How to Reproduce

_List any steps you took for this issue to happen. Be sure to include the URL and what you clicked or entered. More details are better._
URL: https://www.fec.gov/…

1. In Wagtail, I edited the Policy and other guidance page and selected the text "Improvements to report filing processes and website usability (2023)" then pressed the # button to make the anchor link
2. When you click the link https://www.fec.gov/legal-resources/policy-other-guidance/#improvements-to-report-filing-processes-and-website-usability-2023, you'll notice it goes to the blank line under the text that was selected. The user has to scroll up to see the actual text. (So it got them to the right part of the page, but one line below where we'd ideally like to go with that link)

### Device, browser, etc

Chrome, Wagtail, laptop

### Screenshots

What it should look like when clicked:
![image](https://github.com/fecgov/fec-cms/assets/24437369/419fcaf6-3eda-4db6-beeb-850a9d39663e)

What it does look like when clicked (anchor text is cut off).
![image](https://github.com/fecgov/fec-cms/assets/24437369/e476adde-b3e2-4c17-80d5-7c4b81a51472)

**Comment by johnnyporkchops** [comment]
@dorothyyeager These kind of Wagtail anchor links seems to work "in-page"--if you are linking from one place in that page to the anchor. When you are coming to the link inbound from another page or as a copy/pasted link in the URL bar, there does not seem to be a guarantee it will land exactly where we would want, with the anchored-text showing.

Since there are only three of these anchors on the page, one way to guarantee it goes above the link is to add an html block with a named anchor just above  it, like this example on dev. 
https://dev.fec.gov/legal-resources/policy-other-guidance/#recordkeeping-requirements-for-payroll-deduction-authorizations-2006

The section in your example above is not on this older version of the page on dev, so I am just using  Recordkeeping requirements etc... as an example.

**Comment by dorothyyeager** [comment]
I gave it a try but it didn't work... https://www.fec.gov/legal-resources/policy-other-guidance/#improvements-to-report-filing-processes-and-website-usability-2023
