### ISSUE TITLE
Images are caching in Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6158]
**Thank you for your interest in helping improve the FEC CMS.**

Below, you'll find questions to help us more quickly identify, prioritize, and then address the issue.

### Summary

Replacement images uploaded into Wagtail cached with weird characters added into the URL and sometimes showing the old image.

We should be able to swap out the images without weird characters

### Frequency

Randomly

### How to Reproduce

1. Go to Duane Pugh's image in Wagtail
2. Replace with image file of the same name
3. See if the image on this page changes https://www.fec.gov/about/leadership-and-structure/fec-offices/communication-offices/#office-of-congressional-legislative-and-intergovernmental-affairs

### Device, browser, etc

This was observed by multiple people on the content channel using Chrome, Edge and Firefox

 
### Misc

Refer to conversations in content channel on Slack on March 14 and 15.

**Comment by patphongs** [comment]
Thank you @dorothyyeager for logging this ticket. The thing about wagtail content, including documents and especially images, is that we cache it in order to have optimal performance on the CMS. Images load directly onto a page and can take longer to load, especially if there's several pages. The additional hash that gets added onto the image filename allows for cache busting. Cache busting is adding a differential in the file name in order to make the cache update and load in the new image when the page is loaded. Keeping this would be best if we don't need to reference a direct link to an image like we do for documents.
