### ISSUE TITLE
Research: AO search missing entity type filters: Commenter and Counsel/Representative

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6441]
Blocked by: https://github.com/fecgov/fec-cms/issues/6451

### Summary

**What we're after:**
_Determine what the purpose of the entity type filters "Commenter" and "Counsel/Representative" are and whether needed for the AO search. The recent respondent work may help to solve this issue as well._

<img width="509" alt="Screenshot 2024-08-21 at 9 51 26 PM" src="https://github.com/user-attachments/assets/174b5a1e-b9f3-4f0e-ad15-93213a0fa43b">

### Research notes
- We've discovered some issues with requestor and entity names that may conflict. We should dive deeper into researching this. Here's the [thread](https://fecgov.slack.com/archives/C3X3K6EVA/p1724853125877599) we had about this issue.

### Completion criteria

- [x] Documented purpose of the entity type filter
- [x] Determine if it is a required filter
   - [x] If required, create a plan, design, and ticket to implement the filter

**Comment by patphongs** [comment]
The assumption is that `requestor name` is a separate field from `entity name`. Therefore, we may only. need entity name to only include commenters and counsel, but not requestor. We need to verify this assumption with OGC Policy to ensure that we understand what is necessary for these search fields.

**Comment by isaacjamesbaker** [comment]
Update after meeting with a Policy Assistant GC. They are much more familiar with SAOS, which has the entity type and lists pull-down options for:
•	Requestor 
•	Commenter 
•	Counsel/Representative

The current AO system, as you know, already has a requestor name search at the top. This is great because it’s a very common way to search for AOs and allows for a wide range of options concerning type of requestor. 

![Image](https://github.com/user-attachments/assets/4f95ba0b-9892-4cb1-9c16-1bf7defe8b8b)

The current entity name search doesn’t break down the entities into types but does work for all entity types. A search for a requestor in the entity name search brings up the requestor, and also any commenters or counsel/representatives. This entity type filter is perhaps not used as commonly but, when needed, it is very good to have, as it allows users to search for other commenters, recurring counsel for various AOs, etc. 
 
![Image](https://github.com/user-attachments/assets/c1308df9-d7e2-4df5-a9e7-63c9b7bf57d8)

Keeping requestors searchable in the entity name isn’t necessarily a bad thing, but considering it says “other entities” it may be a bit confusing. Jonella asked: If we retain the requestor name/AO name field, are we comfortable with an overlap with entity name if it also searches requestor name? The answer is yes. However, if we are building out new dropdown menus, and keeping the requestor name search as a separate filter, it would be sufficient to include only commenter and counsel/representative as options and have the entity name search just those two types of entities. I’m not sure which route is easier. The informational text needs to be clear whatever route is taken, so that users know whether entity search includes requestor or not.
