### ISSUE TITLE
Add filter by subjects for MUR and ADR search

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6500]
### Summary

**What we're after:**
Two single select dropdown lists of MUR subjects is integrated into the MUR and ADR search features (primary_subject_id and secondary_subject_id). The list of subjects is hardcoded in the CMS based on this [subjects list mapping](https://github.com/fecgov/openFEC/issues/5965). (This is like audit search)

The filter applies the condition `primary_subject_id` to refine search results and adds secondary_subject_id if it applies. The secondary dependency will also be built into the front end subjects list.

### Design

![Image](https://github.com/user-attachments/assets/b4df2cba-5b4e-438c-bf62-287e06835d0a)

### Related issues

- https://github.com/fecgov/openFEC/issues/5965
- https://github.com/fecgov/openFEC/pull/5997

### Completion criteria
- [ ] Dropdown filter for subjects are added for MUR and ADR search

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , @patphongs In the design mockup above, it looks like, when a primary_subject that has a secondary dropdown is chosen, it  defaults to the first  secondary_subject  option ( "Candidates" in the example). Should we consider a scenario where the user does not want to choose a secondary option  ... so that would instead default to "More" or "All" the first secondary dropdown item.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer "More" is the default "choice" for the primary subject dropdown, which, on these two legal pages (MURS and ADRs) just means it does not filter on subjects or in other words,  includes all.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Thanks for clarifying. I appreciate it.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer . I can use "All" for now because thats how we present the two dropdowns for audit search. It is also more semantically evident for screen readers. 

After looking through the site's single-select dropdowns, I noticed that we use "More" (receipts) , "Any"(AOs) and "All" (audit search). Maybe we would want to consider making this uniform? We can also put `aria-labels` on them to clarify that any of those terms mean it is searching all (or not filtering by that parameter)
Just to clarify, what is passed to the API for legal searches for any of those scenarios is "", essentially meaning no-value.
